packages:
  - apps/web
  - packages/api-client
ignoreScripts: true
overrides:
  '@csstools/css-color-parser': '4.1.1'
  '@napi-rs/wasm-runtime': '1.1.4'
  acorn: '8.16.0'
  nanoid: '3.3.12'
  obug: '2.1.2'
  postcss-selector-parser: '6.1.2'
  tldts: '7.4.2'
  tldts-core: '7.4.2'
  undici: '7.27.1'
