packages:
  - apps/web
  - apps/mobile
  - packages/api-client
ignoreScripts: true
overrides:
  '@0no-co/graphql.web': '1.2.0'
  '@csstools/css-color-parser': '4.1.1'
  '@jest/schemas@30.4.1>@sinclair/typebox': '0.34.49'
  '@napi-rs/wasm-runtime': '1.1.4'
  '@react-navigation/core': '7.18.0'
  '@react-navigation/elements': '2.9.20'
  '@react-navigation/native-stack': '7.14.5'
  '@react-navigation/routers': '7.5.5'
  '@radix-ui/react-collection': '1.1.9'
  '@radix-ui/react-dialog': '1.1.16'
  '@radix-ui/react-dismissable-layer': '1.1.12'
  '@radix-ui/react-focus-scope': '1.1.9'
  '@radix-ui/react-portal': '1.1.11'
  '@radix-ui/react-primitive': '2.1.5'
  '@radix-ui/react-roving-focus': '1.1.12'
  '@radix-ui/react-slot': '1.2.5'
  '@radix-ui/react-tabs': '1.1.14'
  acorn: '8.16.0'
  baseline-browser-mapping: '2.10.34'
  caniuse-lite: '1.0.30001797'
  dnssd-advertise: '1.1.4'
  electron-to-chromium: '1.5.368'
  nanoid: '3.3.12'
  node-releases: '2.0.47'
  obug: '2.1.2'
  postcss-selector-parser: '6.1.2'
  regjsparser: '0.13.1'
  semver: '7.8.2'
  tldts: '7.4.2'
  tldts-core: '7.4.2'
  undici: '7.27.1'
  yargs: '17.7.2'
