package ports

import "context"

type EventName string

const (
	EventHealthChecked                        EventName = "health.checked"
	EventHTTPServerStartFailed                EventName = "http.server.start_failed"
	EventHTTPServerShutdownFailed             EventName = "http.server.shutdown_failed"
	EventApplicationStartupFailed             EventName = "application.startup_failed"
	EventApplicationShutdownFailed            EventName = "application.shutdown_failed"
	EventAuthenticationFailed                 EventName = "authentication.failed"
	EventAuthorizationDenied                  EventName = "authorization.denied"
	EventTenantCreated                        EventName = "tenant.created"
	EventTenantViewed                         EventName = "tenant.viewed"
	EventTenantsListed                        EventName = "tenant.listed"
	EventTenantUpdated                        EventName = "tenant.updated"
	EventTenantArchived                       EventName = "tenant.archived"
	EventTenantRestored                       EventName = "tenant.restored"
	EventTenantDeleted                        EventName = "tenant.deleted"
	EventInventoryCreated                     EventName = "inventory.created"
	EventInventoryViewed                      EventName = "inventory.viewed"
	EventInventoryUpdated                     EventName = "inventory.updated"
	EventInventoryArchived                    EventName = "inventory.archived"
	EventInventoryRestored                    EventName = "inventory.restored"
	EventInventoryDeleted                     EventName = "inventory.deleted"
	EventInventoriesListed                    EventName = "inventory.listed"
	EventInventoryAccessGranted               EventName = "inventory_access.granted"
	EventInventoryAccessViewed                EventName = "inventory_access.viewed"
	EventInventoryAccessRevoked               EventName = "inventory_access.revoked"
	EventInventoryAccessListed                EventName = "inventory_access.listed"
	EventInventoryInvitationCreated           EventName = "inventory_invitation.created"
	EventInventoryInvitationViewed            EventName = "inventory_invitation.viewed"
	EventInventoryInvitationListed            EventName = "inventory_invitation.listed"
	EventInventoryInvitationAccepted          EventName = "inventory_invitation.accepted"
	EventInventoryInvitationExpirationUpdated EventName = "inventory_invitation.expiration_updated"
	EventInventoryInvitationRevoked           EventName = "inventory_invitation.revoked"
	EventInventoryInvitationCancelled         EventName = "inventory_invitation.cancelled"
	EventInventoryInvitationDeleted           EventName = "inventory_invitation.deleted"
	EventCustomAssetTypeCreated               EventName = "custom_asset_type.created"
	EventCustomAssetTypeViewed                EventName = "custom_asset_type.viewed"
	EventCustomAssetTypeUpdated               EventName = "custom_asset_type.updated"
	EventCustomAssetTypeArchived              EventName = "custom_asset_type.archived"
	EventCustomAssetTypeRestored              EventName = "custom_asset_type.restored"
	EventCustomAssetTypeDeleted               EventName = "custom_asset_type.deleted"
	EventCustomAssetTypesListed               EventName = "custom_asset_type.listed"
	EventCustomFieldDefinitionCreated         EventName = "custom_field_definition.created"
	EventCustomFieldDefinitionViewed          EventName = "custom_field_definition.viewed"
	EventCustomFieldDefinitionUpdated         EventName = "custom_field_definition.updated"
	EventCustomFieldDefinitionArchived        EventName = "custom_field_definition.archived"
	EventCustomFieldDefinitionRestored        EventName = "custom_field_definition.restored"
	EventCustomFieldDefinitionDeleted         EventName = "custom_field_definition.deleted"
	EventCustomFieldDefinitionsListed         EventName = "custom_field_definition.listed"
	EventAssetCreated                         EventName = "asset.created"
	EventAssetViewed                          EventName = "asset.viewed"
	EventAssetUpdated                         EventName = "asset.updated"
	EventAssetArchived                        EventName = "asset.archived"
	EventAssetRestored                        EventName = "asset.restored"
	EventAssetDeleted                         EventName = "asset.deleted"
	EventAssetsListed                         EventName = "asset.listed"
	EventAssetsSearched                       EventName = "asset.searched"
	EventAttachmentCreated                    EventName = "attachment.created"
	EventAttachmentViewed                     EventName = "attachment.viewed"
	EventAttachmentsListed                    EventName = "attachment.listed"
	EventAttachmentContentDownloaded          EventName = "attachment_content.downloaded"
	EventAttachmentDirectUploadCreated        EventName = "attachment_direct_upload.created"
	EventAttachmentDirectUploadCompleted      EventName = "attachment_direct_upload.completed"
	EventAttachmentThumbnailGenerated         EventName = "attachment_thumbnail.generated"
	EventAttachmentModelImagePrepared         EventName = "attachment_model_image.prepared"
	EventAttachmentArchived                   EventName = "attachment.archived"
	EventAttachmentRestored                   EventName = "attachment.restored"
	EventAttachmentDeleted                    EventName = "attachment.deleted"
	EventBlobStorageFailed                    EventName = "blob_storage.failed"
	EventBlobDeletionOutboxClaimed            EventName = "blob_deletion_outbox.claimed"
	EventBlobDeletionOutboxProcessed          EventName = "blob_deletion_outbox.processed"
	EventBlobDeletionOutboxFailed             EventName = "blob_deletion_outbox.failed"
	EventBlobDeletionOutboxDeadLettered       EventName = "blob_deletion_outbox.dead_lettered"
	EventAuditRecordsListed                   EventName = "audit_record.listed"
	EventUndoableOperationUndone              EventName = "undoable_operation.undone"
	EventUndoableOperationRedone              EventName = "undoable_operation.redone"
	EventAuthorizationOutboxDrained           EventName = "authorization_outbox.drained"
	EventAuthorizationOutboxFailed            EventName = "authorization_outbox.failed"
	EventAuthorizationOutboxDeadLettered      EventName = "authorization_outbox.dead_lettered"
	EventHTTPRateLimited                      EventName = "http.rate_limited"
	EventProviderProfileCreated               EventName = "provider_profile.created"
	EventProviderProfileViewed                EventName = "provider_profile.viewed"
	EventProviderProfilesListed               EventName = "provider_profile.listed"
	EventProviderProfileEnabled               EventName = "provider_profile.enabled"
	EventProviderProfileDisabled              EventName = "provider_profile.disabled"
	EventProviderProfileArchived              EventName = "provider_profile.archived"
)

type Event struct {
	Name    EventName
	Message string
	Fields  map[string]string
}

type Observer interface {
	Record(ctx context.Context, event Event)
}
