package bootstrap

func accessHelp() []commandHelp {
	return []commandHelp{
		{Path: "account show", Scope: helpAccount, Summary: "Inspect the signed-in account."},
		{Path: "tenants list", Scope: helpAccount, Summary: "List accessible households.", Options: "limit cursor"},
		{Path: "tenants show", Scope: helpHousehold, Summary: "Inspect the selected household."},
		{Path: "tenants create", Scope: helpAccount, Summary: "Create a household.", Options: "name input", Input: "Supply --name NAME or --input FILE|- with name. Interactive terminals can ask for the name; do not combine field flags and JSON.", Example: "tenants create --name \"Home\""},
		{Path: "tenants update", Scope: helpHousehold, Summary: "Update the selected household.", Options: "name input", Input: "Supply --name NAME or --input FILE|- with the changed fields; do not combine field flags and JSON.", Example: "tenants update --name \"Home\""},
		{Path: "tenants archive", Scope: helpHousehold, Summary: "Archive the selected household.", Confirm: true},
		{Path: "tenants restore", Scope: helpHousehold, Summary: "Restore the selected household."},
		{Path: "tenants delete", Scope: helpHousehold, Summary: "Permanently delete the selected household.", Confirm: true},
		{Path: "tenants audit", Scope: helpHousehold, Summary: "Read audit records for the selected household.", Options: "limit cursor"},
		{Path: "inventories list", Scope: helpHousehold, Summary: "List accessible inventories.", Options: "limit cursor"},
		{Path: "inventories show", Scope: helpInventory, Summary: "Inspect the selected inventory."},
		{Path: "inventories create", Scope: helpHousehold, Summary: "Create a inventory.", Options: "name input", Input: "Supply --name NAME or --input FILE|- with name. Interactive terminals can ask for the name; do not combine field flags and JSON.", Example: "inventories create --name \"Home\""},
		{Path: "inventories update", Scope: helpInventory, Summary: "Update the selected inventory.", Options: "name input", Input: "Supply --name NAME or --input FILE|- with the changed fields; do not combine field flags and JSON.", Example: "inventories update --name \"Home\""},
		{Path: "inventories archive", Scope: helpInventory, Summary: "Archive the selected inventory.", Confirm: true},
		{Path: "inventories restore", Scope: helpInventory, Summary: "Restore the selected inventory."},
		{Path: "inventories delete", Scope: helpInventory, Summary: "Permanently delete the selected inventory.", Confirm: true},
		{Path: "inventories audit", Scope: helpInventory, Summary: "Read audit records for the selected inventory.", Options: "limit cursor"},
		{Path: "access-grants list", Scope: helpInventory, Summary: "List inventory access grants.", Options: "limit cursor"},
		{Path: "access-grants show", Arguments: "PRINCIPAL_ID RELATIONSHIP", Scope: helpInventory, Summary: "Inspect a viewer or editor relationship.", Input: "RELATIONSHIP is viewer or editor.", Example: "access-grants show PRINCIPAL_ID viewer"},
		{Path: "access-grants remove", Arguments: "PRINCIPAL_ID RELATIONSHIP", Scope: helpInventory, Summary: "Remove one viewer or editor relationship.", Input: "RELATIONSHIP is viewer or editor. Other grants may still provide access.", Confirm: true, Example: "access-grants remove PRINCIPAL_ID viewer --yes"},
		{Path: "access-grants create", Scope: helpInventory, Summary: "Grant viewer or editor access to the inventory.", Options: "input", Input: "JSON requires principalId and relationship (viewer or editor). Interactive terminals can ask; scripts must use --input FILE|-.", Confirm: true, Example: "access-grants create --input grant.json --yes"},
		{Path: "invitations list", Scope: helpInventory, Summary: "List inventory invitations.", Options: "status limit cursor", Input: "Status is pending, accepted, cancelled, expired, revoked or all."},
		{Path: "invitations show", Arguments: "INVITATION_ID", Scope: helpInventory, Summary: "Inspect an invitation."},
		{Path: "invitations cancel", Arguments: "INVITATION_ID", Scope: helpInventory, Summary: "Cancel an invitation without changing existing grants.", Confirm: true},
		{Path: "invitations delete", Arguments: "INVITATION_ID", Scope: helpInventory, Summary: "Delete an invitation without changing existing grants.", Confirm: true},
		{Path: "invitations preview", Arguments: "INVITATION_ID", Scope: helpInventory, Summary: "Preview an invitation using its acceptance token.", Options: "input", Input: "JSON requires acceptanceToken. Interactive terminals prompt without echo; scripts use --input FILE|-.", Example: "invitations preview INVITATION_ID --input invitation.json"},
		{Path: "invitations accept", Arguments: "INVITATION_ID", Scope: helpInventory, Summary: "Accept an invitation using its acceptance token.", Options: "input", Input: "JSON requires acceptanceToken. Interactive terminals prompt without echo; scripts use --input FILE|-.", Confirm: true, Example: "invitations accept INVITATION_ID --input invitation.json --yes"},
		{Path: "invitations expiration", Arguments: "INVITATION_ID", Scope: helpInventory, Summary: "Change invitation expiration.", Options: "input", Input: "JSON requires expiresAt (an RFC3339 timestamp). Interactive terminals can ask; scripts use --input FILE|-.", Confirm: true, Example: "invitations expiration INVITATION_ID --input expiration.json --yes"},
		{Path: "operations undo", Arguments: "OPERATION_ID", Scope: helpInventory, Summary: "Undo an eligible recorded operation.", Confirm: true},
		{Path: "operations redo", Arguments: "OPERATION_ID", Scope: helpInventory, Summary: "Redo an eligible recorded operation.", Confirm: true},
		{Path: "notifications list", Scope: helpInventory, Summary: "List notifications.", Options: "unread-only limit cursor"},
		{Path: "notifications show", Arguments: "NOTIFICATION_ID", Scope: helpInventory, Summary: "Inspect a notification."},
		{Path: "notifications read", Arguments: "NOTIFICATION_ID", Scope: helpInventory, Summary: "Mark a notification as read."},
		{Path: "notifications unread", Arguments: "NOTIFICATION_ID", Scope: helpInventory, Summary: "Mark a notification as unread."},
		{Path: "notifications unread-count", Scope: helpInventory, Summary: "Count a bounded page of unread notifications.", Options: "cursor", Input: "Continue with the returned cursor to finish counting."},
		{Path: "notifications read-all", Scope: helpInventory, Summary: "Mark a bounded page of notifications as read.", Options: "cursor", Input: "Continue with the returned cursor until complete."},
		{Path: "notification-devices show", Arguments: "INSTALLATION_ID", Scope: helpInventory, Summary: "Inspect a push device registration."},
		{Path: "notification-devices register", Scope: helpInventory, Summary: "Register a push device.", Options: "input", Input: "JSON requires installationId, transport (apns or fcm), token, and revision (0 for a first registration). Interactive terminals can ask; scripts use --input FILE|-.", Example: "notification-devices register --input device.json"},
		{Path: "notification-devices remove", Arguments: "DEVICE_ID", Scope: helpInventory, Summary: "Remove a device registration.", Options: "revision", Input: "Supply the positive --revision from notification-devices show.", Confirm: true, Example: "notification-devices remove DEVICE_ID --revision 1 --yes"},
		{Path: "notification-preferences show", Scope: helpInventory, Summary: "Inspect inventory notification preferences."},
		{Path: "notification-preferences initialize", Scope: helpInventory, Summary: "Initialize notification preferences.", Options: "timezone input", Input: "Supply --timezone ZONE or --input FILE|- with timezone. Interactive terminals can ask.", Example: "notification-preferences initialize --timezone Europe/London"},
		{Path: "notification-preferences update", Scope: helpInventory, Summary: "Edit notification preferences.", Options: "input", Input: "Interactive terminals offer an editor. Scripts must supply --input FILE|- with complete settings and the current revision.", Example: "notification-preferences update --input preferences.json"},
		{Path: "notification-preferences override", Arguments: "TYPE_ID", Scope: helpInventory, Summary: "Edit notification settings for an asset type.", Options: "input", Input: "Interactive terminals offer an editor. Scripts must supply --input FILE|- with complete settings and the current revision.", Example: "notification-preferences override TYPE_ID --input preferences.json"},
		{Path: "notification-preferences remove-override", Arguments: "TYPE_ID", Scope: helpInventory, Summary: "Remove an asset-type override and use the defaults.", Options: "revision", Input: "Supply the positive --revision from notification-preferences show.", Confirm: true, Example: "notification-preferences remove-override TYPE_ID --revision 1 --yes"},
	}
}
