package bootstrap

func inventoryHelp() []commandHelp {
	return []commandHelp{
		{Path: "assets list", Scope: helpInventory, Summary: "List assets in the selected inventory.", Options: "limit cursor lifecycle sort"},
		{Path: "assets show", Arguments: "ASSET_ID", Scope: helpInventory, Summary: "Inspect an asset."},
		{Path: "assets create", Scope: helpInventory, Summary: "Create an item, container or location.", Options: "kind title parent input print-label printer template template-version copies show-reference idempotency-key", Input: "Use --kind item|container|location and --title TITLE, or one JSON object with --input FILE|-; do not mix field flags with JSON. Interactive terminals can ask for missing fields. Retry keys require printLabel/--print-label; reuse the same key and unchanged payload after an uncertain printed creation.", Example: "assets create --kind item --title \"Cordless drill\""},
		{Path: "assets update", Arguments: "ASSET_ID", Scope: helpInventory, Summary: "Update asset fields.", Options: "title input", Input: "Use --title TITLE or --input FILE|- with the changed fields; do not combine them.", Example: "assets update ASSET_ID --title \"Cordless drill\""},
		{Path: "assets move", Arguments: "ASSET_ID", Scope: helpInventory, Summary: "Move an asset into a parent or to the inventory root.", Options: "parent", Input: "Supply --parent PARENT_ID, or --parent root.", Example: "assets move ASSET_ID --parent root"},
		{Path: "assets archive", Arguments: "ASSET_ID", Scope: helpInventory, Summary: "Hide an asset from active lists.", Confirm: true},
		{Path: "assets restore", Arguments: "ASSET_ID", Scope: helpInventory, Summary: "Restore an archived asset."},
		{Path: "assets delete", Arguments: "ASSET_ID", Scope: helpInventory, Summary: "Permanently delete an asset.", Confirm: true},
		{Path: "assets expiration", Scope: helpInventory, Summary: "Browse expiration dates with combined filters.", Options: "mode kind checkout-state query type-id tag-id location-id from-date through-date limit cursor", Input: "Dates use YYYY-MM-DD. Repeat --tag-id for multiple required tags. --limit accepts 1–100; mode is all, soon or expired; checkout-state is any, available or checked_out."},
		{Path: "assets checked-out", Scope: helpInventory, Summary: "List checked-out assets.", Options: "limit cursor"},
		{Path: "assets checkout", Arguments: "ASSET_ID", Scope: helpInventory, Summary: "Check out an available asset.", Options: "details input", Input: "Optional --details TEXT, or --input FILE|- containing checkout/return details. Do not combine them."},
		{Path: "assets return", Arguments: "ASSET_ID", Scope: helpInventory, Summary: "Return a checked-out asset.", Options: "details input", Input: "Optional --details TEXT, or --input FILE|- containing checkout/return details. Do not combine them."},
		{Path: "assets checkouts", Arguments: "ASSET_ID", Scope: helpInventory, Summary: "List checkout history for an asset.", Options: "limit cursor"},
		{Path: "assets return-details", Arguments: "ASSET_ID CHECKOUT_ID", Scope: helpInventory, Summary: "Update notes on an asset return.", Options: "details input", Input: "Supply --details TEXT or --input FILE|- with details.", Example: "assets return-details ASSET_ID CHECKOUT_ID --details \"Returned to shelf\""},
		{Path: "assets activity", Arguments: "ASSET_ID", Scope: helpInventory, Summary: "Read an asset activity timeline.", Options: "view limit cursor"},
		{Path: "assets audit", Arguments: "ASSET_ID", Scope: helpInventory, Summary: "Read audit records for an asset.", Options: "limit"},
		{Path: "attachments list", Arguments: "ASSET_ID", Scope: helpInventory, Summary: "List asset attachments.", Options: "limit cursor"},
		{Path: "attachments show", Arguments: "ASSET_ID ATTACHMENT_ID", Scope: helpInventory, Summary: "Inspect an attachment."},
		{Path: "attachments complete-upload", Arguments: "ASSET_ID UPLOAD_ID", Scope: helpInventory, Summary: "Complete an existing upload session."},
		{Path: "attachments archive", Arguments: "ASSET_ID ATTACHMENT_ID", Scope: helpInventory, Summary: "Hide an attachment from active lists.", Confirm: true},
		{Path: "attachments restore", Arguments: "ASSET_ID ATTACHMENT_ID", Scope: helpInventory, Summary: "Restore an archived attachment."},
		{Path: "attachments delete", Arguments: "ASSET_ID ATTACHMENT_ID", Scope: helpInventory, Summary: "Permanently delete an attachment.", Confirm: true},
		{Path: "tags list", Scope: helpInventory, Summary: "List inventory tags.", Options: "limit cursor"},
		{Path: "tags create", Scope: helpInventory, Summary: "Create an inventory tag.", Options: "name key tag-color input", Input: "Supply --name NAME with optional --key KEY and --tag-color HEX, or --input FILE|-; do not combine field flags and JSON.", Example: "tags create --name \"Tools\""},
		{Path: "tags update", Arguments: "TAG_ID", Scope: helpInventory, Summary: "Update a tag name or color.", Options: "name tag-color input", Input: "Supply --name NAME and/or --tag-color HEX, or --input FILE|-; an empty color clears it.", Example: "tags update TAG_ID --name \"Power tools\""},
		{Path: "tags delete", Arguments: "TAG_ID", Scope: helpInventory, Summary: "Delete an inventory tag.", Confirm: true},
		{Path: "import-jobs list", Scope: helpInventory, Summary: "List import jobs."},
		{Path: "import-jobs show", Arguments: "JOB_ID", Scope: helpInventory, Summary: "Inspect an import job."},
		{Path: "import-jobs delete", Arguments: "JOB_ID", Scope: helpInventory, Summary: "Remove a job from history while keeping imported assets.", Confirm: true},
		{Path: "import-jobs cancel", Arguments: "JOB_ID", Scope: helpInventory, Summary: "Cancel an import with an explicit partial-progress choice.", Options: "input", Input: "JSON requires mode: keep_partial_progress or discard_partial_progress. Interactive terminals offer the same choice; scripts must use --input FILE|-.", Confirm: true, Example: "import-jobs cancel JOB_ID --input cancellation.json --yes"},
	}
}
