/** Portable archive task copy shared by web and mobile. */
export const archiveMessages = {
  'archive.fileType': 'Stuff Stash archive',
  'archive.export': 'Export archive',
  'archive.restore': 'Restore inventory',
  'archive.description': 'An archive contains complete inventory data and the photos and files you include.',
  'archive.restoreDescription': 'Choose a Stuff Stash ZIP archive. Review it before creating a new inventory in this household.',
  'archive.photos': 'Photos',
  'archive.files': 'Other files',
  'archive.metadata': 'Inventory data, tags, types and custom fields are always included.',
  'archive.partial': 'Without all photos and files, this is a partial backup.',
  'archive.create': 'Create archive',
  'archive.chooseFile': 'Choose archive',
  'archive.upload': 'Upload and validate',
  'archive.busy': 'Working…',
  'archive.jobs': 'Recent jobs',
  'archive.noJobs': 'No archive jobs yet.',
  'archive.loading': 'Loading jobs…',
  'archive.queued': 'Queued',
  'archive.running': 'Preparing archive',
  'archive.validating': 'Validating archive',
  'archive.restoring': 'Restoring inventory',
  'archive.awaiting_approval': 'Ready to review',
  'archive.ready': 'Ready',
  'archive.failed': 'Failed',
  'archive.cancelled': 'Cancelled',
  'archive.expired': 'Expired',
  'archive.expires': 'Available until {date}',
  'archive.download': 'Download',
  'archive.cancel': 'Cancel job',
  'archive.retry': 'Retry',
  'archive.review': 'Review restore',
  'archive.open': 'Open inventory',
  'archive.name': 'Inventory name',
  'archive.newInventory': 'This creates a new inventory. Existing inventories will not change.',
  'archive.counts': '{assets} items · {tags} tags · {photos} photos · {files} files',
  'archive.definitions': '{types} custom types · {fields} custom fields',
  'archive.omitted': '{count} attachments omitted',
  'archive.remappings': '{count} conflicting definition keys will be renamed.',
  'archive.close': 'Close',
  'archive.closeReview': 'Close review',
  'archive.more': 'Load more',
  'archive.streamingRequired': 'For archives over 128 MiB, use a browser with direct file saving, such as Chrome or Edge on desktop, or use the mobile app.',
  'archive.error': 'Could not complete this request. Try again.',
  'archive.denied': 'You no longer have permission to use these archive jobs.',
  'archive.signIn': 'Sign in again to continue.',
  'archive.tooLarge': 'This archive exceeds the server’s size limit.',
  'archive.downloadStarted': 'Archive download started.',
  'archive.leave': 'You can leave this page while the server works.'
} as const;
