export const labelMobileMessages = {
  'labels.mobile.title': 'Label options',
  'labels.mobile.scan': 'Scan label',
  'labels.mobile.cancel': 'Cancel',
  'labels.mobile.template': 'Layout',
  'labels.mobile.referenceHelp': 'Shows the label’s ID as readable text alongside the QR code.',
  'labels.mobile.noPrinter': 'No label printer is registered. Save or share a label to print using another app.',
  'labels.mobile.reference': 'Show reference',
  'labels.mobile.preview': 'Preview label',
  'labels.mobile.sharePNG': 'Save or share PNG',
  'labels.mobile.sharePDF': 'Save or share PDF',
  'labels.mobile.print': 'Print…',
  'labels.mobile.loading': 'Loading label…',
  'labels.mobile.unavailable': 'Label unavailable. Check your connection and access, then try again.',
  'labels.mobile.mediaUnavailable': 'No supported label size is available.',
  'labels.mobile.paste': 'Paste label link',
  'labels.mobile.open': 'Open label',
  'labels.mobile.camera': 'Use camera',
  'labels.mobile.cameraDenied': 'Camera unavailable. Allow camera access in Settings, or paste a label link.',
  'labels.mobile.resolving': 'Opening label…',
  'labels.mobile.wrongInstance': 'This label belongs to another Stuff Stash instance. Connect to that server and try again.',
  'labels.mobile.ready': 'Your label is ready to open.',
  'labels.mobile.pending': 'Your label is waiting. Sign in to open it.',
  'labels.mobile.unsupported': 'This is not a supported Stuff Stash label.',
  'labels.mobile.retry': 'Try again',
  'labels.mobile.archived': 'This asset is archived.',
  'labels.mobile.previewAlt': 'Label preview',
  'labels.mobile.server': 'Change server',
  'labels.mobile.account': 'Switch account',
  'labels.mobile.size': 'Label size',
  'labels.mobile.sizeValue': '{width} × {height} mm',
  'labels.mobile.actualSize': 'Print at actual size (100%) without scaling to fit.',
  'labels.mobile.saved': 'Label ready',
} as const;
