/** Mobile presentation messages. Keys describe context, never wire values. */
export const mobileMessages = {
  "mobile.AppKeyboardAccessoryios.hidesTheKeyboardWithoutSubmitting": "Hides the keyboard without submitting",
  "mobile.AppKeyboardAccessoryios.dismissKeyboard": "Dismiss keyboard",
  "mobile.AppearancePicker.appearanceNotSaved": "Appearance not saved",
  "mobile.AppearancePicker.stuffStashCouldNotSaveTheAppearanceSetting": "Stuff Stash could not save the appearance setting.",
  "mobile.AppearancePicker.appearance": "Appearance",
  "mobile.AppearancePicker.chooseAppearance": "Choose appearance",
  "mobile.AssetCard.matched": "Matched ",
  "mobile.AssetContainedWorkspace.noMatchingContents": "No matching contents",
  "mobile.AssetContainedWorkspace.tryAnotherNameOrPath": "Try another name or path.",
  "mobile.AssetContainedWorkspace.addToContents": "Add to contents",
  "mobile.AssetContainedWorkspace.add": "Add",
  "mobile.AssetContainedWorkspace.clearSearch": "Clear search",
  "mobile.AssetDetailActions.edit": "Edit",
  "mobile.AssetDetailActions.addPhotos": "Add photos",
  "mobile.AssetDetailActions.assetActions": "Asset actions",
  "mobile.AssetDetailIdentitySection.location": "Location",
  "mobile.AssetDetailIdentitySection.return": "Return",
  "mobile.AssetDetailIdentitySection.availability": "Availability",
  "mobile.AssetDetailPhotoGallery.addPhotos": "Add photos",
  "mobile.AssetDetailPhotoGallery.previewUnavailable": "Preview unavailable",
  "mobile.AssetDetailPhotoGallery.openPhoto": "Open photo",
  "mobile.AssetDetailPresentation.locationLoading": "Location loading",
  "mobile.AssetDetailPresentation.locationNoLocation": "Location No location",
  "mobile.AssetDetailPresentation.return": "Return",
  "mobile.AssetDetailPresentation.checkOut": "Check out",
  "mobile.AssetDetailPresentation.edit": "Edit",
  "mobile.AssetDetailPresentation.move": "Move",
  "mobile.AssetDetailPresentation.addPhotos": "Add photos",
  "mobile.AssetDetailPresentation.lifecycle": "Lifecycle",
  "mobile.AssetDetailPresentation.location": "Location",
  "mobile.AssetDetailView.back": "Back",
  "mobile.AssetDetailView.loadingPhotos": "Loading photos",
  "mobile.AssetDetailView.loadingLocationAndContents": "Loading location and contents",
  "mobile.AssetDetailView.retry": "Retry",
  "mobile.AssetDetailView.photoUploads": "Photo uploads",
  "mobile.AssetExpirationEditor.loadingExpirationSettings": "Loading expiration settings…",
  "mobile.AssetExpirationEditor.itemType": "Item type",
  "mobile.AssetExpirationEditor.searchItemTypes": "Search item types",
  "mobile.AssetExpirationEditor.searchTypes": "Search types",
  "mobile.AssetExpirationEditor.noMatchingItemTypes": "No matching item types.",
  "mobile.AssetExpirationEditor.tracksExpirationDates": "Tracks expiration dates",
  "mobile.AssetExpirationEditor.expiration": "Expiration: ",
  "mobile.AssetExpirationEditor.trackingIsDisabledForThisType": ". Tracking is disabled for this type.",
  "mobile.AssetExpirationEditor.clearExpiration": "Clear expiration",
  "mobile.AssetTagChips.assetTags": "Asset tags",
  "mobile.AssetTagSelectionField.tags": "Tags",
  "mobile.AssetTagSelectionField.chooseTags": "Choose tags",
  "mobile.BrandMark.stuffStash": "Stuff Stash",
  "mobile.ContainedAssetsPresentation.addItemHere": "Add item here",
  "mobile.ContainedAssetsPresentation.moveItemsHere": "Move items here",
  "mobile.ContainedAssetsPresentation.nothingInsideYet": "Nothing inside yet",
  "mobile.ContainedAssetsPresentation.contents": "Contents",
  "mobile.ContainedAssetsPresentation.noSpacesHereYet": "No spaces here yet",
  "mobile.ContainedAssetsPresentation.containersAndNestedPlacesWillAppearHere": "Containers and nested places will appear here.",
  "mobile.ContainedAssetsPresentation.nothingHereYet": "Nothing here yet",
  "mobile.CustomizationEditorFields.type": "Type",
  "mobile.CustomizationEditorFields.options": "Options",
  "mobile.CustomizationEditorFields.addAtLeastOneOption": "Add at least one option.",
  "mobile.CustomizationEditorFields.newEnumOption": "New enum option",
  "mobile.CustomizationEditorFields.addOption": "Add option",
  "mobile.CustomizationEditorFields.addOrClearThisOptionBeforeSaving": "Add or clear this option before saving.",
  "mobile.CustomizationEditorFields.appliesTo": "Applies to",
  "mobile.CustomizationEditorFields.allAssets": "All assets",
  "mobile.CustomizationEditorFields.selectedAssetTypes": "Selected asset types",
  "mobile.CustomizationEditorFields.assetTypes": "Asset types",
  "mobile.CustomizationEditorFields.unavailableSelections": "Unavailable selections",
  "mobile.CustomizationEditorFields.includeUnavailableDraftSelections": "Include unavailable draft selections",
  "mobile.CustomizationEditorFields.chooseAtLeastOneAssetType": "Choose at least one asset type.",
  "mobile.CustomizationEditorFields.noActiveAssetTypesAreAvailable": "No active asset types are available.",
  "mobile.CustomizationEditorFields.required": "Required",
  "mobile.CustomizationEditorFields.name": "Name",
  "mobile.CustomizationLifecycleSection.deletePermanently": "Delete permanently",
  "mobile.ExpirationField.expiration": "Expiration",
  "mobile.ExpirationField.exactDate": "Exact date",
  "mobile.ExpirationField.monthAndYear": "Month and year",
  "mobile.ExpirationField.month": "Month",
  "mobile.ExpirationField.expirationMonth": "Expiration month",
  "mobile.ExpirationField.year": "Year",
  "mobile.ExpirationField.expirationYear": "Expiration year",
  "mobile.ExpirationField.yYYY": "YYYY",
  "mobile.ExpirationField.expirationDate": "Expiration date",
  "mobile.ExpirationField.addExpirationDate": "Add expiration date",
  "mobile.ExpirationField.chooseExpirationDate": "Choose expiration date",
  "mobile.ExpirationField.trackedThroughTheEndOfThisDay": "Tracked through the end of this day.",
  "mobile.ExpirationField.clearExpiration": "Clear expiration",
  "mobile.ExpirationReminderEditor.reminders": "Reminders",
  "mobile.ExpirationReminderEditor.chooseReminderMode": "Choose reminder mode",
  "mobile.ExpirationReminderEditor.useDefaults": "Use defaults",
  "mobile.ExpirationReminderEditor.custom": "Custom",
  "mobile.ExpirationReminderEditor.off": "Off",
  "mobile.ExpirationReminderEditor.inventoryDefaults": "Inventory defaults",
  "mobile.ExpirationReminderEditor.defaultReminders": "Default reminders",
  "mobile.ExpirationReminderEditor.beforeExpiration": "Before expiration",
  "mobile.ExpirationReminderEditor.whenExpired": "When expired",
  "mobile.ExpirationReminderEditor.savingReminders": "Saving reminders…",
  "mobile.ExpirationReminderEditor.retrySavingReminders": "Retry saving reminders",
  "mobile.ExpirationReminderEditor.retry": "Retry",
  "mobile.ExpirationReminderEditor.discardReminderChanges": "Discard reminder changes",
  "mobile.ExpirationReminderEditor.discardChange": "Discard change",
  "mobile.FilterLoadingScreen.loadingFilters": "Loading filters",
  "mobile.FilterLoadingScreen.cancel": "Cancel",
  "mobile.FullScreenPhotoViewer.photoUnavailable": "Photo unavailable",
  "mobile.FullScreenPhotoViewer.retryPhoto": "Retry photo",
  "mobile.FullScreenPhotoViewer.removePhoto": "Remove photo",
  "mobile.FullScreenPhotoViewer.swipeUpOrDownToChangePhotos": "Swipe up or down to change photos",
  "mobile.FullScreenPhotoViewer.nextPhoto": "Next photo",
  "mobile.FullScreenPhotoViewer.previousPhoto": "Previous photo",
  "mobile.FullScreenPhotoViewer.removingPhoto": "Removing photo…",
  "mobile.FullScreenPhotoViewer.photoOptions": "Photo options",
  "mobile.FullSpectrumTagColorPicker.hue": "Hue",
  "mobile.FullSpectrumTagColorPicker.saturation": "Saturation",
  "mobile.FullSpectrumTagColorPicker.brightness": "Brightness",
  "mobile.FullSpectrumTagColorPickerPresentation.increaseSaturation": "Increase saturation",
  "mobile.FullSpectrumTagColorPickerPresentation.decreaseSaturation": "Decrease saturation",
  "mobile.FullSpectrumTagColorPickerPresentation.increaseBrightness": "Increase brightness",
  "mobile.FullSpectrumTagColorPickerPresentation.decreaseBrightness": "Decrease brightness",
  "mobile.FullSpectrumTagColorPickerPresentation.saturationAndBrightness": "Saturation and brightness",
  "mobile.FullSpectrumTagColorPickerPresentation.increaseHue": "Increase hue",
  "mobile.FullSpectrumTagColorPickerPresentation.decreaseHue": "Decrease hue",
  "mobile.FullSpectrumTagColorPickerPresentation.hue": "Hue",
  "mobile.NativeChoiceOptions.choose": "Choose",
  "mobile.NativeTagColorPickerios.fullColorPicker": "Full color picker",
  "mobile.NativeTagColorPickerios.chooseAnyColor": "Choose any color",
  "mobile.PhotoViewerActionButtontypes.closePhotoViewer": "Close photo viewer",
  "mobile.PhotoViewerActionButtontypes.previousPhoto": "Previous photo",
  "mobile.PhotoViewerActionButtontypes.nextPhoto": "Next photo",
  "mobile.PhotoViewerActionButtontypes.removePhoto": "Remove photo",
  "mobile.ReminderTimingEditor.saveReminderDays": "Save reminder days",
  "mobile.ReminderTimingEditor.beforeExpiration": "Before expiration",
  "mobile.ReminderTimingEditor.off": "Off",
  "mobile.ReminderTimingEditor.custom": "Custom…",
  "mobile.ReminderTimingEditor.customDays": "Custom days",
  "mobile.ReminderTimingEditor.daysBefore": "Days before",
  "mobile.ReminderTimingEditor.daysBeforeExpiration": "Days before expiration",
  "mobile.ReminderTimingEditor.enterAWholeNumberFrom0To3650": "Enter a whole number from 0 to 3650.",
  "mobile.ReminderTimingEditor.savingTiming": "Saving timing…",
  "mobile.TagColorPicker.tagColorChoices": "Tag color choices",
  "mobile.TagColorPicker.noTagColor": "No tag color",
  "mobile.TagColorPicker.chooseACustomTagColor": "Choose a custom tag color",
  "mobile.TagColorPicker.custom": "Custom…",
  "mobile.TagColorPicker.customColor": "Custom color",
  "mobile.TagColorPicker.hexColor": "Hex color",
  "mobile.TagColorPicker.customTagColorHexValue": "Custom tag color hex value",
  "mobile.TagColorPicker.2F80ED": "#2F80ED",
  "mobile.TagColorPicker.enterARRGGBBColor": "Enter a #RRGGBB color.",
  "mobile.TagColorPicker.clearColor": "Clear color",
  "mobile.TagColorPicker.cancel": "Cancel",
  "mobile.TagColorPicker.done": "Done",
  "mobile.TimeZonePicker.searchCityOrTimeZone": "Search city or time zone",
  "mobile.TimeZonePicker.datesEndAtMidnightInThisTimeZoneIt": "Dates end at midnight in this time zone. It stays the same when you travel.",
  "mobile.TimeZonePicker.noMatchingTimeZones": "No matching time zones.",
  "mobile.ExpirationDateRange.date": "Date",
  "mobile.ExpirationDateRange.clearDateRange": "Clear date range",
  "mobile.ExpirationFilterHeaderios.filters": "Filters",
  "mobile.ExpirationFilterHeader.filters": "Filters",
  "mobile.ExpirationFiltersScreen.kind": "Kind",
  "mobile.ExpirationFiltersScreen.chooseItemKind": "Choose item kind",
  "mobile.ExpirationFiltersScreen.anyKind": "Any kind",
  "mobile.ExpirationFiltersScreen.items": "Items",
  "mobile.ExpirationFiltersScreen.containers": "Containers",
  "mobile.ExpirationFiltersScreen.places": "Places",
  "mobile.ExpirationFiltersScreen.availability": "Availability",
  "mobile.ExpirationFiltersScreen.chooseAvailability": "Choose availability",
  "mobile.ExpirationFiltersScreen.anyAvailability": "Any availability",
  "mobile.ExpirationFiltersScreen.available": "Available",
  "mobile.ExpirationFiltersScreen.checkedOut": "Checked out",
  "mobile.ExpirationFiltersScreen.chooseType": "Choose type",
  "mobile.ExpirationFiltersScreen.type": "Type",
  "mobile.ExpirationFiltersScreen.chooseTags": "Choose tags",
  "mobile.ExpirationFiltersScreen.tags": "Tags",
  "mobile.ExpirationFiltersScreen.chooseLocation": "Choose location",
  "mobile.ExpirationFiltersScreen.location": "Location",
  "mobile.ExpirationFiltersScreen.chooseDateRange": "Choose date range",
  "mobile.ExpirationFiltersScreen.dateRange": "Date range",
  "mobile.ExpirationFiltersScreen.clearFilters": "Clear filters",
  "mobile.ExpirationFiltersScreen.clearExpirationFilters": "Clear expiration filters",
  "mobile.ExpirationFiltersScreen.any": "Any",
  "mobile.ExpirationFiltersScreen.noMatches": "No matches",
  "mobile.ExpirationFiltersScreen.theEndDateMustBeOnOrAfterThe": "The end date must be on or after the start date.",
  "mobile.ExpirationHomeSection.expiration": "Expiration",
  "mobile.ExpirationHomeSection.viewAllExpirationDates": "View all expiration dates",
  "mobile.ExpirationHomeSection.seeAll": "See all",
  "mobile.ExpirationHomeSection.retryExpiration": "Retry expiration",
  "mobile.ExpirationHomeSection.loadingExpiration": "Loading expiration",
  "mobile.ExpirationHomeSection.noneExpiringSoon": "None expiring soon",
  "mobile.ExpirationHomeSection.expired": "Expired",
  "mobile.ExpirationHomeSection.expiringSoon": "Expiring soon",
  "mobile.ExpirationRouteScreen.returnToHome": "Return to Home",
  "mobile.ExpirationRouteScreen.expiration": "Expiration",
  "mobile.ExpirationWorkspaceScreen.expirationStatus": "Expiration status",
  "mobile.ExpirationWorkspaceScreen.expiringSoon": "Expiring soon",
  "mobile.ExpirationWorkspaceScreen.expired": "Expired",
  "mobile.ExpirationWorkspaceScreen.allDates": "All dates",
  "mobile.ExpirationWorkspaceScreen.searchItems": "Search items",
  "mobile.ExpirationWorkspaceScreen.loadingExpirationDates": "Loading expiration dates",
  "mobile.ExpirationWorkspaceScreen.loadingMoreExpirationDates": "Loading more expiration dates",
  "mobile.AppServicesContext.loadingStuffStash": "Loading Stuff Stash",
  "mobile.AppServicesFeedbackGate.sessionExpired": "Session expired",
  "mobile.AppServicesFeedbackGate.pleaseSignInAgainToContinueUsingStuffStash": "Please sign in again to continue using Stuff Stash.",
  "mobile.AppServicesFeedbackGate.continue": "Continue",
  "mobile.InventorySharingGuard.checkingSharingAccess": "Checking Sharing access",
  "mobile.PrimaryTabStack.expiration": "Expiration",
  "mobile.PrimaryTabStack.settings": "Settings",
  "mobile.PrimaryTabStack.account": "Account",
  "mobile.PrimaryTabStack.appearance": "Appearance",
  "mobile.PrimaryTabStack.sharing": "Sharing",
  "mobile.PrimaryTabStack.stuffStashServer": "Stuff Stash Server",
  "mobile.PrimaryTabStack.about": "About",
  "mobile.PrimaryTabStack.diagnostics": "Diagnostics",
  "mobile.PrimaryTabStack.notifications": "Notifications",
  "mobile.PrimaryTabStack.reminders": "Reminders",
  "mobile.PrimaryTabStack.inventorySettings": "Inventory Settings",
  "mobile.PrimaryTabStack.householdSettings": "Household Settings",
  "mobile.PrimaryTabStack.tags": "Tags",
  "mobile.PrimaryTabStack.addTag": "Add Tag",
  "mobile.PrimaryTabStack.tag": "Tag",
  "mobile.PrimaryTabStack.customFields": "Custom Fields",
  "mobile.PrimaryTabStack.addField": "Add Field",
  "mobile.PrimaryTabStack.customField": "Custom Field",
  "mobile.PrimaryTabStack.assetTypes": "Asset Types",
  "mobile.PrimaryTabStack.addAssetType": "Add Asset Type",
  "mobile.PrimaryTabStack.assetType": "Asset Type",
  "mobile.PrimaryTabStack.voiceSetup": "Voice Setup",
  "mobile.PrimaryTabStack.voiceStage": "Voice Stage",
  "mobile.PrimaryTabStack.providerProfiles": "Provider Profiles",
  "mobile.PrimaryTabStack.addProfile": "Add Profile",
  "mobile.PrimaryTabStack.providerProfile": "Provider Profile",
  "mobile.PrimaryTabStack.credential": "Credential",
  "mobile.PrimaryTabStack.promptGuidance": "Prompt Guidance",
  "mobile.PrimaryTabStack.history": "History",
  "mobile.PrimaryTabStack.historyDetail": "History detail",
  "mobile.PushNotificationNavigation.notificationUnavailable": "Notification unavailable",
  "mobile.PushNotificationNavigation.oK": "OK",
  "mobile.VoiceAdminGuard.voiceSettingsUnavailable": "Voice settings unavailable",
  "mobile.VoiceAdminGuard.couldNotVerifyVoiceSettingsAccess": "Could not verify Voice settings access",
  "mobile.VoiceAdminGuard.checkingVoiceSettingsAccess": "Checking Voice settings access",
  "mobile.VoiceConversationReturn.returnToConversation": "Return to conversation",
  "mobile.VoiceInteractionStateContext.addingPhotos": "Adding photos…",
  "mobile.VoiceInteractionStateContext.photosCouldNotBeAttachedTryAgain": "Photos could not be attached. Try again.",
  "mobile.VoiceSessionPresentation.openVoiceStatus": "Open voice status",
  "mobile.VoiceSessionPresentation.voiceLoading": "Voice loading",
  "mobile.VoiceSessionPresentation.openVoiceError": "Open voice error",
  "mobile.VoiceSessionPresentation.voiceUnavailable": "Voice unavailable",
  "mobile.VoiceSessionPresentation.sendVoiceRequest": "Send voice request",
  "mobile.VoiceSessionPresentation.listening": "Listening",
  "mobile.VoiceSessionPresentation.openVoiceSession": "Open voice session",
  "mobile.VoiceSessionPresentation.openVoiceResponse": "Open voice response",
  "mobile.VoiceSessionPresentation.speaking": "Speaking",
  "mobile.VoiceSessionPresentation.openVoiceFollowUp": "Open voice follow-up",
  "mobile.VoiceSessionPresentation.openCancelledVoiceSession": "Open cancelled voice session",
  "mobile.VoiceSessionPresentation.voiceCancelled": "Voice cancelled",
  "mobile.VoiceSessionPresentation.reviewVoicePlan": "Review voice plan",
  "mobile.VoiceSessionPresentation.startVoiceInteraction": "Start voice interaction",
  "mobile.VoiceSessionPresentation.askStuffStash": "Ask Stuff Stash",
  "mobile.VoiceSessionPresentation.voiceProviders": "Voice providers",
  "mobile.VoiceSessionPresentation.openAppliedVoiceChange": "Open applied voice change",
  "mobile.VoiceSessionPresentation.changeApplied": "Change applied",
  "mobile.VoiceSessionPresentation.openCancelledVoiceChange": "Open cancelled voice change",
  "mobile.VoiceSessionPresentation.changeCancelled": "Change cancelled",
  "mobile.VoiceSessionPresentation.openUnsupportedVoiceResult": "Open unsupported voice result",
  "mobile.VoiceSessionPresentation.voiceActionUnavailable": "Voice action unavailable",
  "mobile.VoiceSessionPresentation.openSafeVoiceResult": "Open safe voice result",
  "mobile.VoiceSessionPresentation.couldNotFinishSafely": "Could not finish safely",
  "mobile.VoiceSessionPresentation.openVoiceAnswer": "Open voice answer",
  "mobile.VoiceSessionPresentation.answerReady": "Answer ready",
  "mobile.AddAssetScreen.assetSaved": "Asset saved",
  "mobile.AddAssetScreen.view": "View",
  "mobile.AddAssetScreen.closeAdd": "Close Add",
  "mobile.AddAssetScreen.saveItem": "Save item",
  "mobile.AddAssetScreen.addItem": "Add item",
  "mobile.AddAssetScreen.savingItem": "Saving item",
  "mobile.AddAssetScreen.loadingInventory": "Loading inventory",
  "mobile.AddAssetScreen.couldNotLoad": "Could not load",
  "mobile.AddAssetScreen.retryAddContext": "Retry Add context",
  "mobile.AddAssetScreen.addIsUnavailable": "Add is unavailable",
  "mobile.AddAssetScreen.thisInventoryDoesNotAllowYouToCreateAssets": "This inventory does not allow you to create assets.",
  "mobile.AddAssetScreen.name": "Name",
  "mobile.AddAssetScreen.assetName": "Asset name",
  "mobile.AddAssetScreen.furnaceFilterPassportCampingBin": "Furnace filter, passport, camping bin",
  "mobile.AddAssetScreen.putIn": "Put in",
  "mobile.AddAssetScreen.chooseDestination": "Choose destination",
  "mobile.AddAssetScreen.stuffStashWillTurn": "Stuff Stash will turn ",
  "mobile.AddAssetScreen.intoAContainerForThisItem": " into a container for this item.",
  "mobile.AddAssetScreen.moreDetails": "More details",
  "mobile.AddAssetScreen.assetTypesCouldNotBeLoaded": "Asset types could not be loaded.",
  "mobile.AddAssetScreen.retryAssetTypes": "Retry asset types",
  "mobile.AddAssetScreen.openMoreDetailsToAddOrClearTheUnfinished": "Open More details to add or clear the unfinished tag before saving.",
  "mobile.AddAssetScreen.assetDescription": "Asset description",
  "mobile.AddAssetScreen.description": "Description",
  "mobile.AddAssetScreen.clearDraft": "Clear draft",
  "mobile.AddAssetScreen.photos": "Photos",
  "mobile.AddAssetScreen.addPhotos": "Add photos",
  "mobile.AddAssetScreen.chooseCameraOrPhotoLibrary": "Choose camera or photo library",
  "mobile.AddAssetScreen.previewPhoto": "Preview photo",
  "mobile.AddAssetScreen.moveEarlier": "Move earlier",
  "mobile.AddAssetScreen.moveLater": "Move later",
  "mobile.AddAssetScreen.removePhoto": "Remove photo",
  "mobile.AddAssetScreen.tapToPreviewHoldAndDragToReorder": "Tap to preview. Hold and drag to reorder.",
  "mobile.AddAssetScreen.tags": "Tags",
  "mobile.AddAssetScreen.newTagName": "New tag name",
  "mobile.AddAssetScreen.newTag": "New tag",
  "mobile.AddAssetScreen.useAShorterTagName": "Use a shorter tag name.",
  "mobile.AddAssetScreen.addTag": "Add tag",
  "mobile.AddAssetScreen.addThisTagOrClearItsNameAndColor": "Add this tag or clear its name and color before saving.",
  "mobile.AddAssetScreen.cancelNewTag": "Cancel new tag",
  "mobile.AddDestinationSelectionScreen.createPlace": "Create place",
  "mobile.AddDestinationSelectionScreen.newPlace": "New place",
  "mobile.AddDestinationSelectionScreen.searchParent": "Search parent",
  "mobile.AddDestinationSelectionScreen.loadingSuggestions": "Loading suggestions…",
  "mobile.AddDestinationSelectionScreen.suggestionsCouldNotBeLoaded": "Suggestions could not be loaded.",
  "mobile.AddDestinationSelectionScreen.retrySuggestions": "Retry suggestions",
  "mobile.AddDestinationSelectionScreen.name": "Name",
  "mobile.AddDestinationSelectionScreen.newPlaceName": "New place name",
  "mobile.AddDestinationSelectionScreen.placeName": "Place name",
  "mobile.AddDestinationSelectionScreen.creatingPlace": "Creating place…",
  "mobile.AddDestinationSelectionScreen.topLevel": "Top level",
  "mobile.AddDestinationSelectionScreen.chooseInventoryTopLevel": "Choose inventory top level",
  "mobile.AssetCheckoutHistoryScreen.checkoutHistoryCouldNotBeLoaded": "Checkout history could not be loaded.",
  "mobile.AssetCheckoutHistoryScreen.close": "Close",
  "mobile.AssetCheckoutHistoryScreen.checkoutHistory": "Checkout history",
  "mobile.AssetCheckoutHistoryScreen.assetNameCouldNotBeLoaded": "Asset name could not be loaded.",
  "mobile.AssetCheckoutHistoryScreen.tryAgain": "Try again",
  "mobile.AssetCheckoutHistoryScreen.checkoutHistoryCouldNotBeRefreshedPreviouslyLoadedCheckouts": "Checkout history could not be refreshed. Previously loaded checkouts are shown.",
  "mobile.AssetCheckoutHistoryScreen.tryRefreshingAgain": "Try refreshing again",
  "mobile.AssetCheckoutHistoryScreen.olderCheckoutsCouldNotBeLoaded": "Older checkouts could not be loaded.",
  "mobile.AssetCheckoutHistorySheet.loadingCheckoutHistory": "Loading checkout history",
  "mobile.AssetCheckoutHistorySheet.couldNotLoadCheckoutHistory": "Could not load checkout history",
  "mobile.AssetCheckoutHistorySheet.checkoutDetails": "Checkout details",
  "mobile.AssetCheckoutHistorySheet.returnDetails": "Return details",
  "mobile.AssetDetailMovePresentation.searchForSomethingToMoveHere": "Search for something to move here",
  "mobile.AssetDetailMovePresentation.startTypingToFindAnItemBoxOrPlace": "Start typing to find an item, box, or place from this inventory.",
  "mobile.AssetDetailMovePresentation.noMovableMatches": "No movable matches",
  "mobile.AssetDetailMovePresentation.searchForSomethingThatIsNotAlreadyInsideThis": "Search for something that is not already inside this place.",
  "mobile.AssetDetailRouteErrorState.assetError": "Asset error",
  "mobile.AssetDetailRouteErrorState.retryAsset": "Retry asset",
  "mobile.AssetDetailRouteScreen.theChangeIsNowInHistory": "The change is now in History.",
  "mobile.AssetDetailRouteScreen.undo": "Undo",
  "mobile.AssetDetailRouteScreen.editUndone": "Edit undone",
  "mobile.AssetDetailRouteScreen.thePreviousValuesWereReapplied": "The previous values were reapplied.",
  "mobile.AssetDetailRouteScreen.couldNotUndoEdit": "Could not undo edit",
  "mobile.AssetDetailRouteScreen.couldNotOpenHistory": "Could not open History",
  "mobile.AssetDetailRouteScreen.theItemScopeIsUnavailableRefreshAndTryAgain": "The item scope is unavailable. Refresh and try again.",
  "mobile.AssetDetailRouteScreen.couldNotRefreshAsset": "Could not refresh asset",
  "mobile.AssetDetailRouteScreen.couldNotRemovePhoto": "Could not remove photo",
  "mobile.AssetDetailRouteScreen.oK": "OK",
  "mobile.AssetDetailRouteScreen.theLatestAssetStateCouldNotBeRefreshedYet": "The latest asset state could not be refreshed yet. Pull to refresh.",
  "mobile.AssetDetailRouteScreen.theLatestAvailabilityCouldNotBeRefreshedYetPull": "The latest availability could not be refreshed yet. Pull to refresh.",
  "mobile.AssetDetailRouteScreen.searchThisPlace": "Search this place",
  "mobile.AssetDetailRouteScreen.loadingAsset": "Loading asset",
  "mobile.AssetDetailSheets.cancel": "Cancel",
  "mobile.AssetDetailSheets.save": "Save",
  "mobile.AssetDetailSheets.savingChanges": "Saving changes…",
  "mobile.AssetDetailSheets.name": "Name",
  "mobile.AssetDetailSheets.assetName": "Asset name",
  "mobile.AssetDetailSheets.description": "Description",
  "mobile.AssetDetailSheets.createDestination": "Create destination",
  "mobile.AssetDetailSheets.newDestination": "New destination",
  "mobile.AssetDetailSheets.move": "Move",
  "mobile.AssetDetailSheets.searchPlacesBoxesShelves": "Search places, boxes, shelves",
  "mobile.AssetDetailSheets.destinations": "Destinations",
  "mobile.AssetDetailSheets.inventoryRoot": "Inventory root",
  "mobile.AssetDetailSheets.chooseInventoryRoot": "Choose inventory root",
  "mobile.AssetDetailSheets.newDestinationName": "New destination name",
  "mobile.AssetDetailSheets.placeOrContainerName": "Place or container name",
  "mobile.AssetDetailSheets.kind": "Kind",
  "mobile.AssetDetailSheets.location": "Location",
  "mobile.AssetDetailSheets.container": "Container",
  "mobile.AssetDetailSheets.creatingDestination": "Creating destination…",
  "mobile.AssetDetailSheets.moveHere": "Move here",
  "mobile.AssetDetailSheets.searchYourInventory": "Search your inventory",
  "mobile.AssetDetailSheets.items": "Items",
  "mobile.AssetDetailSheets.thisItemCannotBeChangedHereYourDraftIs": "This item cannot be changed here. Your draft is kept while this screen is open.",
  "mobile.AssetDetailSheets.moving": "Moving…",
  "mobile.AssetHeaderOverflowios.edit": "Edit",
  "mobile.AssetHeaderOverflow.edit": "Edit",
  "mobile.AssetHistoryDetailRouteScreen.historyDetail": "History detail",
  "mobile.AssetHistoryDetailRouteScreen.loadingActivity": "Loading activity…",
  "mobile.AssetHistoryDetailRouteScreen.tryAgain": "Try again",
  "mobile.AssetHistoryDetailRouteScreen.activityIsNoLongerAvailable": "Activity is no longer available",
  "mobile.AssetHistoryDetailRouteScreen.returnToHistoryAndOpenItAgain": "Return to History and open it again.",
  "mobile.AssetHistoryDetailRouteScreen.backToHistory": "Back to History",
  "mobile.AssetHistoryDetailRouteScreen.changeReverted": "Change reverted",
  "mobile.AssetHistoryDetailRouteScreen.activityCouldNotBeRefreshedPreviouslyLoadedDetailsAre": "Activity could not be refreshed. Previously loaded details are shown.",
  "mobile.AssetHistoryDetailRouteScreen.tryRefreshingAgain": "Try refreshing again",
  "mobile.AssetHistoryDetailRouteScreen.whatChanged": "What changed",
  "mobile.AssetHistoryDetailRouteScreen.before": "Before",
  "mobile.AssetHistoryDetailRouteScreen.after": "After",
  "mobile.AssetHistoryDetailRouteScreen.changed": "Changed",
  "mobile.AssetHistoryDetailRouteScreen.thisChangeCanNoLongerBeSafelyReverted": "This change can no longer be safely reverted.",
  "mobile.AssetHistoryDetailRouteScreen.thisChangeHasBeenReverted": "This change has been reverted.",
  "mobile.AssetHistoryDetailRouteScreen.technicalDetails": "Technical details",
  "mobile.AssetHistoryPresentation.historyUnavailable": "History unavailable",
  "mobile.AssetHistoryPresentation.youDoNotHaveAccessToThisItemS": "You do not have access to this item’s History.",
  "mobile.AssetHistoryPresentation.thisItemIsUnavailableOrYouNoLongerHave": "This item is unavailable or you no longer have access.",
  "mobile.AssetHistoryPresentation.couldNotLoadHistory": "Could not load History",
  "mobile.AssetHistoryPresentation.historyCouldNotBeLoadedTryAgain": "History could not be loaded. Try again.",
  "mobile.AssetHistoryPresentation.revertThisChange": "Revert this change?",
  "mobile.AssetHistoryPresentation.revertChange": "Revert Change",
  "mobile.AssetHistoryPresentation.revertUnavailable": "Revert unavailable",
  "mobile.AssetHistoryPresentation.youNoLongerHavePermissionToRevertThisChange": "You no longer have permission to revert this change.",
  "mobile.AssetHistoryPresentation.changeCanTBeReverted": "Change can’t be reverted",
  "mobile.AssetHistoryPresentation.thisChangeIsNoLongerAvailable": "This change is no longer available.",
  "mobile.AssetHistoryPresentation.thisItemChangedAfterwardSoThisChangeCanT": "This item changed afterward, so this change can’t be safely reverted.",
  "mobile.AssetHistoryPresentation.couldNotRevertChange": "Could not revert change",
  "mobile.AssetHistoryPresentation.theChangeCouldNotBeRevertedTryAgain": "The change could not be reverted. Try again.",
  "mobile.AssetHistoryPresentation.auditRecord": "Audit record",
  "mobile.AssetHistoryPresentation.action": "Action",
  "mobile.AssetHistoryPresentation.source": "Source",
  "mobile.AssetHistoryPresentation.request": "Request",
  "mobile.AssetHistoryRouteScreen.history": "History",
  "mobile.AssetHistoryRouteScreen.loadingHistory": "Loading history",
  "mobile.AssetHistoryRouteScreen.tryAgain": "Try again",
  "mobile.AssetHistoryRouteScreen.historyCouldNotBeRefreshedPreviouslyLoadedActivityIs": "History could not be refreshed. Previously loaded activity is shown.",
  "mobile.AssetHistoryRouteScreen.tryRefreshingAgain": "Try refreshing again",
  "mobile.AssetHistoryRouteScreen.show": "Show",
  "mobile.AssetHistoryRouteScreen.changes": "Changes",
  "mobile.AssetHistoryRouteScreen.allEvents": "All events",
  "mobile.AssetHistoryRouteScreen.showsExactTimeAndTechnicalDetails": "Shows exact time and technical details",
  "mobile.AssetLifecyclePresentation.assetUnavailable": "Asset unavailable",
  "mobile.AssetLifecyclePresentation.thisAssetIsNotAvailableInYourCurrentInventory": "This asset is not available in your current inventory.",
  "mobile.AssetLifecyclePresentation.couldNotLoadAsset": "Could not load asset",
  "mobile.AssetLifecyclePresentation.checkYourConnectionAndTryAgain": "Check your connection and try again.",
  "mobile.AssetLifecyclePresentation.archive": "Archive",
  "mobile.AssetLifecyclePresentation.restore": "Restore",
  "mobile.AssetLifecyclePresentation.deletePermanently": "Delete permanently",
  "mobile.AssetLifecyclePresentation.checkoutHistory": "Checkout history",
  "mobile.AssetLifecyclePresentation.history": "History",
  "mobile.AssetNativeActionSheetScreens.retryPlacement": "Retry placement",
  "mobile.AssetNativeActionSheetScreens.couldNotLoadAsset": "Could not load asset.",
  "mobile.AssetNativeActionSheetScreens.loadingAsset": "Loading asset",
  "mobile.AssetNativeActionSheetScreens.close": "Close",
  "mobile.AssetNativeActionSheetScreens.editAsset": "Edit asset",
  "mobile.AssetNativeActionSheetScreens.assetTypesCouldNotBeLoaded": "Asset types could not be loaded.",
  "mobile.AssetNativeActionSheetScreens.tagsCouldNotBeLoaded": "Tags could not be loaded.",
  "mobile.AssetNativeActionSheetScreens.moveSomethingHere": "Move something here",
  "mobile.AssetNativeActionSheetScreens.couldNotLoad": "Could not load",
  "mobile.AssetNativeActionSheetScreens.retryAsset": "Retry asset",
  "mobile.AssetNativeActionSheetScreens.suggestionsCouldNotBeLoaded": "Suggestions could not be loaded.",
  "mobile.AssetNativeActionSheetScreens.retrySuggestions": "Retry suggestions",
  "mobile.AssetNativeActionSheetScreens.loadingSuggestions": "Loading suggestions…",
  "mobile.AssetNativeSheetOptions.addItem": "Add item",
  "mobile.AssetNativeSheetOptions.filters": "Filters",
  "mobile.AssetNativeSheetOptions.editAsset": "Edit asset",
  "mobile.AssetNativeSheetOptions.moveAsset": "Move asset",
  "mobile.AssetNativeSheetOptions.moveSomethingHere": "Move something here",
  "mobile.AssetNativeSheetOptions.checkoutHistory": "Checkout history",
  "mobile.AssetOverflowMenu.addPhotos": "Add photos",
  "mobile.AssetOverflowMenu.move": "Move",
  "mobile.AssetOverflowMenu.checkOut": "Check out",
  "mobile.AssetTagSelectionScreen.tags": "Tags",
  "mobile.AssetTagSelectionScreen.searchTags": "Search tags",
  "mobile.AssetTagSelectionScreen.allTags": "All tags",
  "mobile.AssetTagSelectionScreen.selected": "Selected",
  "mobile.AssetTagSelectionScreen.selected2": " selected",
  "mobile.AssetTagSelectionScreen.newTag": "New tag",
  "mobile.AssetTagSelectionScreen.tagSelectionIsNoLongerAvailableForThisDraft": "Tag selection is no longer available for this draft.",
  "mobile.AssetTagSelectionScreen.unavailableTag": "Unavailable tag",
  "mobile.AssetWorkspaceStatusPresentation.archivingAsset": "Archiving asset...",
  "mobile.AssetWorkspaceStatusPresentation.deletingAsset": "Deleting asset...",
  "mobile.AssetWorkspaceStatusPresentation.savingChanges": "Saving changes...",
  "mobile.AssetWorkspaceStatusPresentation.movingAsset": "Moving asset...",
  "mobile.AssetWorkspaceStatusPresentation.checkingOutAsset": "Checking out asset...",
  "mobile.AssetWorkspaceStatusPresentation.returningAsset": "Returning asset...",
  "mobile.AssetWorkspaceStatusPresentation.restoringAsset": "Restoring asset...",
  "mobile.BrowseFiltersRouteScreen.filtersAreUnavailableForThisInventory": "Filters are unavailable for this inventory.",
  "mobile.BrowseFiltersRouteScreen.retry": "Retry",
  "mobile.BrowseFiltersRouteScreen.cancel": "Cancel",
  "mobile.BrowseFiltersScreen.allTypes": "All types",
  "mobile.BrowseFiltersScreen.places": "Places",
  "mobile.BrowseFiltersScreen.containers": "Containers",
  "mobile.BrowseFiltersScreen.items": "Items",
  "mobile.BrowseFiltersScreen.active": "Active",
  "mobile.BrowseFiltersScreen.archived": "Archived",
  "mobile.BrowseFiltersScreen.allStatuses": "All statuses",
  "mobile.BrowseFiltersScreen.anyAvailability": "Any availability",
  "mobile.BrowseFiltersScreen.available": "Available",
  "mobile.BrowseFiltersScreen.checkedOut": "Checked out",
  "mobile.BrowseFiltersScreen.recentlyChanged": "Recently changed",
  "mobile.BrowseFiltersScreen.defaultOrder": "Default order",
  "mobile.BrowseFiltersScreen.searchTags": "Search tags",
  "mobile.BrowseFiltersScreen.type": "Type",
  "mobile.BrowseFiltersScreen.chooseType": "Choose type",
  "mobile.BrowseFiltersScreen.status": "Status",
  "mobile.BrowseFiltersScreen.chooseStatus": "Choose status",
  "mobile.BrowseFiltersScreen.availability": "Availability",
  "mobile.BrowseFiltersScreen.chooseAvailability": "Choose availability",
  "mobile.BrowseFiltersScreen.tags": "Tags",
  "mobile.BrowseFiltersScreen.chooseTags": "Choose tags",
  "mobile.BrowseFiltersScreen.sort": "Sort",
  "mobile.BrowseFiltersScreen.chooseSort": "Choose sort",
  "mobile.BrowseFiltersScreen.chooseExpirationReview": "Choose expiration review",
  "mobile.BrowseFiltersScreen.reviewExpiration": "Review expiration",
  "mobile.BrowseFiltersScreen.expiringSoon": "Expiring soon",
  "mobile.BrowseFiltersScreen.expired": "Expired",
  "mobile.BrowseFiltersScreen.allDates": "All dates",
  "mobile.BrowseFiltersScreen.resetAll": "Reset all",
  "mobile.BrowseFiltersScreen.resetAllFilters": "Reset all filters",
  "mobile.BrowseHeader.searchingInventory": "Searching inventory",
  "mobile.BrowseHeader.appliedFilters": "Applied filters",
  "mobile.BrowseHeader.clearAll": "Clear all",
  "mobile.BrowseHeader.retry": "Retry",
  "mobile.BrowsePlaceRow.place": "Place",
  "mobile.BrowseResultStates.couldNotLoadThisInventory": "Could not load this inventory",
  "mobile.BrowseResultStates.retry": "Retry",
  "mobile.BrowseResultStates.tryAgain": "Try again",
  "mobile.BrowseResultStates.tryAnotherSearchOrClearItToBrowseEverything": "Try another search or clear it to browse everything.",
  "mobile.BrowseResultStates.noItemsMatchTheseFilters": "No items match these filters",
  "mobile.BrowseResultStates.removeAFilterToSeeMoreOfYourInventory": "Remove a filter to see more of your inventory.",
  "mobile.BrowseSurfaceControl.browseView": "Browse view",
  "mobile.CustomizationCollectionScreen.couldNotRefreshSettings": "Could not refresh settings",
  "mobile.CustomizationCollectionScreen.previouslyLoadedSettingsAreStillShownRefreshToRetry": "Previously loaded settings are still shown. Refresh to retry.",
  "mobile.CustomizationCollectionScreen.someSettingsCouldNotBeLoaded": "Some settings could not be loaded",
  "mobile.CustomizationCollectionScreen.refreshToTryLoadingTheCompleteList": "Refresh to try loading the complete list.",
  "mobile.CustomizationCollectionScreen.youDonTHavePermissionToViewTheseSettings": "You don’t have permission to view these settings.",
  "mobile.CustomizationCollectionScreen.loadingSettings": "Loading settings…",
  "mobile.CustomizationCollectionScreen.couldNotLoad": "Could not load ",
  "mobile.CustomizationCollectionScreen.yourSettingsWereNotChanged": "Your settings were not changed.",
  "mobile.CustomizationCollectionScreen.retry": "Retry",
  "mobile.CustomizationCollectionScreen.active": "Active",
  "mobile.CustomizationCollectionScreen.archived": "Archived",
  "mobile.CustomizationCollectionScreen.someSettingsMayBeMissing": "Some settings may be missing",
  "mobile.CustomizationCollectionScreen.pullToRefreshAndTryLoadingTheCompleteList": "Pull to refresh and try loading the complete list.",
  "mobile.CustomizationCollectionScreen.noMatches": "No matches",
  "mobile.CustomizationEditorScreen.backToSettingsCollection": "Back to settings collection",
  "mobile.CustomizationEditorScreen.loadingSetting": "Loading setting…",
  "mobile.CustomizationEditorScreen.settingUnavailable": "Setting unavailable",
  "mobile.CustomizationEditorScreen.itMayHaveBeenArchivedDeletedOrYouMay": "It may have been archived, deleted, or you may no longer have access.",
  "mobile.CustomizationEditorScreen.retry": "Retry",
  "mobile.CustomizationEditorScreen.youDonTHavePermissionToAddThisSetting": "You don’t have permission to add this setting.",
  "mobile.CustomizationEditorScreen.returnToCollection": "Return to collection",
  "mobile.CustomizationEditorScreen.accessChanged": "Access changed",
  "mobile.CustomizationEditorScreen.yourChangeWasNotSavedYourDraftIsShown": "Your change was not saved. Your draft is shown below and is read-only.",
  "mobile.CustomizationEditorScreen.askAHouseholdManagerToRestoreYourAccessThen": "Ask a household manager to restore your access, then refresh access.",
  "mobile.CustomizationEditorScreen.refreshAccess": "Refresh access",
  "mobile.CustomizationEditorScreen.name": "Name",
  "mobile.CustomizationEditorScreen.color": "Color",
  "mobile.CustomizationEditorScreen.enterASixDigitHexColorSuchAs2F80ED": "Enter a six-digit hex color such as #2F80ED.",
  "mobile.CustomizationEditorScreen.trackExpirationDates": "Track expiration dates",
  "mobile.CustomizationEditorScreen.eachAssetCanHaveItsOwnOptionalDateTurning": "Each asset can have its own optional date. Turning this off keeps existing dates.",
  "mobile.CustomizationEditorScreen.description": "Description",
  "mobile.CustomizationEditorScreen.details": "Details",
  "mobile.CustomizationEditorScreen.stableKey": "Stable key",
  "mobile.CustomizationEditorScreen.key": "Key",
  "mobile.CustomizationEditorScreen.scope": "Scope",
  "mobile.CustomizationEditorScreen.unsavedChanges": "Unsaved changes",
  "mobile.CustomizationEditorScreen.accessIsStillUnavailable": "Access is still unavailable",
  "mobile.CustomizationEditorScreen.yourDraftRemainsReadOnly": "Your draft remains read-only.",
  "mobile.CustomizationEditorScreen.couldNotRefreshAccess": "Could not refresh access",
  "mobile.CustomizationEditorScreen.yourDraftRemainsReadOnlyTryAgain": "Your draft remains read-only. Try again.",
  "mobile.HomeNavigationHeader.addAnAsset": "Add an asset",
  "mobile.HomeNavigationHeader.openAccountAndSettings": "Open account and settings",
  "mobile.HomeReturnDetailsRouteScreen.returnDetails": "Return details",
  "mobile.HomeReturnDetailsSheet.yourAccessChangedTheItemIsAlreadyReturnedYou": "Your access changed. The item is already returned. You can close this sheet, but cannot save details or cancel the return.",
  "mobile.HomeReturnDetailsSheet.thisReturnCannotBeCanceled": "This return cannot be canceled.",
  "mobile.HomeReturnDetailsSheet.optionalReturnDetails": "Optional return details",
  "mobile.HomeReturnDetailsSheet.returnDetailsError": "Return details error",
  "mobile.HomeScreen.couldNotRefreshHome": "Could not refresh Home",
  "mobile.HomeScreen.loadingStuffStash": "Loading Stuff Stash",
  "mobile.HomeScreen.couldNotLoad": "Could not load",
  "mobile.HomeScreen.retryLoadingHome": "Retry loading Home",
  "mobile.HomeScreen.recentlyChanged": "Recently changed",
  "mobile.HomeScreen.viewAllRecentlyChangedAssets": "View all recently changed assets",
  "mobile.HomeScreen.seeAll": "See all",
  "mobile.HomeScreen.noAssetsYet": "No assets yet.",
  "mobile.HomeScreen.checkedOut": "Checked out",
  "mobile.HomeScreen.viewAllCheckedOutAssets": "View all checked-out assets",
  "mobile.HomeScreen.viewAll": "View all",
  "mobile.InventoryAssetsRouteScreen.assets": "Assets",
  "mobile.InventoryAssetsRouteScreen.recentlyChanged": "Recently changed",
  "mobile.InventoryAssetsRouteScreen.noAssetsYet": "No assets yet.",
  "mobile.InventoryAssetsRouteScreen.loadingAssets": "Loading assets",
  "mobile.InventoryAssetsRouteScreen.couldNotLoad": "Could not load",
  "mobile.InventoryAssetsRouteScreen.retry": "Retry",
  "mobile.InventoryExportAction.exportInventory": "Export inventory",
  "mobile.InventoryExportAction.jSONCompleteInventoryData": "JSON — complete inventory data",
  "mobile.InventoryExportAction.cSVSpreadsheetRows": "CSV — spreadsheet rows",
  "mobile.InventoryExportAction.preparingExport": "Preparing export…",
  "mobile.InventoryExportAction.cancelExport": "Cancel export",
  "mobile.InventoryExportAction.retryExport": "Retry export",
  "mobile.InventoryInvitationScreen.invitationNotAvailable": "Invitation not available",
  "mobile.InventoryInvitationScreen.thisInvitationLinkIsIncompleteOrInvalidAskThe": "This invitation link is incomplete or invalid. Ask the sender for a new link.",
  "mobile.InventoryInvitationScreen.checkingInvitation": "Checking invitation",
  "mobile.InventoryInvitationScreen.confirmingThatThisInvitationIsStillAvailable": "Confirming that this invitation is still available…",
  "mobile.InventoryInvitationScreen.youReInvited": "You’re invited",
  "mobile.InventoryInvitationScreen.access": "Access",
  "mobile.InventoryInvitationScreen.expires": "Expires",
  "mobile.InventoryInvitationScreen.joinInventory": "Join inventory",
  "mobile.InventoryInvitationScreen.joining": "Joining…",
  "mobile.InventoryInvitationScreen.signOutAndStartOver": "Sign out and start over",
  "mobile.InventoryInvitationScreen.startingOver": "Starting over…",
  "mobile.InventoryInvitationScreen.notNow": "Not now",
  "mobile.InventoryInvitationScreen.youReIn": "You’re in",
  "mobile.InventoryInvitationScreen.youNowHaveAccessTo": "You now have access to ",
  "mobile.InventoryInvitationScreen.theInventoryCouldNotBeOpenedYourAccessWas": "The inventory could not be opened. Your access was still added.",
  "mobile.InventoryInvitationScreen.openInventory": "Open inventory",
  "mobile.InventoryInvitationScreen.opening": "Opening…",
  "mobile.InventoryInvitationScreen.tryAgain": "Try again",
  "mobile.InventoryInvitationScreen.switchAccount": "Switch account",
  "mobile.InventoryInvitationScreen.done": "Done",
  "mobile.InventoryInvitationScreen.couldNotStartOver": "Could not start over",
  "mobile.InventoryInvitationScreen.tryAgainToSignOut": "Try again to sign out.",
  "mobile.InventoryInvitationScreen.invitationExpired": "Invitation expired",
  "mobile.InventoryInvitationScreen.askTheSenderForANewInvitation": "Ask the sender for a new invitation.",
  "mobile.InventoryInvitationScreen.thisInvitationCanNoLongerBeAccepted": "This invitation can no longer be accepted.",
  "mobile.InventoryInvitationScreen.differentAccountNeeded": "Different account needed",
  "mobile.InventoryInvitationScreen.signInRequired": "Sign in required",
  "mobile.InventoryInvitationScreen.couldNotVerifyInvitation": "Could not verify invitation",
  "mobile.InventoryInvitationScreen.theServerReturnedAnInvalidResponse": "The server returned an invalid response.",
  "mobile.InventoryInvitationScreen.couldNotCheckInvitation": "Could not check invitation",
  "mobile.InventoryInvitationScreen.checkYourConnectionAndTryAgain": "Check your connection and try again.",
  "mobile.InventoryMapPresentation.list": "List",
  "mobile.InventoryMapPresentation.map": "Map",
  "mobile.InventoryMapPresentation.addItemHere": "Add item here",
  "mobile.InventoryMapScreen.inventoryMapCouldNotLoad": "Inventory map could not load.",
  "mobile.InventoryMapScreen.couldNotRefreshMap": "Could not refresh Map",
  "mobile.InventoryMapScreen.yourLastLoadedMapIsStillAvailablePullTo": "Your last loaded map is still available. Pull to refresh.",
  "mobile.InventoryMapScreen.noMatchingItemsTryAnotherNameKindOrLocation": "No matching items. Try another name, kind or location.",
  "mobile.InventoryMapScreen.findAndExpandPath": "Find and expand path",
  "mobile.InventoryMapScreen.loadingMap": "Loading map",
  "mobile.InventoryMapScreen.mapUnavailable": "Map unavailable",
  "mobile.InventoryMapScreen.retryMap": "Retry map",
  "mobile.InventorySharingScreen.invitationCreatedLinkUnavailable": "Invitation created, link unavailable",
  "mobile.InventorySharingScreen.ifTheInvitationIsStillPendingBelowCancelIt": "If the invitation is still pending below, cancel it before retrying. If you already cancelled it, try again.",
  "mobile.InventorySharingScreen.couldNotCreateInvitation": "Could not create invitation",
  "mobile.InventorySharingScreen.invitationLinkCopied": "Invitation link copied",
  "mobile.InventorySharingScreen.share": "Share ",
  "mobile.InventorySharingScreen.inviteSomeoneByEmailAsAViewerOrEditor": "Invite someone by email as a viewer or editor.",
  "mobile.InventorySharingScreen.newInvitation": "New Invitation",
  "mobile.InventorySharingScreen.email": "Email",
  "mobile.InventorySharingScreen.access": "Access",
  "mobile.InventorySharingScreen.chooseInvitationAccess": "Choose invitation access",
  "mobile.InventorySharingScreen.viewer": "Viewer",
  "mobile.InventorySharingScreen.editor": "Editor",
  "mobile.InventorySharingScreen.invitationLink": "Invitation Link",
  "mobile.InventorySharingScreen.invitationReady": "Invitation ready",
  "mobile.InventorySharingScreen.expires": " · Expires ",
  "mobile.InventorySharingScreen.completeInvitationLink": "Complete invitation link",
  "mobile.InventorySharingScreen.invitations": "Invitations",
  "mobile.InventorySharingScreen.noInvitationsYet": "No invitations yet.",
  "mobile.InventorySharingScreen.cancelling": "Cancelling…",
  "mobile.InventorySharingScreen.couldNotCancelInvitation": "Could not cancel invitation",
  "mobile.InventorySharingScreen.cancelInvitation": "Cancel invitation",
  "mobile.InventorySharingScreen.loadingOlderInvitations": "Loading older invitations…",
  "mobile.InventorySharingScreen.loadOlderInvitations": "Load older invitations",
  "mobile.InvitationEmailInputios.friendExampleCom": "friend@example.com",
  "mobile.InvitationEmailInput.inviteeEmail": "Invitee email",
  "mobile.InvitationEmailInput.friendExampleCom": "friend@example.com",
  "mobile.LocationAssetsRouteScreen.noAssetsInThisLocation": "No assets in this location.",
  "mobile.LocationAssetsRouteScreen.loadingLocation": "Loading location",
  "mobile.LocationAssetsRouteScreen.couldNotLoad": "Could not load",
  "mobile.LocationAssetsRouteScreen.retry": "Retry",
  "mobile.LocationsScreen.loadingLocations": "Loading locations",
  "mobile.LocationsScreen.couldNotLoad": "Could not load",
  "mobile.LocationsScreen.retry": "Retry",
  "mobile.LocationsScreen.locations": "Locations",
  "mobile.LocationsScreen.noLocationsYet": "No locations yet.",
  "mobile.LocationsScreen.place": "Place",
  "mobile.NewAssetTagScreen.newTag": "New tag",
  "mobile.NewAssetTagScreen.name": "Name",
  "mobile.NewAssetTagScreen.newTagName": "New tag name",
  "mobile.NewAssetTagScreen.tagName": "Tag name",
  "mobile.NewAssetTagScreen.useAShorterTagName": "Use a shorter tag name.",
  "mobile.NewAssetTagScreen.colorOptional": "Color (optional)",
  "mobile.NotificationInboxScreen.markAllRead": "Mark all read",
  "mobile.NotificationInboxScreen.reminderSettings": "Reminder settings",
  "mobile.NotificationInboxScreen.notifications": "Notifications",
  "mobile.NotificationInboxScreen.all": "All",
  "mobile.NotificationInboxScreen.unread": "Unread",
  "mobile.NotificationInboxScreen.updatingNotifications": "Updating notifications",
  "mobile.NotificationSettingsScreen.loadingReminders": "Loading reminders",
  "mobile.NotificationSettingsScreen.retryLoadingReminders": "Retry loading reminders",
  "mobile.NotificationSettingsScreen.retry": "Retry",
  "mobile.NotificationSettingsScreen.back": "Back",
  "mobile.NotificationSettingsScreen.yourRemindersForThisInventory": "Your reminders for this inventory.",
  "mobile.NotificationSettingsScreen.notifications": "Notifications",
  "mobile.NotificationSettingsScreen.pushNotifications": "Push notifications",
  "mobile.NotificationSettingsScreen.openNotificationSystemSettings": "Open notification system settings",
  "mobile.NotificationSettingsScreen.openSettings": "Open Settings",
  "mobile.NotificationSettingsScreen.timeZone": "Time zone",
  "mobile.NotificationSettingsScreen.assetTypeReminders": "Asset type reminders",
  "mobile.OnboardingAddressInputios.httpsStashExampleCom": "https://stash.example.com",
  "mobile.OnboardingAddressInput.serverAddress": "Server address",
  "mobile.OnboardingAddressInput.httpsStashExampleCom": "https://stash.example.com",
  "mobile.OnboardingScreen.yourInvitationIsWaitingSignInToReviewIt": "Your invitation is waiting. Sign in to review it.",
  "mobile.OnboardingScreen.needHelpConnecting": "Need help connecting?",
  "mobile.OnboardingScreen.enterYourStuffStashServerSFullAddressIncluding": "Enter your Stuff Stash server’s full address, including a port or path if needed.",
  "mobile.OnboardingScreen.youLlNeedARunningStuffStashServerTo": "You’ll need a running Stuff Stash server to connect. If you’re joining someone else’s inventory, ask them for its server address.",
  "mobile.OnboardingScreen.yourBrowserWillOpenForSignInThenBring": "Your browser will open for sign-in, then bring you back here.",
  "mobile.OnboardingScreen.setupInProgress": "Setup in progress",
  "mobile.OnboardingScreen.signOutAndStartOver": "Sign out and start over",
  "mobile.ProviderProfileEditorScreens.thisProfileDoesNotSupportMobileCredentialEditing": "This profile does not support mobile credential editing.",
  "mobile.ProviderProfileEditorScreens.thisProviderProfileIsNoLongerAvailable": "This provider profile is no longer available.",
  "mobile.ProviderProfileEditorScreens.credentialSaved": "Credential saved",
  "mobile.ProviderProfileEditorScreens.saveCredential": "Save Credential",
  "mobile.ProviderProfileEditorScreens.secretsAreSentDirectlyToYourStuffStashServer": ". Secrets are sent directly to your Stuff Stash server and aren’t stored on this device.",
  "mobile.ProviderProfileEditorScreens.useTheApplicationDefaultCredentialsConfiguredByTheServer": "Use the Application Default Credentials configured by the server operator. No provider secret is entered here.",
  "mobile.ProviderProfileEditorScreens.saving": "Saving…",
  "mobile.ProviderProfileEditorScreens.promptGuidanceSaved": "Prompt guidance saved",
  "mobile.ProviderProfileEditorScreens.saveGuidance": "Save Guidance",
  "mobile.ProviderProfileEditorScreens.optionalTenantGuidanceFor": "Optional tenant guidance for ",
  "mobile.ProviderProfileEditorScreens.existingHiddenPromptTextIsNeverReturnedToThe": ". Existing hidden prompt text is never returned to the phone.",
  "mobile.ProviderProfileEditorScreens.newPromptGuidance": "New prompt guidance",
  "mobile.ProviderProfileScreens.addAProviderProfile": "Add a provider profile",
  "mobile.ProviderProfileScreens.addProfile": "Add Profile",
  "mobile.ProviderProfileScreens.profiles": "Profiles",
  "mobile.ProviderProfileScreens.noProfiles": "No profiles",
  "mobile.ProviderProfileScreens.draftProfileCreated": "Draft profile created",
  "mobile.ProviderProfileScreens.addCredentialsTestItThenEnableItForVoice": "Add credentials, test it, then enable it for voice.",
  "mobile.ProviderProfileScreens.couldNotCreateProfile": "Could not create profile",
  "mobile.ProviderProfileScreens.chooseAService": "Choose a Service",
  "mobile.ProviderProfileScreens.stuffStashCreatesADisabledDraftFirstYouLl": "Stuff Stash creates a disabled draft first. You’ll add credentials, test the connection, and enable it next.",
  "mobile.ProviderProfileScreens.recommended": "Recommended",
  "mobile.ProviderProfileScreens.thisProviderProfileIsNoLongerAvailable": "This provider profile is no longer available.",
  "mobile.ProviderProfileScreens.profileActionFailed": "Profile action failed",
  "mobile.ProviderProfileScreens.configuration": "Configuration",
  "mobile.ProviderProfileScreens.model": "Model",
  "mobile.ProviderProfileScreens.status": "Status",
  "mobile.ProviderProfileScreens.credential": "Credential",
  "mobile.ProviderProfileScreens.lastTested": "Last tested",
  "mobile.ProviderProfileScreens.actions": "Actions",
  "mobile.ProviderProfileScreens.replaceCredential": "Replace Credential",
  "mobile.ProviderProfileScreens.promptGuidance": "Prompt Guidance",
  "mobile.ProviderSettingsSupport.providerProfilesAreNoLongerAvailable": "Provider profiles are no longer available.",
  "mobile.ProviderSettingsSupport.providerProfilesCouldNotBeLoaded": "Provider profiles could not be loaded.",
  "mobile.ProviderSettingsSupport.voiceSettingsAreNoLongerAvailable": "Voice settings are no longer available.",
  "mobile.ProviderSettingsSupport.voiceSettingsCouldNotBeLoaded": "Voice settings could not be loaded.",
  "mobile.ProviderSettingsSupport.retry": "Retry",
  "mobile.ScopedSettingsScreens.couldNotLoadSettings": "Could not load settings",
  "mobile.ScopedSettingsScreens.retry": "Retry",
  "mobile.ScopedSettingsScreens.customFields": "Custom fields",
  "mobile.ScopedSettingsScreens.assetTypes": "Asset types",
  "mobile.ScopedSettingsScreens.voiceSetup": "Voice setup",
  "mobile.ScopedSettingsScreens.sharing": "Sharing",
  "mobile.ScopedSettingsScreens.notifications": "Notifications",
  "mobile.ScopedSettingsScreens.tags": "Tags",
  "mobile.ScopedSettingsScreens.youDonTHavePermissionToManageSettingsShared": "You don’t have permission to manage settings shared by this household.",
  "mobile.ScopedSettingsScreens.settingsUnavailable": "Settings unavailable",
  "mobile.SearchScreen.thisInventoryCouldNotBeLoaded": "This inventory could not be loaded.",
  "mobile.SearchScreen.searchNamesPlacesOrTags": "Search names, places, or tags",
  "mobile.SearchScreen.noMatchingItemsInThePagesLoadedSoFar": "No matching items in the pages loaded so far.",
  "mobile.SearchScreen.continueLoadingResults": "Continue loading results",
  "mobile.SearchScreenPresentation.all": "All",
  "mobile.SearchScreenPresentation.places": "Places",
  "mobile.SearchScreenPresentation.containers": "Containers",
  "mobile.SearchScreenPresentation.items": "Items",
  "mobile.SettingsDetailScreens.couldNotSignOut": "Could not sign out",
  "mobile.SettingsDetailScreens.signedInAs": "Signed in as",
  "mobile.SettingsDetailScreens.couldNotChangeServer": "Could not change server",
  "mobile.SettingsDetailScreens.currentServer": "Current Server",
  "mobile.SettingsDetailScreens.server": "Server",
  "mobile.SettingsDetailScreens.address": "Address",
  "mobile.SettingsDetailScreens.connection": "Connection",
  "mobile.SettingsDetailScreens.aPIURL": "API URL",
  "mobile.SettingsDetailScreens.authentication": "Authentication",
  "mobile.SettingsDetailScreens.identity": "Identity",
  "mobile.SettingsDetailScreens.principalID": "Principal ID",
  "mobile.SettingsDetailScreens.tenantID": "Tenant ID",
  "mobile.SettingsDetailScreens.application": "Application",
  "mobile.SettingsDetailScreens.version": "Version",
  "mobile.SettingsDetailScreens.stuffStash": "Stuff Stash",
  "mobile.SettingsDetailScreens.aCalmFlexibleHomeInventoryForKnowingWhatYou": "A calm, flexible home inventory for knowing what you have and where it lives.",
  "mobile.SettingsList.opensASettingsScreen": "Opens a settings screen",
  "mobile.SettingsRefreshNotice.retryRefresh": "Retry refresh",
  "mobile.SettingsScreen.loadingSettings": "Loading settings",
  "mobile.SettingsScreen.couldNotLoadSettings": "Could not load Settings",
  "mobile.SettingsScreen.retry": "Retry",
  "mobile.SettingsScreen.openAccountSettings": "Open Account settings",
  "mobile.SettingsScreen.account": "Account",
  "mobile.SettingsScreen.openStuffStashServerSettings": "Open Stuff Stash server settings",
  "mobile.SettingsScreen.stuffStashServer": "Stuff Stash server",
  "mobile.SettingsScreenPresentation.preferences": "Preferences",
  "mobile.SettingsScreenPresentation.householdAndInventory": "Household and Inventory",
  "mobile.SettingsScreenPresentation.connection": "Connection",
  "mobile.SettingsScreenPresentation.about": "About",
  "mobile.SettingsScreenState.theseSettingsAreNoLongerAvailable": "These settings are no longer available.",
  "mobile.SettingsScreenState.stuffStashCouldNotLoadSettings": "Stuff Stash could not load settings.",
  "mobile.TenantSwitcherSheetScreen.inventories": "Inventories",
  "mobile.TenantSwitcherSheetScreen.newInventory": "New inventory",
  "mobile.TenantSwitcherSheetScreen.noInventoriesAreAvailableInThisHousehold": "No inventories are available in this household.",
  "mobile.TenantSwitcherSheetScreen.households": "Households",
  "mobile.TenantSwitcherSheetScreen.newHousehold": "New household",
  "mobile.TenantSwitcherSheetScreen.loadingInventories": "Loading inventories",
  "mobile.TenantSwitcherSheetScreen.couldNotLoad": "Could not load",
  "mobile.TenantSwitcherSheetScreen.inventoriesCouldNotBeLoadedTryAgain": "Inventories could not be loaded. Try again.",
  "mobile.TenantSwitcherSheetScreen.retryInventories": "Retry inventories",
  "mobile.VoiceConversationComposer.messageStuffStash": "Message Stuff Stash",
  "mobile.VoiceConversationComposer.askOrAddSomething": "Ask or add something…",
  "mobile.VoiceConversationComposer.cancelRequest": "Cancel request",
  "mobile.VoiceConversationComposer.workingOnYourRequest": "Working on your request",
  "mobile.VoiceConversationExchange.newConversationContext": "New conversation context",
  "mobile.VoiceConversationExchange.you": "You",
  "mobile.VoiceConversationExchange.retryPhotos": "Retry photos",
  "mobile.VoiceConversationHeader.closeVoiceSession": "Close voice session",
  "mobile.VoiceConversationHeader.newConversation": "New conversation",
  "mobile.VoiceConversationHeader.conversation": "Conversation",
  "mobile.VoiceNativeSheetOptions.conversation": "Conversation",
  "mobile.VoicePlanLocationChoices.inventoryRoot": "Inventory root",
  "mobile.VoicePlanLocationRouteScreen.backToConversation": "Back to conversation",
  "mobile.VoicePlanLocationRouteScreen.containingLocation": "Containing location",
  "mobile.VoicePlanLocationRouteScreen.thisProposalIsNoLongerAvailableForEditing": "This proposal is no longer available for editing.",
  "mobile.VoicePlanLocationScreen.searchLocations": "Search locations",
  "mobile.VoicePlanLocationScreen.currentLocation": "Current location",
  "mobile.VoicePlanLocationScreen.inventoryRoot": "Inventory root",
  "mobile.VoicePlanLocationScreen.selectInventoryRoot": "Select Inventory root",
  "mobile.VoicePlanLocationScreen.createdByThisPlan": "Created by this plan",
  "mobile.VoicePlanLocationScreen.existingLocations": "Existing locations",
  "mobile.VoicePlanLocationScreen.loadingLocations": "Loading locations",
  "mobile.VoicePlanLocationScreen.couldNotLoadLocations": "Could not load locations.",
  "mobile.VoicePlanLocationScreen.retryLocations": "Retry locations",
  "mobile.VoicePlanNameEditor.proposedItemName": "Proposed item name",
  "mobile.VoicePlanNameEditor.cancel": "Cancel",
  "mobile.VoicePlanNameEditor.save": "Save",
  "mobile.VoicePlanPhotoDrafts.addPhotos": "Add photos",
  "mobile.VoicePlanProgressPresentation.cancellingChange": "Cancelling change…",
  "mobile.VoicePlanProgressPresentation.saved": "Saved",
  "mobile.VoicePreviewRecovery.voiceUnavailable": "Voice unavailable",
  "mobile.VoicePreviewRecovery.retryConversation": "Retry conversation",
  "mobile.VoiceResultRailNavigation.previous": "Previous",
  "mobile.VoiceResultRailNavigation.next": "Next",
  "mobile.VoiceSessionSheetScreen.findSomethingAddAnItemOrOrganizeYourBelongings": "Find something, add an item, or organize your belongings. Speak or type below.",
  "mobile.VoiceSessionSheetScreen.newConversationContextEarlierExchangesAreShownForYour": "New conversation context · earlier exchanges are shown for your reference.",
  "mobile.VoiceSessionSheetScreen.you": "You",
  "mobile.VoiceSessionSheetScreen.cancelledNoChangeWasMade": "Cancelled. No change was made.",
  "mobile.VoiceSessionSheetScreen.retryPhotos": "Retry photos",
  "mobile.VoiceSessionSheetScreen.couldNotApplyThisChange": "Could not apply this change.",
  "mobile.VoiceSessionSheetScreen.diagnostics": "Diagnostics",
  "mobile.VoiceSessionSheetScreen.enterANameBeforeApproving": "Enter a name before approving.",
  "mobile.VoiceSessionSheetScreen.editsTheNameInline": "Edits the name inline",
  "mobile.VoiceSessionSheetScreen.opensTheContainingLocationSelector": "Opens the containing location selector",
  "mobile.VoiceSessionSheetScreen.loadingVoice": "Loading voice",
  "mobile.VoiceSettingsScreens.appliesToEveryoneIn": "Applies to everyone in ",
  "mobile.VoiceSettingsScreens.configureHowStuffStashListensUnderstandsRequestsAndSpeaks": ". Configure how Stuff Stash listens, understands requests, and speaks.",
  "mobile.VoiceSettingsScreens.voicePipeline": "Voice Pipeline",
  "mobile.VoiceSettingsScreens.advanced": "Advanced",
  "mobile.VoiceSettingsScreens.providerProfiles": "Provider Profiles",
  "mobile.VoiceSettingsScreens.thisVoiceStageIsNotAvailable": "This voice stage is not available.",
  "mobile.VoiceSettingsScreens.notSelected": "Not selected",
  "mobile.VoiceSettingsScreens.couldNotUpdateVoice": "Could not update voice",
  "mobile.VoiceSettingsScreens.addProfile": "Add Profile",
  "mobile.VoiceSettingsScreens.addCredential": "Add Credential",
  "mobile.VoiceSettingsScreens.selectedService": "Selected Service",
  "mobile.VoiceSettingsScreens.service": "Service",
  "mobile.VoiceSettingsScreens.setupStatus": "Setup Status",
  "mobile.VoiceSettingsScreens.selection": "Selection",
  "mobile.VoiceSettingsScreens.readyChoices": "Ready choices",
  "mobile.VoiceSettingsScreens.chooseVoiceService": "Choose voice service",
  "mobile.VoiceSettingsScreens.selectingService": "Selecting service…",
  "mobile.VoiceSettingsScreens.loadingHouseholdContext": "Loading household context",
  "mobile.VoiceSettingsScreens.couldNotLoadTenantContext": "Could not load tenant context",
  "mobile.VoiceSettingsScreens.retry": "Retry",
  "mobile.VoiceStagePresentation.listen": "Listen",
  "mobile.VoiceStagePresentation.speechToText": "Speech to text",
  "mobile.VoiceStagePresentation.understand": "Understand",
  "mobile.VoiceStagePresentation.languageModel": "Language model",
  "mobile.VoiceStagePresentation.speak": "Speak",
  "mobile.VoiceStagePresentation.spokenResponses": "Spoken responses",
  "mobile.VoiceStagePresentation.voiceService": "Voice Service",
  "mobile.VoiceStagePresentation.unknownCapability": "Unknown capability",
  "mobile.WorkspaceCreationForm.creating": "Creating…",
  "mobile.useHomeReturnActions.returnCompletedWithoutUndo": "Return completed without undo",
  "mobile.useHomeReturnActions.theAssetWasReturnedButThisReturnCannotBe": "The asset was returned, but this return cannot be canceled.",
  "mobile.usePullRefreshFeedback.pleaseTryRefreshingAgain": "Please try refreshing again.",
  "mobile.notifications.loadingInventory": "Loading inventory",
  "mobile.notifications.retry": "Retry",
  "mobile.notificationeditor.thisSettingsLinkIsUnavailable": "This settings link is unavailable.",
  "mobile.notifications.thisInventoryIsNoLongerSelectedGoBackTo": "This inventory is no longer selected. Go back to open its settings again.",
  "mobile.layout.home": "Home",
  "mobile.layout.browse": "Browse",
  "mobile.layout.containingLocation": "Containing location",
  "mobile.layout.invitation": "Invitation",
  "mobile.layout.putIn": "Put in",
  "mobile.layout.tags": "Tags",
  "mobile.layout.returnDetails": "Return details",
  "mobile.expirationfilters.filtersCouldNotBeLoaded": "Filters could not be loaded.",
  "mobile.expirationfilters.retry": "Retry",
  "mobile.expirationfilters.cancel": "Cancel"
} as const;
