export const printingMobileMessages = {
  'printing.mobile.online': 'Connector online',
  'printing.mobile.offline': 'Connector offline',
  'printing.mobile.connectionUnknown': 'Connection status unknown',
  'printing.mobile.reportedAt': 'Printer checked: {time}',
  'printing.mobile.paperEmpty': 'Load labels in the printer',
  'printing.mobile.coverOpen': 'Close the printer cover',
  'printing.mobile.deviceBusy': 'Printer is busy',
  'printing.mobile.hardwareError': 'Check the printer for an error',
  'printing.mobile.createRejected': 'The item and label were not saved. Check the selected printer and label defaults, or turn off label printing before trying again.',
  'printing.mobile.viewJob': 'View print job',
  'printing.mobile.defaultsUnavailable': 'Label settings could not be loaded. Try again or add this item without a label.',
  'printing.mobile.addWithoutLabel': 'Add without a label',
  'printing.mobile.createRetry': 'The item and label request may already be saved. Retry Save to check the same request without creating another item or label.',
  'printing.mobile.title': 'Printers',
  'printing.mobile.print': 'Print label',
  'printing.mobile.loading': 'Loading printing settings…',
  'printing.mobile.unavailable': 'Printing is unavailable. Check your connection and inventory access, then try again.',
  'printing.mobile.retry': 'Try again',
  'printing.mobile.reload': 'Reload settings',
  'printing.mobile.save': 'Save defaults',
  'printing.mobile.saved': 'Defaults saved',
  'printing.mobile.saveFailed': 'Could not save. Your draft is still here. Reload if another person changed these settings.',
  'printing.mobile.defaults': 'Label defaults',
  'printing.mobile.printer': 'Printer',
  'printing.mobile.none': 'No default printer',
  'printing.mobile.empty': 'No printers registered. Register a printer with the Stuff Stash CLI to print labels here.',
  'printing.mobile.template': 'Layout',
  'printing.mobile.reference': 'Show reference',
  'printing.mobile.auto': 'Print label when adding an item',
  'printing.mobile.preview': 'Preview label',
  'printing.mobile.previewAlt': 'Label preview',
  'printing.mobile.jobs': 'Recent print jobs',
  'printing.mobile.noJobs': 'No print jobs yet',
  'printing.mobile.job': 'Print job',
  'printing.mobile.cancel': 'Cancel print job',
  'printing.mobile.refresh': 'Refresh status',
  'printing.mobile.refreshFailed': 'Could not refresh status. The information shown may be out of date.',
  'printing.mobile.unknownSubmission': 'The request may have been queued. Try again to check the same request without printing a second label.',
  'printing.mobile.uncertain': 'The printer may have produced a label. Check it before requesting another copy. This printer’s queue stays paused until the outcome is resolved.',
  'printing.mobile.copyProgress': '{completed} of {total} copies confirmed',
  'printing.mobile.lastSeen': 'Last seen: {time}',
  'printing.mobile.neverSeen': 'No connection reported',
  'printing.mobile.connector': 'Connector: {name}',
  'printing.mobile.retired': 'Retired',
  'printing.mobile.readiness.ready': 'Printer ready',
  'printing.mobile.readiness.unavailable': 'Printer unavailable — check power and USB',
  'printing.mobile.readiness.error': 'Printer needs attention',
  'printing.mobile.readiness.unknown': 'Printer status unknown',
  'printing.mobile.state.active': 'Connector registered',
  'printing.mobile.state.pending': 'Waiting for connector activation',
  'printing.mobile.state.revoked': 'Connector access revoked',
  'printing.mobile.state.unknown': 'Connector status unknown',
  'printing.mobile.status.queued': 'Queued',
  'printing.mobile.status.claimed': 'Preparing to print',
  'printing.mobile.status.printing': 'Printing',
  'printing.mobile.status.completed': 'Completed',
  'printing.mobile.status.failed': 'Failed',
  'printing.mobile.status.canceled': 'Canceled',
  'printing.mobile.status.uncertain': 'Output uncertain',
  'printing.mobile.status.unknown': 'Status unavailable'
} as const;
