/** Web presentation messages. Keys describe context, never wire values. */
export const webMessages = {
  "web.AuthBrand.stuffStash": "Stuff Stash",
  "web.InvitationAcceptSurface.inventoryInvitationStuffStash": "Inventory invitation · Stuff Stash",
  "web.InvitationAcceptSurface.checkingInvitation": "Checking invitation…",
  "web.InvitationAcceptSurface.youVeBeenInvited": "You’ve been invited",
  "web.InvitationAcceptSurface.join": "Join",
  "web.InvitationAcceptSurface.youAlreadyJoined": "You already joined",
  "web.InvitationAcceptSurface.youJoined": "You joined",
  "web.InvitationAcceptSurface.thisInvitationExpired": "This invitation expired",
  "web.InvitationAcceptSurface.thisInvitationWasRevoked": "This invitation was revoked",
  "web.InvitationAcceptSurface.thisInvitationWasCancelled": "This invitation was cancelled",
  "web.InvitationAcceptSurface.thisInvitationIsForAnotherAccount": "This invitation is for another account",
  "web.InvitationAcceptSurface.invitationCouldNotBeChecked": "Invitation could not be checked",
  "web.InvitationAcceptSurface.thisInvitationLinkIsInvalid": "This invitation link is invalid",
  "web.InvitationAcceptSurface.thisWillOnlyTakeAMoment": "This will only take a moment.",
  "web.InvitationAcceptSurface.signInToViewTheInventoryAndAccessLevel": "Sign in to view the inventory and access level before accepting.",
  "web.InvitationAcceptSurface.reviewTheDetailsThenAcceptWhenYouReReady": "Review the details, then accept when you’re ready.",
  "web.InvitationAcceptSurface.youCanOpenTheInventoryNow": "You can open the inventory now.",
  "web.InvitationAcceptSurface.askTheInventoryOwnerToSendANewInvitation": "Ask the inventory owner to send a new invitation.",
  "web.InvitationAcceptSurface.theInventoryOwnerRevokedThisInvitationAskThemTo": "The inventory owner revoked this invitation. Ask them to send a new one if you still need access.",
  "web.InvitationAcceptSurface.theInventoryOwnerCancelledThisInvitationAskThemTo": "The inventory owner cancelled this invitation. Ask them to send a new one if you still need access.",
  "web.InvitationAcceptSurface.signOutThenUseTheAccountThatReceivedThe": "Sign out, then use the account that received the invitation.",
  "web.InvitationAcceptSurface.yourAccessHasNotChangedCheckYourConnectionAnd": "Your access has not changed. Check your connection and try again.",
  "web.InvitationAcceptSurface.checkThatYouOpenedTheCompleteLinkOrAsk": "Check that you opened the complete link, or ask for a new invitation.",
  "web.InvitationAcceptSurface.inventory": "Inventory",
  "web.InvitationAcceptSurface.access": "Access",
  "web.InvitationAcceptSurface.invitationExpires": "Invitation expires",
  "web.InvitationAcceptSurface.openInventory": "Open inventory",
  "web.dialogcontent.close": "Close",
  "web.dialogfooter.close": "Close",
  "web.sheetcontent.close": "Close",
  "web.AccountMenu.account": "Account",
  "web.AccountMenu.openAccountMenu": "Open account menu",
  "web.AccountMenu.signedInToStuffStash": "Signed in to Stuff Stash",
  "web.AccountMenu.settings": "Settings",
  "web.AccountMenu.signOut": "Sign out",
  "web.AccountMenu.signedInAs": "Signed in as",
  "web.AddAssetCustomFieldsSection.customType": "Custom type",
  "web.AddAssetCustomFieldsSection.customAssetType": "Custom asset type",
  "web.AddAssetCustomFieldsSection.customFields": "Custom fields",
  "web.AddAssetCustomFieldsSection.baseAsset": "Base asset",
  "web.AddAssetPhotosSection.photos": "Photos",
  "web.AddAssetTray.closeAddTray": "Close add tray",
  "web.AddAssetTray.cancel": "Cancel",
  "web.AssetDetail.back": "Back",
  "web.AssetDetail.choosePhoto": "Choose photo",
  "web.AssetDetail.chooseFile": "Choose file",
  "web.AssetDetail.expiration": "Expiration",
  "web.AssetDetail.kind": "Kind",
  "web.AssetDetail.type": "Type",
  "web.AssetDetail.checkout": "Checkout",
  "web.AssetDetail.updated": "Updated",
  "web.AssetDetail.edit": "Edit",
  "web.AssetDetail.move": "Move",
  "web.AssetDetail.return": "Return",
  "web.AssetDetail.checkOut": "Check out",
  "web.AssetDetail.archive": "Archive",
  "web.AssetDetail.restore": "Restore",
  "web.AssetDetail.details": "Details",
  "web.AssetDetail.customFieldValues": "Custom field values",
  "web.AssetDetail.unset": "unset",
  "web.AssetDetail.unsetCustomFields": "Unset custom fields",
  "web.AssetDetail.notSet": "Not set",
  "web.AssetDetail.checkoutHistory": "Checkout history",
  "web.AssetDetail.loadingCheckoutHistory": "Loading checkout history…",
  "web.AssetDetail.noCheckoutHistory": "No checkout history.",
  "web.AssetDetail.by": "by",
  "web.AssetDetail.returned": "Returned",
  "web.AssetDetail.dangerArea": "Danger area",
  "web.AssetDetail.permanentDeletion": "Permanent deletion",
  "web.AssetDetail.removeThisAssetFromTheInventoryPermanently": "Remove this asset from the inventory permanently.",
  "web.AssetDetail.delete": "Delete",
  "web.AssetDetailActionPanel.editAsset": "Edit asset",
  "web.AssetDetailActionPanel.updateTheNameDetailsFieldsAndTags": "Update the name, details, fields, and tags.",
  "web.AssetDetailActionPanel.name": "Name",
  "web.AssetDetailActionPanel.description": "Description",
  "web.AssetDetailActionPanel.customType": "Custom type",
  "web.AssetDetailActionPanel.customAssetType": "Custom asset type",
  "web.AssetDetailActionPanel.expiration": "Expiration:",
  "web.AssetDetailActionPanel.clearExpiration": "Clear expiration",
  "web.AssetDetailActionPanel.details": "Details",
  "web.AssetDetailActionPanel.empty": "empty",
  "web.AssetDetailActionPanel.emptyDetails": "Empty details",
  "web.AssetDetailActionPanel.cancel": "Cancel",
  "web.AssetDetailActionPanel.save": "Save",
  "web.AssetDetailActionPanel.move": "Move",
  "web.AssetDetailActionPanel.archiveAsset": "Archive asset",
  "web.AssetDetailActionPanel.archive": "Archive",
  "web.AssetDetailActionPanel.restoreAsset": "Restore asset",
  "web.AssetDetailActionPanel.restore": "Restore",
  "web.AssetDetailActionPanel.deleteAsset": "Delete asset",
  "web.AssetDetailActionPanel.delete": "Delete",
  "web.AssetDetailActionPanel.checkOutAsset": "Check out asset",
  "web.AssetDetailActionPanel.optionalUsingAtDeskLoanedToSam": "Optional: using at desk, loaned to Sam",
  "web.AssetDetailActionPanel.checkOut": "Check out",
  "web.AssetDetailActionPanel.returnAsset": "Return asset",
  "web.AssetDetailActionPanel.optionalBackInBinReturnedByAlex": "Optional: back in bin, returned by Alex",
  "web.AssetDetailActionPanel.return": "Return",
  "web.AssetDetailActionPanel.deleteAttachment": "Delete attachment",
  "web.AssetDetailHero.assetPhotos": "Asset photos",
  "web.AssetDetailHero.addPhoto": "Add photo",
  "web.AssetDetailHero.removePhoto": "Remove photo",
  "web.AssetDetailHero.assetPhotoGallery": "Asset photo gallery",
  "web.AssetDetailHero.photos": "Photos",
  "web.AssetDetailHero.primary": "Primary",
  "web.AssetDetailHero.uploadingPhoto": "Uploading photo…",
  "web.AssetDetailHero.retry": "Retry",
  "web.AssetFilesSection.files": "Files",
  "web.AssetFilesSection.uploadFile": "Upload file",
  "web.AssetFilesSection.loadingFiles": "Loading files…",
  "web.AssetFilesSection.archive": "Archive",
  "web.AssetFilesSection.delete": "Delete",
  "web.AssetLocationTrail.itemLocation": "Item location",
  "web.AssetTagChips.assetTags": "Asset tags",
  "web.AssetTagSelector.tags": "Tags",
  "web.AssetTagSelector.availableTags": "Available tags",
  "web.AssetTagSelector.newTag": "New tag",
  "web.AssetTagSelector.workshop": "Workshop",
  "web.AssetTagSelector.color": "Color",
  "web.AssetTagSelector.2F80ED": "#2F80ED",
  "web.AssetTagSelector.pickNewTagColor": "Pick new tag color",
  "web.AssetTagSelector.add": "Add",
  "web.AssetThumb.photoUnavailable": "Photo unavailable",
  "web.BrowsePanel.browse": "Browse",
  "web.BrowsePanel.browseSurface": "Browse surface",
  "web.BrowsePanel.searchBrowse": "Search Browse",
  "web.BrowsePanel.searchThisInventory": "Search this inventory",
  "web.BrowsePanel.search": "Search",
  "web.BrowsePanel.browseScope": "Browse scope",
  "web.BrowsePanel.filters": "Filters",
  "web.BrowsePanel.limitTheAssetsShownInBrowse": "Limit the assets shown in Browse.",
  "web.BrowsePanel.status": "Status",
  "web.BrowsePanel.availability": "Availability",
  "web.BrowsePanel.tags": "Tags",
  "web.BrowsePanel.reset": "Reset",
  "web.BrowsePanel.cancel": "Cancel",
  "web.BrowsePanel.applyFilters": "Apply filters",
  "web.BrowsePanel.sortBrowse": "Sort Browse",
  "web.BrowsePanel.sort": "Sort",
  "web.BrowsePanel.recentlyChanged": "Recently changed",
  "web.BrowsePanel.defaultOrder": "Default order",
  "web.BrowsePanel.resultsAreOrderedBySearchRelevance": "Results are ordered by search relevance.",
  "web.BrowsePanel.shown": "shown",
  "web.BrowsePanel.updating": "Updating…",
  "web.BrowsePanel.appliedFilters": "Applied filters",
  "web.BrowsePanel.clearAll": "Clear all",
  "web.BrowsePanel.browseFailed": "Browse failed",
  "web.BrowsePanel.tryAgain": "Try again",
  "web.BrowsePanel.loadingInventory": "Loading inventory…",
  "web.BrowsePanel.addItem": "Add item",
  "web.BrowsePanel.addLocation": "Add location",
  "web.BrowsePanel.clearSearch": "Clear search",
  "web.BrowsePanel.loadingMap": "Loading map…",
  "web.BrowsePanel.updatingMap": "Updating map…",
  "web.BrowsePanel.tryMapAgain": "Try map again",
  "web.BrowsePanel.containmentPath": "Containment path",
  "web.BrowsePanel.inventoryRoot": "Inventory root",
  "web.BrowsePanel.jumpToAPlaceOrContainer": "Jump to a place or container",
  "web.BrowsePanel.jumpTo": "Jump to…",
  "web.BrowsePanel.mapJumpResults": "Map jump results",
  "web.BrowsePanel.selectedMapAsset": "Selected map asset",
  "web.BrowsePanel.open": "Open",
  "web.BrowsePanel.nothingIsContainedHere": "Nothing is contained here.",
  "web.BrowsePanel.showNext": "Show next",
  "web.BrowsePanel.of": "of",
  "web.CheckoutBadge.checkedOut": "Checked out",
  "web.ContainedAssetWorkspace.spatialActions": "Spatial actions",
  "web.ContainedAssetWorkspace.addItemHere": "Add item here",
  "web.ContainedAssetWorkspace.moveItemsHere": "Move items here",
  "web.ContainedAssetWorkspace.addingItemsIsUnavailableForThisInventory": "Adding items is unavailable for this inventory.",
  "web.ContainedAssetWorkspace.findAnAsset": "Find an asset",
  "web.ContainedAssetWorkspace.searchByNameOrCurrentPlace": "Search by name or current place",
  "web.ContainedAssetWorkspace.eligible": "eligible",
  "web.ContainedAssetWorkspace.eligibleAssets": "Eligible assets",
  "web.ContainedAssetWorkspace.showAll": "Show all",
  "web.ContainedAssetWorkspace.clearSearch": "Clear search",
  "web.ContainedAssetWorkspace.move": "Move",
  "web.ContainedAssetWorkspace.into": "into",
  "web.ContainedAssetWorkspace.cancel": "Cancel",
  "web.ContainedAssetWorkspace.searchContents": "Search contents",
  "web.ContainedAssetWorkspace.searchThisPlace": "Search this place",
  "web.CustomFieldControls.unset": "Unset",
  "web.CustomFieldControls.yes": "Yes",
  "web.CustomFieldControls.no": "No",
  "web.ExpirationField.expirationOptional": "Expiration (optional)",
  "web.ExpirationField.expirationPrecision": "Expiration precision",
  "web.ExpirationField.enterACompleteValidExpirationDate": "Enter a complete, valid expiration date.",
  "web.ExpirationField.trackedThroughTheEndOfThisMonth": "Tracked through the end of this month.",
  "web.ExpirationField.trackedThroughTheEndOfThisDay": "Tracked through the end of this day.",
  "web.ExpirationField.clearExpiration": "Clear expiration",
  "web.HomeWorkspace.assetLifecycle": "Asset lifecycle",
  "web.HomeWorkspace.addLocation": "Add location",
  "web.HomeWorkspace.recentlyChanged": "Recently changed",
  "web.HomeWorkspace.recentlyChangedNavigation": "Recently changed navigation",
  "web.HomeWorkspace.previousRecentlyChangedAssets": "Previous recently changed assets",
  "web.HomeWorkspace.nextRecentlyChangedAssets": "Next recently changed assets",
  "web.HomeWorkspace.recentlyChangedAssets": "Recently changed assets",
  "web.HomeWorkspace.checkedOut": "Checked out",
  "web.HomeWorkspace.archived": "Archived",
  "web.HomeWorkspace.places": "Places",
  "web.HomeWorkspace.viewAllPlaces": "View all places",
  "web.ImportFlowStepper.source": "Source",
  "web.ImportFlowStepper.connect": "Connect",
  "web.ImportFlowStepper.preview": "Preview",
  "web.ImportFlowStepper.run": "Run",
  "web.ImportJobConfirmationPanel.keepRunning": "Keep running",
  "web.ImportJobConfirmationPanel.keepImportedItems": "Keep imported items",
  "web.ImportJobConfirmationPanel.stopFutureWorkAndLeaveAnythingAlreadyImportedIn": "Stop future work and leave anything already imported in the inventory.",
  "web.ImportJobConfirmationPanel.discardImportedItems": "Discard imported items",
  "web.ImportJobConfirmationPanel.stopFutureWorkAndRemoveRecordsCreatedByThis": "Stop future work and remove records created by this job. Audit history remains.",
  "web.ImportJobConfirmationPanel.importedRecordsAndAuditHistoryWillRemainThisOnly": "Imported records and audit history will remain. This only removes the run from the import history list.",
  "web.ImportJobConfirmationPanel.keepInHistory": "Keep in history",
  "web.ImportJobConfirmationPanel.removeFromHistory": "Remove from history",
  "web.ImportJobDetailPanel.importRunSummary": "Import run summary",
  "web.ImportJobDetailPanel.changed": "Changed",
  "web.ImportJobDetailPanel.issues": "Issues",
  "web.ImportJobDetailPanel.reviewTheBlockingItemsBeforeRelyingOnThisRun": "Review the blocking items before relying on this run.",
  "web.ImportJobDetailPanel.reviewIssues": "Review issues",
  "web.ImportJobDetailPanel.refreshingImportDetails": "Refreshing import details.",
  "web.ImportJobDetailPanel.importDetailSections": "Import detail sections",
  "web.ImportJobDetailPanel.overview": "Overview",
  "web.ImportJobDetailPanel.plan": "Plan",
  "web.ImportJobDetailPanel.records": "Records",
  "web.ImportJobDetailPanel.timeline": "Timeline",
  "web.ImportJobDetailPanel.importResultOverview": "Import result overview",
  "web.ImportJobDetailPanel.result": "Result",
  "web.ImportJobDetailPanel.importIssues": "Import issues",
  "web.ImportJobDetailPanel.importPreviewPlan": "Import preview plan",
  "web.ImportJobDetailPanel.previewPlan": "Preview plan",
  "web.ImportJobDetailPanel.noPreviewPlanIsAvailableForThisRun": "No preview plan is available for this run.",
  "web.ImportJobDetailPanel.recordsCreatedByThisJobWereDiscardedAuditHistory": "Records created by this job were discarded. Audit history remains.",
  "web.ImportJobDetailPanel.importedRecords": "Imported records",
  "web.ImportJobDetailPanel.of": "of",
  "web.ImportJobDetailPanel.record": "Record",
  "web.ImportJobDetailPanel.source": "Source",
  "web.ImportJobDetailPanel.open": "Open",
  "web.ImportJobDetailPanel.imported": "· Imported",
  "web.ImportJobDetailPanel.page": "Page",
  "web.ImportJobDetailPanel.previous": "Previous",
  "web.ImportJobDetailPanel.next": "Next",
  "web.ImportJobDetailPanel.noImportedRecordSummariesAreAvailableForThisRun": "No imported record summaries are available for this run.",
  "web.ImportJobDetailPanel.progressTimeline": "Progress timeline",
  "web.ImportJobDetailPanel.phases": "phases",
  "web.ImportJobDetailPanel.importControlsAndSource": "Import controls and source",
  "web.ImportJobDetailPanel.importRunDetails": "Import run details",
  "web.ImportJobDetailPanel.method": "Method",
  "web.ImportJobDetailPanel.howStuffStashReadTheSource": "How Stuff Stash read the source",
  "web.ImportJobDetailPanel.selectedSourceOptions": "Selected source options",
  "web.ImportJobDetailPanel.importActions": "Import actions",
  "web.ImportJobDetailPanel.cancel": "Cancel",
  "web.ImportJobDetailPanel.continueImport": "Continue import",
  "web.ImportJobDetailPanel.more": "More",
  "web.ImportJobDetailPanel.moreImportActions": "More import actions",
  "web.ImportJobDetailPanel.openInventoryActivity": "Open inventory activity",
  "web.ImportJobDetailPanel.showsTheFullInventoryActivityLog": "Shows the full inventory activity log.",
  "web.ImportJobDetailPanel.removeFromHistory": "Remove from history",
  "web.ImportJobDetailPanel.importedRecordsAndAuditHistoryRemain": "Imported records and audit history remain.",
  "web.ImportJobHistory.newImport": "New import",
  "web.ImportJobHistory.importHistoryFilters": "Import history filters",
  "web.ImportJobHistory.allRuns": "All runs",
  "web.ImportJobHistory.running": "Running",
  "web.ImportJobHistory.readyToReview": "Ready to review",
  "web.ImportJobHistory.actionRequired": "Action required",
  "web.ImportJobHistory.warnings": "Warnings",
  "web.ImportJobHistory.completed": "Completed",
  "web.ImportJobHistory.noImportRunsYet": "No import runs yet",
  "web.ImportJobHistory.startWithHomeboxPreviewWhatStuffStashWillCreate": "Start with Homebox, preview what Stuff Stash will create, then run it in the background.",
  "web.ImportJobHistory.creatingImportsRequiresImportJobCreateAccess": "Creating imports requires import job create access.",
  "web.ImportJobHistory.currentWork": "Current work",
  "web.ImportJobHistory.resumeDraftsWatchProgressOrCancelRunningImports": "Resume drafts, watch progress, or cancel running imports.",
  "web.ImportJobHistory.details": "Details",
  "web.ImportJobHistory.cancel": "Cancel",
  "web.ImportJobHistory.continue": "Continue",
  "web.ImportJobHistory.showOnlyThose": "Show only those",
  "web.ImportJobHistory.runs": "Runs",
  "web.ImportJobHistory.showAll": "Show all",
  "web.ImportJobHistory.importHistory": "Import history",
  "web.ImportJobHistory.source": "Source",
  "web.ImportJobHistory.status": "Status",
  "web.ImportJobHistory.changed": "Changed",
  "web.ImportJobHistory.finished": "Finished",
  "web.ImportJobHistory.actions": "Actions",
  "web.ImportJobHistory.partialProgressKept": "· partial progress kept",
  "web.ImportJobHistory.partialProgressDiscarded": "· partial progress discarded",
  "web.ImportJobHistory.noCompletedImportRunsYet": "No completed import runs yet.",
  "web.ImportJobRunHandoff.viewInHistory": "View in history",
  "web.ImportMessagesList.groups": "Groups",
  "web.ImportMessagesList.affected": "Affected",
  "web.ImportMessagesList.blocking": "Blocking",
  "web.ImportMessagesList.warnings": "Warnings",
  "web.ImportMessagesList.explain": "Explain",
  "web.ImportMessagesList.show": "Show",
  "web.ImportMessagesList.showFewerInThisGroup": "Show fewer in this group",
  "web.ImportMessagesList.moreIssue": "more issue",
  "web.ImportMessagesList.showFewer": "Show fewer",
  "web.ImportMessagesList.showMoreIssues": "Show more issues",
  "web.ImportMessagesList.allIssueGroupsAreShown": "All issue groups are shown.",
  "web.ImportMessagesList.closeIssueDetails": "Close issue details",
  "web.ImportMessagesList.meaning": "Meaning",
  "web.ImportMessagesList.impact": "Impact",
  "web.ImportMessagesList.nextAction": "Next action",
  "web.ImportMessagesList.affectedRecords": "Affected records",
  "web.ImportMessagesList.moreAffected": "more affected",
  "web.ImportPreviewPanel.previewImport": "Preview import",
  "web.ImportPreviewPanel.reviewThePlanBeforeStartingTheBackgroundImport": "Review the plan before starting the background import.",
  "web.ImportPreviewPanel.selectedSourceOptions": "Selected source options",
  "web.ImportPreviewPanel.previewIssues": "Preview issues",
  "web.ImportPreviewPanel.issues": "Issues",
  "web.ImportPreviewPanel.planPreview": "Plan preview",
  "web.ImportPreviewPanel.plannedRecordsBySection": "Planned records by section",
  "web.ImportPreviewPanel.startBackgroundImport": "Start background import",
  "web.ImportPreviewPanel.back": "Back",
  "web.ImportPreviewSamples.partialList": "Partial list",
  "web.ImportPreviewSamples.page": "Page",
  "web.ImportPreviewSamples.fields": "Fields",
  "web.ImportPreviewSamples.field": "Field",
  "web.ImportPreviewSamples.key": "Key",
  "web.ImportPreviewSamples.type": "Type",
  "web.ImportPreviewSamples.tags": "Tags",
  "web.ImportPreviewSamples.tag": "Tag",
  "web.ImportPreviewSamples.color": "Color",
  "web.ImportPreviewSamples.locations": "Locations",
  "web.ImportPreviewSamples.location": "Location",
  "web.ImportPreviewSamples.kind": "Kind",
  "web.ImportPreviewSamples.context": "Context",
  "web.ImportPreviewSamples.assets": "Assets",
  "web.ImportPreviewSamples.asset": "Asset",
  "web.ImportPreviewSamples.photosFiles": "Photos/files",
  "web.ImportPreviewSamples.file": "File",
  "web.ImportPreviewSamples.size": "Size",
  "web.ImportSourceChoiceStep.chooseImportMethod": "Choose import method",
  "web.ImportSourceChoiceStep.pickThePathThatMatchesTheDataYouHave": "Pick the path that matches the data you have right now.",
  "web.ImportSourceChoiceStep.homeboxImportMethod": "Homebox import method",
  "web.ImportSourceChoiceStep.connectToHomebox": "Connect to Homebox",
  "web.ImportSourceChoiceStep.useYourHomeboxURLAndCredentialsBestWhenThe": "Use your Homebox URL and credentials. Best when the instance is reachable and you want photos from the live API.",
  "web.ImportSourceChoiceStep.canIncludePhotosChecksTheSourceBeforeRunning": "Can include photos · checks the source before running",
  "web.ImportSourceChoiceStep.uploadHomeboxCSV": "Upload Homebox CSV",
  "web.ImportSourceChoiceStep.useAnExportedCSVFileBestForOfflineImports": "Use an exported CSV file. Best for offline imports, migrations from an older instance, or when the Homebox API is not reachable.",
  "web.ImportSourceChoiceStep.noPhotosInCSVWorksWithoutALiveServer": "No photos in CSV · works without a live server",
  "web.ImportSourceSetup.stuffStashWillVerifyTheSourceAndBuildA": "Stuff Stash will verify the source and build a preview.",
  "web.ImportSourceSetup.homeboxURL": "Homebox URL",
  "web.ImportSourceSetup.homeboxExampleComOrHttpHomeboxLocal3100": "homebox.example.com or http://homebox.local:3100",
  "web.ImportSourceSetup.explicitHttpAndHttpsURLsArePreservedSchemelessHosts": "Explicit http:// and https:// URLs are preserved. Schemeless hosts try https:// first.",
  "web.ImportSourceSetup.email": "Email",
  "web.ImportSourceSetup.password": "Password",
  "web.ImportSourceSetup.importPhotosWhenHomeboxProvidesThem": "Import photos when Homebox provides them",
  "web.ImportSourceSetup.connectionOptions": "Connection options",
  "web.ImportSourceSetup.allowPrivateNetworkHomeboxURL": "Allow private-network Homebox URL",
  "web.ImportSourceSetup.allowSelfSignedTLSCertificate": "Allow self-signed TLS certificate",
  "web.ImportSourceSetup.connectionSummary": "Connection summary",
  "web.ImportSourceSetup.liveHomeboxAPI": "Live Homebox API",
  "web.ImportSourceSetup.credentialsAreEncryptedForPreviewAndImport": "Credentials are encrypted for preview and import",
  "web.ImportSourceSetup.homeboxCSVExport": "Homebox CSV export",
  "web.ImportSourceSetup.kBPhotosAreNotIncludedInCSVExports": "KB · photos are not included in CSV exports",
  "web.ImportSourceSetup.cSVFilesMustBe10MiBOrSmallerHomebox": "CSV files must be 10 MiB or smaller. Homebox CSV exports do not include photos.",
  "web.ImportSourceSetup.cSVImportSummary": "CSV import summary",
  "web.ImportSourceSetup.cSVSnapshot": "CSV snapshot",
  "web.ImportSourceSetup.photosUnavailable": "Photos unavailable",
  "web.ImportSourceSetup.back": "Back",
  "web.InventoryAccessManager.sharing": "Sharing",
  "web.InventoryAccessManager.oneTimeInvitationLink": "One-time invitation link",
  "web.InventoryAccessManager.invitationLink": "Invitation link",
  "web.InventoryAccessManager.thisLinkCannotBeShownAgainAfterYouLeave": "This link cannot be shown again after you leave this page.",
  "web.InventoryAccessManager.copyLink": "Copy link",
  "web.InventoryAccessManager.shareInvitation": "Share invitation",
  "web.InventoryAccessManager.emailAddress": "Email address",
  "web.InventoryAccessManager.personExampleCom": "person@example.com",
  "web.InventoryAccessManager.accessLevel": "Access level",
  "web.InventoryAccessManager.invitationAccessLevel": "Invitation access level",
  "web.InventoryAccessManager.createInvite": "Create invite",
  "web.InventoryAccessManager.advancedAccountGrants": "Advanced account grants",
  "web.InventoryAccessManager.useTheAccountIDSuppliedByYourIdentityProvider": "Use the account ID supplied by your identity provider or administrator.",
  "web.InventoryAccessManager.accountID": "Account ID",
  "web.InventoryAccessManager.accountId": "account-id",
  "web.InventoryAccessManager.directGrantAccessLevel": "Direct grant access level",
  "web.InventoryAccessManager.grantAccess": "Grant access",
  "web.InventoryAccessManager.directGrants": "Direct grants",
  "web.InventoryAccessManager.revoke": "Revoke",
  "web.InventoryAccessManager.loadMoreGrants": "Load more grants",
  "web.InventoryAccessManager.invitations": "Invitations",
  "web.InventoryAccessManager.invitationStatus": "Invitation status",
  "web.InventoryAccessManager.loadMoreInvitations": "Load more invitations",
  "web.InventoryAccessManager.revokeAccess": "Revoke access",
  "web.InventoryAccessManager.cancel": "Cancel",
  "web.InventoryAccessManager.stuffStashInvitation": "Stuff Stash invitation",
  "web.InventoryAuditPanel.activity": "Activity",
  "web.InventoryAuditPanel.auditHistoryForAuthorizedTenantAndInventoryActivity": "Audit history for authorized tenant and inventory activity.",
  "web.InventoryAuditPanel.auditScope": "Audit scope",
  "web.InventoryAuditPanel.auditRecords": "Audit records",
  "web.InventoryAuditPanel.technicalDetails": "Technical details",
  "web.InventoryAuditPanel.showMoreActivity": "Show more activity",
  "web.InventoryAuditPanel.loadOlderActivity": "Load older activity",
  "web.InventoryConversationPanel.askStuffStash": "Ask Stuff Stash",
  "web.InventoryConversationPanel.conversation": "Conversation",
  "web.InventoryConversationPanel.findSomethingAskWhatSStoredHereOrDescribe": "Find something, ask what’s stored here, or describe a change.",
  "web.InventoryConversationPanel.reviewChanges": "Review changes",
  "web.InventoryConversationPanel.expires": "Expires",
  "web.InventoryConversationPanel.removeExpirationDate": "Remove expiration date",
  "web.InventoryConversationPanel.destination": "Destination:",
  "web.InventoryConversationPanel.approveChanges": "Approve changes",
  "web.InventoryConversationPanel.cancelChanges": "Cancel changes",
  "web.InventoryConversationPanel.refreshInventory": "Refresh inventory",
  "web.InventoryConversationPanel.messageStuffStash": "Message Stuff Stash",
  "web.InventoryConversationPanel.stop": "Stop",
  "web.InventoryConversationPanel.send": "Send",
  "web.InventoryCustomizationManager.customFields": "Custom fields",
  "web.InventoryCustomizationManager.typesAndFieldsAvailableToThisInventory": "Types and fields available to this inventory.",
  "web.InventoryCustomizationManager.assetTypes": "Asset types",
  "web.InventoryCustomizationManager.customTypeScope": "Custom type scope",
  "web.InventoryCustomizationManager.key": "Key",
  "web.InventoryCustomizationManager.medicine": "medicine",
  "web.InventoryCustomizationManager.displayName": "Display name",
  "web.InventoryCustomizationManager.medicine2": "Medicine",
  "web.InventoryCustomizationManager.description": "Description",
  "web.InventoryCustomizationManager.optional": "Optional",
  "web.InventoryCustomizationManager.createType": "Create type",
  "web.InventoryCustomizationManager.customAssetTypes": "Custom asset types",
  "web.InventoryCustomizationManager.noCustomAssetTypesYet": "No custom asset types yet.",
  "web.InventoryCustomizationManager.fieldDefinitions": "Field definitions",
  "web.InventoryCustomizationManager.customFieldScope": "Custom field scope",
  "web.InventoryCustomizationManager.expirationDate": "expiration-date",
  "web.InventoryCustomizationManager.expirationDate2": "Expiration date",
  "web.InventoryCustomizationManager.customFieldType": "Custom field type",
  "web.InventoryCustomizationManager.options": "Options",
  "web.InventoryCustomizationManager.newOpenClosed": "new, open, closed",
  "web.InventoryCustomizationManager.fieldApplicability": "Field applicability",
  "web.InventoryCustomizationManager.fieldCustomTypeTargets": "Field custom type targets",
  "web.InventoryCustomizationManager.noEligibleCustomAssetTypesForThisScope": "No eligible custom asset types for this scope.",
  "web.InventoryCustomizationManager.createField": "Create field",
  "web.InventoryCustomizationManager.customFieldDefinitions": "Custom field definitions",
  "web.InventoryCustomizationManager.noCustomFieldsYet": "No custom fields yet.",
  "web.InventoryImportWorkspace.refresh": "Refresh",
  "web.InventoryImportWorkspace.backToHistory": "Back to history",
  "web.InventoryImportWorkspace.importAccessNeeded": "Import access needed",
  "web.InventoryImportWorkspace.youCanViewThisInventoryButImportingRecordsRequires": "You can view this inventory, but importing records requires import job access.",
  "web.InventorySettings.settingsSections": "Settings sections",
  "web.InventorySettings.returnToOverviewAccessFieldsOrActivityToManage": "Return to Overview, Access, Fields, or Activity to manage this inventory.",
  "web.InventorySettings.administration": "Administration",
  "web.InventorySettings.noWebAdministrationActionsAreAvailable": "No web administration actions are available",
  "web.InventoryWorkspaceApp.stuffStash": "Stuff Stash",
  "web.InventoryWorkspaceApp.openInventory": "Open inventory",
  "web.InventoryWorkspaceApp.viewArchived": "View archived",
  "web.InventoryWorkspaceApp.undo": "Undo",
  "web.InventoryWorkspaceApp.viewLocation": "View location",
  "web.InventoryWorkspaceApp.viewAsset": "View asset",
  "web.InventoryWorkspaceApp.viewHome": "View home",
  "web.InventoryWorkspaceApp.viewParent": "View parent",
  "web.InventoryWorkspaceRouteContent.loadingAssetDetails": "Loading asset details",
  "web.InventoryWorkspaceRouteContent.gettingTheLatestDetailsAndFiles": "Getting the latest details and files.",
  "web.InventoryWorkspaceRouteContent.loadingImports": "Loading imports…",
  "web.InventoryWorkspaceRouteContent.loadingSettings": "Loading settings…",
  "web.LocationView.back": "Back",
  "web.LocationView.location": "Location",
  "web.LocationView.placeMaintenance": "Place maintenance",
  "web.LocationView.editLocation": "Edit location",
  "web.LocationView.movePlace": "Move place",
  "web.LocationView.archive": "Archive",
  "web.MobileNav.mobileNavigation": "Mobile navigation",
  "web.MobileNav.addAsset": "Add asset",
  "web.NotificationBell.notifications": "Notifications",
  "web.NotificationBell.expirationRemindersForThisInventory": "Expiration reminders for this inventory",
  "web.NotificationBell.theUnreadCountCouldNotBeUpdated": "The unread count could not be updated.",
  "web.NotificationBell.retryUnreadCount": "Retry unread count",
  "web.NotificationInbox.notificationInbox": "Notification inbox",
  "web.NotificationInbox.notificationFilter": "Notification filter",
  "web.NotificationInbox.markAllRead": "Mark all read",
  "web.NotificationInbox.refresh": "Refresh",
  "web.NotificationInbox.notificationSettings": "Notification settings",
  "web.NotificationInbox.loadingNotifications": "Loading notifications…",
  "web.NotificationInbox.retryNotifications": "Retry notifications",
  "web.NotificationInbox.opening": "Opening…",
  "web.NotificationInbox.unread": "Unread",
  "web.ParentTargetPicker.currentDestination": "Current destination",
  "web.ParentTargetPicker.clearParentSelection": "Clear parent selection",
  "web.ParentTargetPicker.clearParent": "Clear parent",
  "web.ParentTargetPicker.locations": "Locations",
  "web.ParentTargetPicker.containers": "Containers",
  "web.ParentTargetPicker.showAll": "Show all",
  "web.ParentTargetPicker.suggestedDestinations": "Suggested destinations",
  "web.SearchSuggestions.photoUnavailable": "Photo unavailable",
  "web.SideNav.workspaceNavigation": "Workspace navigation",
  "web.SideNav.stuffStash": "Stuff Stash",
  "web.SideNav.inventoryDestinations": "Inventory destinations",
  "web.TopHeader.searchThisInventory": "Search this inventory",
  "web.TopHeader.runSearch": "Run search",
  "web.TopHeader.currentInventory": "Current inventory",
  "web.WorkspaceAddMenu.add": "Add",
  "web.WorkspaceAddMenu.addAssetKind": "Add asset kind",
  "web.WorkspaceContextSwitcher.tenantName": "Tenant name",
  "web.WorkspaceContextSwitcher.inventoryName": "Inventory name",
  "web.WorkspaceContextSwitcher.cancel": "Cancel",
  "web.WorkspaceContextSwitcher.tenants": "Tenants",
  "web.WorkspaceContextSwitcher.newTenant": "New tenant",
  "web.WorkspaceContextSwitcher.inventories": "Inventories",
  "web.WorkspaceContextSwitcher.newInventory": "New inventory",
  "web.WorkspaceContextSwitcher.inventoryContext": "Inventory context",
  "web.WorkspaceContextSwitcher.chooseTheTenantAndInventoryToUse": "Choose the tenant and inventory to use.",
  "web.WorkspaceSetupPanel.tenantName": "Tenant name",
  "web.WorkspaceSetupPanel.inventoryName": "Inventory name",
  "web.WorkspaceConfirmationDialog.working": "Working…",
  "web.WorkspaceConfirmationDialogHarness.deleteAsset": "Delete asset",
  "web.WorkspaceConfirmationDialogHarness.deleteItPermanently": "Delete it permanently?",
  "web.WorkspaceConfirmationDialogHarness.cancel": "Cancel",
  "web.WorkspaceConfirmationDialogHarness.delete": "Delete",
  "web.WorkspaceTaskSheet.savingChanges": "Saving changes…",
  "web.WorkspaceTaskSheetHarness.editAsset": "Edit asset",
  "web.WorkspaceTaskSheetHarness.changeTheAssetDetails": "Change the asset details.",
  "web.WorkspaceTaskSheetHarness.name": "Name",
  "web.WorkspaceTaskSheetHarness.save": "Save",
  "web.ExpirationBrowseEntry.browseExpirationDates": "Browse expiration dates",
  "web.ExpirationBrowseEntry.expirationActiveItems": "Expiration · Active items",
  "web.ExpirationFilters.expirationFilters": "Expiration filters",
  "web.ExpirationFilters.filterRecordedDatesInThisInventoryMonthOnlyDates": "Filter recorded dates in this inventory. Month-only dates are compared at the end of the month.",
  "web.ExpirationFilters.loadingFilterChoices": "Loading filter choices…",
  "web.ExpirationFilters.retryChoices": "Retry choices",
  "web.ExpirationFilters.kind": "Kind",
  "web.ExpirationFilters.availability": "Availability",
  "web.ExpirationFilters.type": "Type",
  "web.ExpirationFilters.location": "Location",
  "web.ExpirationFilters.tagsMatchAllSelected": "Tags · match all selected",
  "web.ExpirationFilters.noTagsInThisInventory": "No tags in this inventory.",
  "web.ExpirationFilters.from": "From",
  "web.ExpirationFilters.through": "Through",
  "web.ExpirationFilters.throughMustBeOnOrAfterFrom": "Through must be on or after From.",
  "web.ExpirationFilters.clearFilters": "Clear filters",
  "web.ExpirationFilters.cancel": "Cancel",
  "web.ExpirationFilters.applyFilters": "Apply filters",
  "web.ExpirationHome.expiration": "Expiration",
  "web.ExpirationHome.seeAll": "See all",
  "web.ExpirationHome.retryExpiration": "Retry expiration",
  "web.ExpirationHome.loadingExpiration": "Loading expiration…",
  "web.ExpirationHome.expired": "Expired ·",
  "web.ExpirationHome.expiringSoon": "Expiring soon ·",
  "web.ExpirationHome.noneExpiringSoon": "None expiring soon",
  "web.ExpirationWorkspace.expiration": "Expiration",
  "web.ExpirationWorkspace.reviewDatesForActiveItemsAcrossYourInventory": "Review dates for active items across your inventory.",
  "web.ExpirationWorkspace.refresh": "Refresh",
  "web.ExpirationWorkspace.expirationStatus": "Expiration status",
  "web.ExpirationWorkspace.searchItemNamesAndDescriptions": "Search item names and descriptions",
  "web.ExpirationWorkspace.searchNamesAndDescriptions": "Search names and descriptions",
  "web.ExpirationWorkspace.search": "Search",
  "web.ExpirationWorkspace.filters": "Filters",
  "web.ExpirationWorkspace.filtersApplied": "Filters applied",
  "web.ExpirationWorkspace.clearFilters": "Clear filters",
  "web.ExpirationWorkspace.retry": "Retry",
  "web.ExpirationWorkspace.loadingExpirationDates": "Loading expiration dates…",
  "web.ExpirationWorkspace.expirationIsUnavailableInThisSession": "Expiration is unavailable in this session.",
  "web.AssetTypeSettingsManager.assetTypes": "Asset types",
  "web.AssetTypeSettingsManager.addAssetType": "Add Asset Type",
  "web.AssetTypeSettingsManager.assetTypeLifecycle": "Asset type lifecycle",
  "web.AssetTypeSettingsManager.active": "Active",
  "web.AssetTypeSettingsManager.archived": "Archived",
  "web.AssetTypeSettingsManager.gettingTheCurrentSchema": "Getting the current schema.",
  "web.AssetTypeSettingsManager.updatingAssetTypes": "Updating asset types",
  "web.AssetTypeSettingsManager.showingTheLastLoadedRowsWhileThisViewRefreshes": "Showing the last loaded rows while this view refreshes.",
  "web.AssetTypeSettingsManager.assetTypesUnavailable": "Asset types unavailable",
  "web.AssetTypeSettingsManager.searchAssetTypes": "Search asset types",
  "web.AssetTypeSettingsManager.inherited": "Inherited",
  "web.AssetTypeSettingsManager.couldNotLoadMore": "Could not load more",
  "web.AssetTypeSettingsManager.moreAssetTypesAreAvailable": "More asset types are available.",
  "web.AssetTypeSettingsManager.readOnly": "Read only",
  "web.AssetTypeSettingsManager.thisAccountCanViewAssetTypesButCannotChange": "This account can view asset types but cannot change them here.",
  "web.AssetTypeSettingsManager.assetTypeUnavailable": "Asset type unavailable",
  "web.AssetTypeSettingsManager.thisRecordMayBeInheritedArchivedOrNoLonger": "This record may be inherited, archived, or no longer available.",
  "web.AssetTypeSettingsManager.displayName": "Display name",
  "web.AssetTypeSettingsManager.stableKey": "Stable key",
  "web.AssetTypeSettingsManager.theKeyCannotChangeAfterCreation": "The key cannot change after creation.",
  "web.AssetTypeSettingsManager.trackExpirationDates": "Track expiration dates",
  "web.AssetTypeSettingsManager.eachAssetCanHaveItsOwnOptionalExpirationDate": "Each asset can have its own optional expiration date. Turning this off keeps existing dates.",
  "web.AssetTypeSettingsManager.descriptionOptional": "Description (optional)",
  "web.AssetTypeSettingsManager.cancel": "Cancel",
  "web.AssetTypeSettingsManager.archive": "Archive",
  "web.AssetTypeSettingsManager.save": "Save",
  "web.AssetTypeSettingsManager.discardChanges": "Discard changes?",
  "web.AssetTypeSettingsManager.yourUnsavedAssetTypeChangesWillBeLost": "Your unsaved asset type changes will be lost.",
  "web.AssetTypeSettingsManager.keepEditing": "Keep editing",
  "web.AssetTypeSettingsManager.discardChanges2": "Discard changes",
  "web.AssetTypeSettingsManager.thisRecordMayNoLongerExistOrMayNot": "This record may no longer exist or may not be visible to this account.",
  "web.AssetTypeSettingsManager.description": "Description",
  "web.AssetTypeSettingsManager.expirationTracking": "Expiration tracking",
  "web.AssetTypeSettingsManager.ownership": "Ownership",
  "web.AssetTypeSettingsManager.done": "Done",
  "web.AssetTypeSettingsManager.manageIn": "Manage in",
  "web.AssetTypeSettingsManager.deletePermanently": "Delete permanently",
  "web.AssetTypeSettingsManager.restore": "Restore",
  "web.ExpirationReminderEditor.expirationReminders": "Expiration reminders",
  "web.ExpirationReminderEditor.reminderPolicy": "Reminder policy",
  "web.ExpirationReminderEditor.defaultReminders": "Default reminders",
  "web.ExpirationReminderEditor.typesWithCustomRemindersCanOverrideTheseDefaults": "Types with custom reminders can override these defaults.",
  "web.ExpirationReminderEditor.beforeExpiration": "Before expiration",
  "web.ExpirationReminderEditor.notifyBeforeExpiration": "Notify before expiration",
  "web.ExpirationReminderEditor.daysBeforeExpiration": "Days before expiration",
  "web.ExpirationReminderEditor.whenExpired": "When expired",
  "web.ExpirationReminderEditor.remindersSaved": "Reminders saved.",
  "web.ExpirationReminderEditor.discardChanges": "Discard changes",
  "web.FieldSettingsManager.customFields": "Custom fields",
  "web.FieldSettingsManager.addField": "Add Field",
  "web.FieldSettingsManager.customFieldLifecycle": "Custom field lifecycle",
  "web.FieldSettingsManager.active": "Active",
  "web.FieldSettingsManager.archived": "Archived",
  "web.FieldSettingsManager.gettingTheCurrentSchema": "Getting the current schema.",
  "web.FieldSettingsManager.updatingCustomFields": "Updating custom fields",
  "web.FieldSettingsManager.showingTheLastLoadedRowsWhileThisViewRefreshes": "Showing the last loaded rows while this view refreshes.",
  "web.FieldSettingsManager.customFieldsUnavailable": "Custom fields unavailable",
  "web.FieldSettingsManager.searchLoadedCustomFields": "Search loaded custom fields",
  "web.FieldSettingsManager.searchLoadedFields": "Search loaded fields",
  "web.FieldSettingsManager.inherited": "Inherited",
  "web.FieldSettingsManager.couldNotLoadMore": "Could not load more",
  "web.FieldSettingsManager.moreCustomFieldsAreAvailable": "More custom fields are available.",
  "web.FieldSettingsManager.readOnly": "Read only",
  "web.FieldSettingsManager.yourDraftIsPreservedButThisAccountCanNo": "Your draft is preserved, but this account can no longer change custom fields here.",
  "web.FieldSettingsManager.fieldUnavailable": "Field unavailable",
  "web.FieldSettingsManager.thisFieldMayBeInheritedArchivedOrNoLonger": "This field may be inherited, archived, or no longer available.",
  "web.FieldSettingsManager.displayName": "Display name",
  "web.FieldSettingsManager.stableKey": "Stable key",
  "web.FieldSettingsManager.theKeyCannotChangeAfterCreation": "The key cannot change after creation.",
  "web.FieldSettingsManager.fieldType": "Field type",
  "web.FieldSettingsManager.type": "Type",
  "web.FieldSettingsManager.existingOptions": "Existing options",
  "web.FieldSettingsManager.newOpenClosed": "new, open, closed",
  "web.FieldSettingsManager.appliesTo": "Applies to",
  "web.FieldSettingsManager.fieldApplicability": "Field applicability",
  "web.FieldSettingsManager.assetTypes": "Asset types",
  "web.FieldSettingsManager.fieldAssetTypeTargets": "Field asset type targets",
  "web.FieldSettingsManager.noEligibleActiveAssetTypes": "No eligible active asset types.",
  "web.FieldSettingsManager.cancel": "Cancel",
  "web.FieldSettingsManager.archive": "Archive",
  "web.FieldSettingsManager.save": "Save",
  "web.FieldSettingsManager.discardChanges": "Discard changes?",
  "web.FieldSettingsManager.yourUnsavedCustomFieldChangesWillBeLost": "Your unsaved custom field changes will be lost.",
  "web.FieldSettingsManager.keepEditing": "Keep editing",
  "web.FieldSettingsManager.discardChanges2": "Discard changes",
  "web.FieldSettingsManager.thisRecordMayNoLongerExistOrMayNot": "This record may no longer exist or may not be visible to this account.",
  "web.FieldSettingsManager.ownership": "Ownership",
  "web.FieldSettingsManager.done": "Done",
  "web.FieldSettingsManager.manageIn": "Manage in",
  "web.FieldSettingsManager.deletePermanently": "Delete permanently",
  "web.FieldSettingsManager.restore": "Restore",
  "web.InventoryExportAction.exportInventory": "Export inventory",
  "web.InventoryExportAction.downloadThisInventoryIncludingArchivedItemsJSONIncludesField": "Download this inventory, including archived items. JSON includes field definitions; CSV opens in a spreadsheet. Photo and file contents are not included.",
  "web.InventoryExportAction.jSONCompleteInventoryData": "JSON — complete inventory data",
  "web.InventoryExportAction.cSVSpreadsheetRows": "CSV — spreadsheet rows",
  "web.InventoryExportAction.retryExport": "Retry export",
  "web.NotificationSettings.expirationReminders": "Expiration reminders",
  "web.NotificationSettings.yourRemindersForThisInventoryOtherMembersHaveTheir": "Your reminders for this inventory. Other members have their own settings.",
  "web.NotificationSettings.loadingReminders": "Loading reminders…",
  "web.NotificationSettings.retryLoadingReminders": "Retry loading reminders",
  "web.NotificationSettings.refreshSavedSettings": "Refresh saved settings",
  "web.NotificationSettings.personalNotificationSettings": "Personal notification settings",
  "web.NotificationSettings.inventoryDefaults": "Inventory defaults",
  "web.NotificationSettings.timeZone": "Time zone ·",
  "web.NotificationSettings.timezone": "Timezone",
  "web.NotificationSettings.searchCityOrTimeZone": "Search city or time zone",
  "web.NotificationSettings.saveTimezone": "Save timezone",
  "web.NotificationSettings.timezoneSaved": "Timezone saved.",
  "web.NotificationSettings.assetTypeReminders": "Asset type reminders",
  "web.NotificationSettings.enableExpirationTrackingOnAnAssetTypeToCustomize": "Enable expiration tracking on an asset type to customize its reminders here.",
  "web.NotificationSettings.setUpPushNotificationsInTheMobileAppYour": "Set up push notifications in the mobile app. Your inbox is available on web and mobile.",
  "web.SettingsCollectionState.tryAgain": "Try again",
  "web.SettingsWorkspace.settings": "Settings",
  "web.SettingsWorkspace.chooseWhatYouWantToConfigure": "Choose what you want to configure.",
  "web.SettingsWorkspace.settingsLevels": "Settings levels",
  "web.SettingsWorkspace.accountAndApp": "Account and app",
  "web.SettingsWorkspace.account": "Account",
  "web.SettingsWorkspace.profileEditing": "Profile editing",
  "web.SettingsWorkspace.notAvailable": "Not available",
  "web.SettingsWorkspace.app": "App",
  "web.SettingsWorkspace.stuffStashWeb": "Stuff Stash web",
  "web.SettingsWorkspace.settingsUnavailable": "Settings unavailable",
  "web.SettingsWorkspace.theSelectedSettingsContextIsNotAvailableToThis": "The selected settings context is not available to this account.",
  "web.SettingsWorkspace.backToSettings": "Back to Settings",
  "web.SettingsWorkspace.belongsTo": "belongs to",
  "web.SettingsWorkspace.settingsSharedWithThisTenantSInventories": "Settings shared with this tenant’s inventories.",
  "web.SettingsWorkspace.sectionUnavailable": "Section unavailable",
  "web.SettingsWorkspace.thisSettingsSectionIsNotAvailableInTheSelected": "This settings section is not available in the selected context.",
  "web.TagSettingsManager.tags": "Tags",
  "web.TagSettingsManager.reusableLabelsForThisInventory": "Reusable labels for this inventory.",
  "web.TagSettingsManager.addTag": "Add Tag",
  "web.TagSettingsManager.loadingTags": "Loading tags",
  "web.TagSettingsManager.gettingTheCurrentTagList": "Getting the current tag list.",
  "web.TagSettingsManager.updatingTags": "Updating tags",
  "web.TagSettingsManager.showingTheLastLoadedTagsWhileThisListRefreshes": "Showing the last loaded tags while this list refreshes.",
  "web.TagSettingsManager.tagsUnavailable": "Tags unavailable",
  "web.TagSettingsManager.searchTags": "Search tags",
  "web.TagSettingsManager.activeTags": "Active tags",
  "web.TagSettingsManager.couldNotLoadMore": "Could not load more",
  "web.TagSettingsManager.moreTagsAreAvailable": "More tags are available.",
  "web.TagSettingsManager.tagsBelongOnlyToThisInventory": "Tags belong only to this inventory.",
  "web.TagSettingsManager.readOnly": "Read only",
  "web.TagSettingsManager.yourDraftIsPreservedButThisAccountCanNo": "Your draft is preserved, but this account can no longer change tags here.",
  "web.TagSettingsManager.tagUnavailable": "Tag unavailable",
  "web.TagSettingsManager.thisTagMayHaveBeenArchivedOrIsNo": "This tag may have been archived or is no longer available.",
  "web.TagSettingsManager.displayName": "Display name",
  "web.TagSettingsManager.color": "Color",
  "web.TagSettingsManager.chooseACustomColor": "Choose a custom color",
  "web.TagSettingsManager.clearColor": "Clear color",
  "web.TagSettingsManager.hexColorOptional": "Hex color (optional)",
  "web.TagSettingsManager.2F80ED": "#2F80ED",
  "web.TagSettingsManager.leaveBlankForNoColor": "Leave blank for no color.",
  "web.TagSettingsManager.cancel": "Cancel",
  "web.TagSettingsManager.archive": "Archive",
  "web.TagSettingsManager.save": "Save",
  "web.TagSettingsManager.discardChanges": "Discard changes?",
  "web.TagSettingsManager.yourUnsavedTagChangesWillBeLost": "Your unsaved tag changes will be lost.",
  "web.TagSettingsManager.keepEditing": "Keep editing",
  "web.TagSettingsManager.discardChanges2": "Discard changes",
  "web.TagSettingsManager.archiveTag": "Archive tag",
  "web.CaseEditor.testCase": "Test case",
  "web.CaseEditor.describeARealisticRequestATestInventoryAndWhat": "Describe a realistic request, a test inventory and what a good response should do. This case evaluates text interactions.",
  "web.CaseEditor.checkTheseDetails": "Check these details",
  "web.CaseEditor.caseTitle": "Case title",
  "web.CaseEditor.whatTheUserSays": "What the user says",
  "web.CaseEditor.loadLatestToCompare": "Load latest to compare",
  "web.CaseEditor.theServerRejectedThisCaseCheckItsFixtureAnd": "The server rejected this case. Check its fixture and expectation limits.",
  "web.CaseExpectations.expectedResult": "Expected result",
  "web.CaseExpectations.theConversationShould": "The conversation should",
  "web.CaseExpectations.mustReferToTheseFixtures": "Must refer to these fixtures",
  "web.CaseExpectations.addFixturesToRequireSpecificItemsInTheAnswer": "Add fixtures to require specific items in the answer.",
  "web.CaseExpectations.expectedLocations": "Expected locations",
  "web.CaseExpectations.item": "Item",
  "web.CaseExpectations.mustBeInside": "Must be inside",
  "web.CaseExpectations.removeLocationExpectation": "Remove location expectation",
  "web.CaseExpectations.addExpectedLocation": "Add expected location",
  "web.CaseExpectations.expectedProposedChanges": "Expected proposed changes",
  "web.CaseExpectations.removeTheseChangesOrChooseProposeAChangeBefore": "Remove these changes or choose “Propose a change” before saving.",
  "web.CaseExpectations.change": "Change",
  "web.CaseExpectations.newItemName": "New item name",
  "web.CaseExpectations.newItemKind": "New item kind",
  "web.CaseExpectations.existingItem": "Existing item",
  "web.CaseExpectations.destination": "Destination",
  "web.CaseExpectations.expectedDetails": "Expected details",
  "web.CaseExpectations.removeProposedChange": "Remove proposed change",
  "web.CaseExpectations.addProposedChange": "Add proposed change",
  "web.CaseExpectations.mustNeverProposeTheseChanges": "Must never propose these changes",
  "web.CaseExpectations.testRunsNeverApproveOrExecuteInventoryChanges": "Test runs never approve or execute inventory changes.",
  "web.CaseExpectations.create": "Create",
  "web.CaseExpectations.move": "Move",
  "web.CaseExpectations.archive": "Archive",
  "web.CaseExpectations.restore": "Restore",
  "web.CaseExpectations.checkOut": "Check out",
  "web.CaseExpectations.return": "Return",
  "web.CaseFixtures.testInventory": "Test inventory",
  "web.CaseFixtures.theseItemsExistOnlyInsideThisTestCaseYour": "These items exist only inside this test case. Your household inventory is unchanged.",
  "web.CaseFixtures.fixture": "Fixture",
  "web.CaseFixtures.name": "Name",
  "web.CaseFixtures.kind": "Kind",
  "web.CaseFixtures.thisFixtureContainsOthersSoItMustRemainA": "This fixture contains others, so it must remain a container or location.",
  "web.CaseFixtures.inside": "Inside",
  "web.CaseFixtures.description": "Description",
  "web.CaseFixtures.tagsOnePerLine": "Tags — one per line",
  "web.CaseFixtures.removeFixture": "Remove fixture",
  "web.CaseFixtures.changeReferencesToThisFixtureInContainmentOrExpected": "Change references to this fixture in containment or expected results before removing it.",
  "web.CaseFixtures.addTestItem": "Add test item",
  "web.CaseFixtures.aTestCaseSupportsUpTo100Fixtures": "A test case supports up to 100 fixtures.",
  "web.CaseSummary.testInventory": "Test inventory",
  "web.CaseSummary.tags": "Tags:",
  "web.CaseSummary.expectedResult": "Expected result:",
  "web.CaseSummary.mustMention": "Must mention:",
  "web.CaseSummary.isInside": "is inside",
  "web.CaseSummary.forbiddenChanges": "Forbidden changes:",
  "web.CaseWorkspace.testCasesUnavailable": "Test cases unavailable",
  "web.CaseWorkspace.youNoLongerHaveAccessToConfigureThisTenant": "You no longer have access to configure this tenant.",
  "web.CaseWorkspace.testCases": "Test cases",
  "web.CaseWorkspace.checkRealisticRequestsAgainstAControlledTestInventory": "Check realistic requests against a controlled test inventory.",
  "web.CaseWorkspace.closeEditorAndDiscardUnsavedEdits": "Close editor and discard unsaved edits",
  "web.CaseWorkspace.latestSavedCase": "Latest saved case",
  "web.CaseWorkspace.latestSavedRevision": "Latest saved revision",
  "web.CaseWorkspace.replaceMyEditsWithThisRevision": "Replace my edits with this revision",
  "web.CaseWorkspace.newTestCase": "New test case",
  "web.CaseWorkspace.loadingTestCases": "Loading test cases…",
  "web.CaseWorkspace.couldNotLoadTestCases": "Could not load test cases.",
  "web.CaseWorkspace.retryCases": "Retry cases",
  "web.CaseWorkspace.revision": "· Revision",
  "web.CaseWorkspace.noSavedTestCasesYet": "No saved test cases yet.",
  "web.CaseWorkspace.nextCases": "Next cases",
  "web.CaseWorkspace.backToFirstCases": "Back to first cases",
  "web.ConversationWorkspace.conversationSettingsUnavailable": "Conversation settings unavailable",
  "web.ConversationWorkspace.yourAccountNoLongerHasAccessToConfigureThis": "Your account no longer has access to configure this tenant.",
  "web.ConversationWorkspace.conversationSettingsSections": "Conversation settings sections",
  "web.ConversationWorkspace.workflows": "Workflows",
  "web.ConversationWorkspace.testCases": "Test cases",
  "web.ConversationWorkspace.runs": "Runs",
  "web.ConversationWorkspace.finishLoadingOrCloseTheEditorBeforeSwitchingSections": "Finish loading or close the editor before switching sections.",
  "web.RunActivation.workflowActivation": "Workflow activation",
  "web.RunActivation.useThisTestedRevision": "Use this tested revision",
  "web.RunActivation.checkingTheCurrentWorkflowSelection": "Checking the current workflow selection…",
  "web.RunActivation.couldNotCheckTheWorkflowSelection": "Could not check the workflow selection.",
  "web.RunActivation.retryActivationCheck": "Retry activation check",
  "web.RunActivation.revision": "· Revision",
  "web.RunActivation.thisRevisionIsActive": "This revision is active.",
  "web.RunActivation.checkCurrentSelection": "Check current selection",
  "web.RunActivation.everySelectedCaseMustPassInACompletedRun": "Every selected case must pass in a completed run before this revision can be activated.",
  "web.RunComparison.compareRuns": "Compare runs",
  "web.RunComparison.chooseAnEarlierRun": "Choose an earlier run",
  "web.RunComparison.loadingRuns": "Loading runs…",
  "web.RunComparison.couldNotLoadRuns": "Could not load runs.",
  "web.RunComparison.retryComparisonRuns": "Retry comparison runs",
  "web.RunComparison.passed": "passed",
  "web.RunComparison.noOtherRunsOnThisPage": "No other runs on this page.",
  "web.RunComparison.nextComparisonRuns": "Next comparison runs",
  "web.RunComparison.firstComparisonRuns": "First comparison runs",
  "web.RunComparison.loadingComparison": "Loading comparison…",
  "web.RunComparison.couldNotLoadTheSelectedRun": "Could not load the selected run.",
  "web.RunComparison.retrySelectedRun": "Retry selected run",
  "web.RunComparison.refreshSelectedRun": "Refresh selected run",
  "web.RunComparison.recordedResultsForTheSameCasesAndProviders": "Recorded results for the same cases and providers",
  "web.RunComparison.measure": "Measure",
  "web.RunComparison.selectedRun": "Selected run",
  "web.RunComparison.thisRun": "This run",
  "web.RunComparison.casesPassed": "Cases passed",
  "web.RunComparison.modelCalls": "Model calls",
  "web.RunComparison.caseExecution": "Case execution",
  "web.RunComparison.s": "s",
  "web.RunComparison.recordedCaseResultsExcludeQueueTimeAndAnyAttempts": "Recorded case results exclude queue time and any attempts that did not produce a saved result. Text-only coverage does not measure speech quality.",
  "web.RunDetails.loadingRun": "Loading run…",
  "web.RunDetails.couldNotLoadThisRun": "Could not load this run.",
  "web.RunDetails.retryRun": "Retry run",
  "web.RunDetails.evaluationRun": "Evaluation run",
  "web.RunDetails.textOnlyEvaluationThisDoesNotTestRecordingTranscription": "Text-only evaluation. This does not test recording, transcription or spoken playback.",
  "web.RunDetails.of": "of",
  "web.RunDetails.statusCouldNotBeRefreshedShowingTheLastReceived": "Status could not be refreshed. Showing the last received result.",
  "web.RunDetails.theRunCouldNotFinishCheckTheConfiguredProvider": "The run could not finish. Check the configured provider and try again.",
  "web.RunDetails.reference": "Reference:",
  "web.RunDetails.noPassingResultRecorded": "— no passing result recorded.",
  "web.RunResult.modelCalls": "model calls ·",
  "web.RunResult.loadingExpectedResult": "Loading expected result…",
  "web.RunResult.couldNotLoadTheSavedExpectations": "Could not load the saved expectations.",
  "web.RunResult.retryExpectations": "Retry expectations",
  "web.RunResult.expected": "Expected",
  "web.RunResult.observed": "Observed",
  "web.RunResult.outcome": "Outcome:",
  "web.RunResult.referencedItems": "Referenced items:",
  "web.RunResult.inside": "inside",
  "web.RunResult.executedOperations": "Executed operations:",
  "web.RunResult.differences": "Differences",
  "web.RunSetup.setUpEvaluation": "Set up evaluation",
  "web.RunSetup.setUpATestRun": "Set up a test run",
  "web.RunSetup.testYourConfiguredModelsUsingSavedCasesHouseholdInventory": "Test your configured models using saved cases. Household inventory is not changed.",
  "web.RunSetup.chooseWorkflow": "Choose workflow",
  "web.RunSetup.workflow": "Workflow",
  "web.RunSetup.loadingWorkflows": "Loading workflows…",
  "web.RunSetup.couldNotLoadWorkflows": "Could not load workflows.",
  "web.RunSetup.retryWorkflows": "Retry workflows",
  "web.RunSetup.revision": "· Revision",
  "web.RunSetup.saveAWorkflowBeforeRunningCases": "Save a workflow before running cases.",
  "web.RunSetup.nextWorkflows": "Next workflows",
  "web.RunSetup.firstWorkflows": "First workflows",
  "web.RunSetup.selected": "Selected:",
  "web.RunSetup.chooseASavedRevision": "Choose a saved revision",
  "web.RunSetup.loadingRevisions": "Loading revisions…",
  "web.RunSetup.couldNotLoadRevisions": "Could not load revisions.",
  "web.RunSetup.retryRevisions": "Retry revisions",
  "web.RunSetup.nextRevisions": "Next revisions",
  "web.RunSetup.firstRevisions": "First revisions",
  "web.RunSetup.chooseTestCases": "Choose test cases",
  "web.RunSetup.testCases": "Test cases",
  "web.RunSetup.loadingCases": "Loading cases…",
  "web.RunSetup.couldNotLoadCases": "Could not load cases.",
  "web.RunSetup.retryCases": "Retry cases",
  "web.RunSetup.saveATestCaseBeforeStartingARun": "Save a test case before starting a run.",
  "web.RunSetup.nextCases": "Next cases",
  "web.RunSetup.firstCases": "First cases",
  "web.RunSetup.selectedUpTo100": "selected (up to 100)",
  "web.RunSetup.remove": "Remove",
  "web.RunSetup.loadingSelectedWorkflow": "Loading selected workflow…",
  "web.RunSetup.couldNotLoadTheSelectedRevision": "Could not load the selected revision.",
  "web.RunSetup.retrySelectedRevision": "Retry selected revision",
  "web.RunSetup.runUsage": "Run usage",
  "web.RunSetup.perAttemptUpTo": "Per attempt, up to",
  "web.RunSetup.loadingModelChoices": "Loading model choices…",
  "web.RunSetup.couldNotLoadConfiguredModels": "Could not load configured models.",
  "web.RunSetup.retryModels": "Retry models",
  "web.RunSetup.model": "Model:",
  "web.RunSetup.textOnlyCoverageSpeechInputAndPlaybackNeedSeparate": "Text-only coverage. Speech input and playback need separate testing.",
  "web.RunWorkspace.runsUnavailable": "Runs unavailable",
  "web.RunWorkspace.youNoLongerHaveAccessToConfigureThisTenant": "You no longer have access to configure this tenant.",
  "web.RunWorkspace.runs": "Runs",
  "web.RunWorkspace.discardRunSetup": "Discard run setup",
  "web.RunWorkspace.backToRuns": "Back to runs",
  "web.RunWorkspace.newRun": "New run",
  "web.RunWorkspace.loadingRuns": "Loading runs…",
  "web.RunWorkspace.couldNotLoadRuns": "Could not load runs.",
  "web.RunWorkspace.retryRuns": "Retry runs",
  "web.RunWorkspace.cases": "cases ·",
  "web.RunWorkspace.noEvaluationRunsYetStartWithASavedWorkflow": "No evaluation runs yet. Start with a saved workflow and test case.",
  "web.RunWorkspace.nextRuns": "Next runs",
  "web.RunWorkspace.firstRuns": "First runs",
  "web.WorkflowEditor.workflowSettings": "Workflow settings",
  "web.WorkflowEditor.chooseAModelAndGiveItGuidanceForYour": "Choose a model and give it guidance for your inventory. Saving creates a draft.",
  "web.WorkflowEditor.workflowName": "Workflow name",
  "web.WorkflowEditor.modelProfile": "Model profile",
  "web.WorkflowEditor.additionalInstructions": "Additional instructions",
  "web.WorkflowEditor.conversationLimits": "Conversation limits",
  "web.WorkflowEditor.callAndProcessingLimitsApplyToEachTurnTime": "Call and processing limits apply to each turn. Time spent waiting for you does not count. Follow-up turns limit the conversation. Values must fit your server’s configured maximums.",
  "web.WorkflowEditor.loadLatestToCompare": "Load latest to compare",
  "web.WorkflowEditor.toolCallsPerTurn": "Tool calls per turn",
  "web.WorkflowEditor.modelCallsPerTurn": "Model calls per turn",
  "web.WorkflowEditor.processingTimePerTurnSeconds": "Processing time per turn (seconds)",
  "web.WorkflowEditor.followUpTurns": "Follow-up turns",
  "web.WorkflowWorkspace.conversationSettingsUnavailable": "Conversation settings unavailable",
  "web.WorkflowWorkspace.yourAccountNoLongerHasAccessToConfigureThis": "Your account no longer has access to configure this tenant.",
  "web.WorkflowWorkspace.conversations": "Conversations",
  "web.WorkflowWorkspace.tuneHowYourConfiguredModelsWorkWithYourInventory": "Tune how your configured models work with your inventory.",
  "web.WorkflowWorkspace.couldNotLoadTheActiveWorkflow": "Could not load the active workflow.",
  "web.WorkflowWorkspace.retryActiveWorkflow": "Retry active workflow",
  "web.WorkflowWorkspace.loadingActiveWorkflow": "Loading active workflow…",
  "web.WorkflowWorkspace.thisRevisionWasConvertedFromThePreviousWorkflowFormat": "This revision was converted from the previous workflow format. Its selected model and general guidance were retained; stage-specific rules were removed. Review the settings and run your test cases before activating a new revision.",
  "web.WorkflowWorkspace.closeEditorAndDiscardUnsavedEdits": "Close editor and discard unsaved edits",
  "web.WorkflowWorkspace.loadingConfiguredModels": "Loading configured models…",
  "web.WorkflowWorkspace.couldNotLoadConfiguredModels": "Could not load configured models.",
  "web.WorkflowWorkspace.retryModels": "Retry models",
  "web.WorkflowWorkspace.latestRevisionComparison": "Latest revision comparison",
  "web.WorkflowWorkspace.latestSavedRevision": "Latest saved revision",
  "web.WorkflowWorkspace.model": "Model",
  "web.WorkflowWorkspace.perTurnLimits": "Per-turn limits",
  "web.WorkflowWorkspace.toolCalls": "tool calls ·",
  "web.WorkflowWorkspace.followUps": "Follow-ups",
  "web.WorkflowWorkspace.replaceMyEditsWithThisRevision": "Replace my edits with this revision",
  "web.WorkflowWorkspace.newWorkflow": "New workflow",
  "web.WorkflowWorkspace.loadingWorkflows": "Loading workflows…",
  "web.WorkflowWorkspace.couldNotLoadWorkflows": "Could not load workflows.",
  "web.WorkflowWorkspace.retryWorkflows": "Retry workflows",
  "web.WorkflowWorkspace.revision": "· Revision",
  "web.WorkflowWorkspace.noSavedWorkflowsYetCreateOneToStartTuning": "No saved workflows yet. Create one to start tuning your conversations.",
  "web.WorkflowWorkspace.nextWorkflows": "Next workflows",
  "web.WorkflowWorkspace.backToFirstWorkflows": "Back to first workflows",
  "web.page.stuffStash": "Stuff Stash",
  "web.page.loadingStuffStash": "Loading Stuff Stash...",
  "web.page.confirmingSession": "Confirming session",
  "web.InvitationAcceptSurface.joinFull": "Join {inventoryName}",
  "web.InvitationAcceptSurface.youAlreadyJoinedFull": "You already joined {inventoryName}",
  "web.InvitationAcceptSurface.youJoinedFull": "You joined {inventoryName}",
  "web.AssetDetail.byFull": "{value} by {checkedOutByPrincipalId}",
  "web.AssetDetail.returnedByFull": "Returned {value} by {returnedByPrincipalId}",
  "web.AssetDetailActionPanel.expirationTrackingIsDisabledForThisTypeFull": "Expiration: {date}. Tracking is disabled for this type.",
  "web.AssetDetailHero.retryFull": "Retry {retryPhotoName}",
  "web.BrowsePanel.filtersFull": "Filters{value}",
  "web.BrowsePanel.shownFull": "{length} shown",
  "web.BrowsePanel.showNextFull": "Show next {value}",
  "web.BrowsePanel.ofShownFull": "{value} of {length} shown",
  "web.ContainedAssetWorkspace.addingItemsIsUnavailableForThisInventoryFull": "Adding items is unavailable for this inventory.{value}",
  "web.ContainedAssetWorkspace.eligibleFull": "{totalCount} eligible {value}",
  "web.ContainedAssetWorkspace.showAllFull": "Show all {totalCount}",
  "web.ImportJobDetailPanel.issuesFull": "Issues{value}",
  "web.ImportJobDetailPanel.ofFull": "{value}-{visibleResourceEnd} of {length}",
  "web.ImportJobDetailPanel.importedFull": "{value} · Imported {value2}",
  "web.ImportJobDetailPanel.pageOfFull": "Page {value} of {resourcePageCount}",
  "web.ImportJobDetailPanel.phasesFull": "{length} phases",
  "web.ImportMessagesList.showMoreInThisGroupFull": "Show {length} more in this group",
  "web.ImportMessagesList.moreIssueHiddenFull": "{hiddenGroupCount} more issue {value} hidden.",
  "web.ImportMessagesList.moreAffectedInThisGroupFull": "{value} more affected {value2} in this group.",
  "web.ImportPreviewSamples.pageOfFull": "Page {value} of {value2}",
  "web.ImportSourceSetup.kBPhotosAreNotIncludedInCSVExportsFull": "{name} · {value} KB · photos are not included in CSV exports",
  "web.InventoryConversationPanel.expiresFull": "Expires {value}",
  "web.InventoryConversationPanel.destinationFull": "Destination: {destination}",
  "web.ParentTargetPicker.showAllMatchesFull": "Show all {length} matches",
  "web.ExpirationHome.expiredFull": "Expired · {expired}",
  "web.ExpirationHome.expiringSoonFull": "Expiring soon · {soon}",
  "web.ExpirationWorkspace.filtersFull": "Filters{value}",
  "web.ExpirationWorkspace.filtersAppliedFull": "Filters applied{value}{value2}",
  "web.AssetTypeSettingsManager.manageInFull": "Manage in {name}",
  "web.FieldSettingsManager.manageInFull": "Manage in {name}",
  "web.NotificationSettings.timeZoneFull": "Time zone · {value}",
  "web.SettingsWorkspace.belongsToFull": "{name} belongs to {name2}.",
  "web.CaseFixtures.fixtureFull": "Fixture {value}{value2}",
  "web.CaseSummary.tagsFull": "Tags: {value}",
  "web.CaseSummary.expectedResultFull": "Expected result: {kind}",
  "web.CaseSummary.isInsideFull": "{value} is inside {value2}.",
  "web.CaseSummary.forbiddenChangesFull": "Forbidden changes: {value}",
  "web.CaseWorkspace.latestSavedRevisionFull": "Latest saved revision {number}",
  "web.CaseWorkspace.revisionFull": "{title} · Revision {latestRevision}",
  "web.RunActivation.revisionFull": "{name} · Revision {number}",
  "web.RunActivation.theServerChecksCurrentCasesProvidersAndLimitsFull": "{value} The server checks current cases, providers and limits before activation.",
  "web.RunComparison.passedFull": "{value} · {passedCases}/{totalCases} passed",
  "web.RunComparison.sFull": "{value} s",
  "web.RunComparison.selectedRunCallsSFull": "Selected run: {value} · {modelCalls} calls · {value3} s",
  "web.RunComparison.thisRunCallsSFull": "This run: {value} · {modelCalls} calls · {value3} s",
  "web.RunDetails.ofCasesCompletedPassedFull": "{completedCases} of {totalCases} cases completed · {passedCases} passed",
  "web.RunDetails.referenceFull": "Reference: {failureCode}",
  "web.RunDetails.noPassingResultRecordedFull": "{value} — no passing result recorded.",
  "web.RunResult.modelCallsSecondsFull": "{value} · {modelCalls} model calls · {value3} seconds",
  "web.RunResult.outcomeFull": "Outcome: {kind}",
  "web.RunResult.insideFull": "{value} inside {value2}",
  "web.RunResult.executedOperationsFull": "Executed operations: {value}",
  "web.RunSetup.revisionFull": "{name} · Revision {latestRevision}",
  "web.RunSetup.selectedFull": "Selected: {name}",
  "web.RunSetup.revisionFull2": "Revision {number} · {name}",
  "web.RunSetup.revisionFull3": "{title} · Revision {latestRevision}",
  "web.RunSetup.selectedUpTo100Full": "{length} selected (up to 100)",
  "web.RunSetup.removeFull": "Remove {title}",
  "web.RunSetup.revisionFull4": "{name} · Revision {number}",
  "web.RunSetup.perAttemptUpToModelCallsAcrossCasesFull": "Per attempt, up to {length} model calls across {length2} cases; each case has a {elapsedSeconds}-second budget. Recovering an interrupted run may add model calls.",
  "web.RunWorkspace.casesFull": "{value} · {completedCases}/{totalCases} cases · {value4}",
  "web.WorkflowWorkspace.latestSavedRevisionFull": "Latest saved revision {number}",
  "web.WorkflowWorkspace.toolCallsModelCallsSecondsFull": "{toolCalls} tool calls · {modelCalls} model calls · {elapsedSeconds} seconds",
  "web.WorkflowWorkspace.revisionFull": "{name} · Revision {latestRevision}"
} as const;
