/** Complete workflow messages, including variable-derived notices. */
export const workflowMessages = {
  "asset.lifecycle.active": "Active",
  "asset.lifecycle.archived": "Archived",
  "case.operation.locate": "Locate",
  "case.operation.exists": "Check existence",
  "case.operation.list_inventory": "List inventory",
  "case.operation.list_contents": "List contents",
  "case.operation.detail": "View details",
  "case.operation.checkout_status": "Check availability",
  "case.operation.asset_history": "View item history",
  "case.operation.checkout_history": "View checkout history",
  "case.operation.create": "Create",
  "case.operation.move": "Move",
  "case.operation.archive": "Archive",
  "case.operation.restore": "Restore",
  "case.operation.checkout": "Check out",
  "case.operation.return": "Return",
  "case.operation.unsupported": "Unsupported operation",
  "case.outcome.answer": "Answer",
  "case.outcome.clarification": "Clarification",
  "case.outcome.proposal": "Proposal",
  "case.outcome.failure": "Failure",

  "asset.expirationFallback": "Expiration",
  "voice.fallbackContainer": "container",
  "voice.fallbackPlace": "existing place",
  "asset.archiveSucceeded": "Archive succeeded",
  "asset.restoreSucceeded": "Restore succeeded",
  "notification.markUnread": "Mark {title} unread",
  "notification.markRead": "Mark {title} read",
  "voice.entityDeferred": "{title}, available after the response finishes",
  "voice.entityDeferredContext": "{title} in {context}, available after the response finishes",
  "containment.addUnavailable": "Adding items is unavailable for this inventory.",
  "containment.addMoveUnavailable": "Adding items is unavailable for this inventory. Moving items is also unavailable.",
  "expiration.filtersActive": "Filters · Active",
  "expiration.fromSummary": " · From {date}",
  "expiration.throughSummary": " · Through {date}",
  "workflow.replaceCustom": "This will replace the current custom workflow.",
  "workflow.replaceDefault": "This will replace the default conversation workflow.",
  "evaluation.passed": "Passed",
  "evaluation.failed": "Failed",
  "evaluation.notRun": "Not run yet",
  "evaluation.notCompleted": "Not completed",
  "evaluation.none": "None",
  "workflow.savedFallback": "Saved workflow",

  "photos.storageUploadFailed": "Could not upload the photo. Try again.",
  "browse.list": "List",
  "browse.map": "Map",
  "customization.fromHousehold": "From {household}",

  "recovery.browseContinuation": "Could not load more items. Try again.",
  "recovery.locationUnavailable": "This location is no longer available in this inventory.",
  "recovery.checkoutUnavailable": "Asset checkout is not available.",
  "recovery.returnUnavailable": "Asset return is not available.",
  "recovery.returnDetailsUnavailable": "Asset return details are not available.",
  "recovery.checkoutUndoUnavailable": "Undo is not available.",

  "mobile.providers.onboardingRequired": "Complete mobile onboarding before managing voice provider profiles.",
  "mobile.network.timeout": "Network request timed out. Check that the API is reachable from this phone.",
  "web.options.seededInventoryRepository.cancellationRequested": "Cancellation requested",
  "web.options.seededInventoryRepository.queuedLocally": "Queued locally",
  "web.options.AssetDetailActionPanel.baseAsset": "Base asset",
  "web.options.CustomFieldControls.unset": "Unset",
  "web.options.ExpirationField.monthAndYear": "Month and year",
  "web.options.ExpirationField.exactDate": "Exact date",
  "web.options.NotificationInbox.unread": "Unread",
  "web.options.NotificationInbox.all": "All",
  "web.options.ExpirationFilters.checkedOut": "Checked out",
  "web.options.ExpirationFilters.available": "Available",
  "web.options.ExpirationFilters.places": "Places",
  "web.options.ExpirationFilters.containers": "Containers",
  "web.options.ExpirationFilters.items": "Items",
  "web.options.ExpirationReminderEditor.off": "Off",
  "web.options.ExpirationReminderEditor.custom": "Custom",
  "web.options.ExpirationReminderEditor.useDefaults": "Use defaults",
  "web.options.CaseExpectations.unnamedFixture": "Unnamed fixture",
  "web.options.CaseExpectations.noParent": "No parent",
  "web.options.CaseExpectations.location": "Location",
  "web.options.CaseExpectations.container": "Container",
  "web.options.CaseExpectations.item": "Item",
  "web.options.CaseExpectations.reportAFailure": "Report a failure",
  "web.options.CaseExpectations.proposeAChange": "Propose a change",
  "web.options.CaseExpectations.askForClarification": "Ask for clarification",
  "web.options.CaseExpectations.answerTheQuestion": "Answer the question",
  "web.options.CaseFixtures.unnamedFixture": "Unnamed fixture",
  "web.options.CaseFixtures.noParent": "No parent",
  "web.options.CaseFixtures.location": "Location",
  "web.options.CaseFixtures.container": "Container",
  "web.options.CaseFixtures.item": "Item",
  "web.options.WorkflowEditor.savedProfileCurrentlyUnavailable": "Saved profile (currently unavailable)",
  "web.options.WorkflowEditor.tenantDefaultModel": "Tenant default model",
  "customization.keyGuidance": "Key must start with a letter and use lowercase letters, numbers, or hyphens.",
  "inventory.workspaceEmpty": "Inventory workspace must include at least one inventory.",
  "inventory.tenantMissing": "Selected inventory must belong to a tenant.",
  "providerTest.chooseProfile": "Choose a provider profile to test.",
  "providerTest.failed": "Connection test failed. Check the profile configuration and credential, then try again.",
  "sharing.emailRequired": "Enter a valid email address.",
  "sharing.invitationRequired": "Invitation ID must not be empty.",
  "settings.serverNotConfigured": "Not configured",
  "settings.versionUnknown": "Unknown",
  "voice.openEntityIn": "Open {title} in {context}",
  "voice.openEntity": "Open {title}",
  "auth.refreshRequired": "Sign in again to refresh your Stuff Stash session.",
  "auth.unusableSession": "Sign-in did not return a usable Stuff Stash session.",
  "auth.unrefreshableSession": "Sign-in did not return a refreshable Stuff Stash session.",
  "voice.entityPosition": "{label} ({position} of {total})",
  "move.cannotContainSelf": "An asset cannot be moved into itself.",
  "move.saved": "Moved {title}.",
  "move.savedAtRoot": "Moved {title} to No parent.",
  "voice.disconnectedReview": "{reason} This review is disconnected. Your draft is kept here. Check the inventory before submitting the change again.",
  "color.degrees": "{value} degrees",
  "color.percent": "{value} percent",
  "onboarding.householdExample": "e.g. Maple Street household",
  "onboarding.inventoryExample": "e.g. Home Inventory",
  "assets.openNamed": "Open asset {title}",
  "customization.onlyIn": "Only in {inventory}",
  "settings.unavailableReason": "Settings unavailable. {reason}",
  "browse.currentInventory": "this inventory",
  "move.promotedPath": "{path} · Will become a container",
  "assets.savedWithPhotoFailures": {
    "one": "Saved {title}, but {count} photo upload failed.",
    "other": "Saved {title}, but {count} photo uploads failed."
  },
  "assets.savedNamed": "Saved {title}.",
  "assets.updatedNamed": "Updated {title}.",
  "customization.inheritedName": "{name} · Inherited",
  "photos.added": {
    "one": "{count} photo added.",
    "other": "{count} photos added."
  },
  "photos.failedReason": "Photos could not be uploaded: {reason}",
  "photos.partiallyAdded": "{added} of {total} photos added.",
  "workspace.inventoryCreated": "Created {title}.",
  "assets.archivedNamed": "Archived {title}.",
  "assets.restoredNamed": "Restored {title}.",
  "assets.deletedNamed": "Deleted {title}.",
  "assets.checkedOutNamed": "Checked out {title}.",
  "assets.returnedNamed": "Returned {title}.",
  "photos.archivedNamed": "Archived {title}.",
  "photos.deletedNamed": "Deleted {title}.",
  "photos.uploadedNamed": "Uploaded {title}.",
  "move.savedInto": "Moved {title} into {parent}.",
  "move.failedWithReason": "Move not saved. {title} stayed where it was. {reason}",
  "move.permissionDenied": "Move not saved. You do not have permission to move assets in this inventory.",
  "move.failed": "Move not saved. {title} stayed where it was.",
  "contents.insideNamed": "Inside {title}",
  "contents.spacesIn": "Spaces in {title}",
  "contents.itemsIn": "Items in {title}",
  "search.noSuggestions": "No suggestions for \"{query}\". Press Search to run a full search.",
  "move.currentDestination": "Current destination: {name}, {metadata}",
  "conversation.caseRevisionSaved": "Test case revision {revision} saved.",
  "conversation.workflowRevisionSaved": "Draft revision {revision} saved. Run test cases before activation.",
  "workspace.appliedRefreshNeeded": "{result} Reload to see the latest inventory.",
  "move.matchCount": {
    "one": "{count} match",
    "other": "{count} matches"
  },
  "move.destinationCount": {
    "one": "{count} possible destination",
    "other": "{count} possible destinations"
  },
  "move.suggestionCount": {
    "one": "Showing {count} suggested destination.",
    "other": "Showing {count} suggested destinations."
  },
  "move.truncatedMatches": "Showing the first {shown} of {total} matches.",
  "expiration.default.day": "Expiration: {date}",
  "expiration.default.month": "Expiration: {date} (end of month)",
  "expiration.disabled.day": "Expiration tracking disabled: {date}",
  "expiration.disabled.month": "Expiration tracking disabled: {date} (end of month)",
  "expiration.today.day": "Expires today: {date}",
  "expiration.today.month": "Expires today: {date} (end of month)",
  "expiration.upcoming.day": "Expiring soon: {date}",
  "expiration.upcoming.month": "Expiring soon: {date} (end of month)",
  "expiration.expired.day": "Expired: {date}",
  "expiration.expired.month": "Expired: {date} (end of month)",
  "contents.childCount": {
    "one": "{count} inside",
    "other": "{count} inside"
  },
  "assets.savedIn": "Saved {title} in {parent}.",
  "assets.savedWithUploads": {
    "one": "Saved {title} with {count} photo upload.",
    "other": "Saved {title} with {count} photo uploads."
  },
  "assets.savedInWithUploads": {
    "one": "Saved {title} in {parent} with {count} photo upload.",
    "other": "Saved {title} in {parent} with {count} photo uploads."
  },
  "photos.saveWarning": {
    "one": "{saved} {count} photo upload failed.",
    "other": "{saved} {count} photo uploads failed."
  },
  "photos.saveWarningWithReason": {
    "one": "{saved} {count} photo upload failed. {reason}",
    "other": "{saved} {count} photo uploads failed. {reason}"
  },
  "import.historyFor": "View current and past data imports for {inventory}.",
  "import.detailsFor": "Import details for {inventory}.",
  "photos.maximumSize": "Attachment must be {size} or smaller.",
  "photos.unsupportedNamed": "{name} is not a supported image type.",
  "photos.oversizedNamed": "{name} is larger than {size}.",
  "import.unknownContentType": "unknown type",
  "import.visibleRange": "{start}-{end} of {total}",
  "import.visibleRangeTruncated": "{start}-{end} of {total}+",
  "conversation.fixtureNamed": "Fixture {title}",
  "conversation.fixtureSettings": "Fixture settings",
  "reminders.before": {
    "one": "{count} day before expiration",
    "other": "{count} days before expiration"
  },
  "reminders.beforeAndExpired": {
    "one": "{count} day before expiration and when expired",
    "other": "{count} days before expiration and when expired"
  },
  "reminders.whenExpired": "When expired",
  "reminders.none": "Default reminders are off",
  "media.bytes": "{size} B",
  "media.kilobytes": "{size} KB",
  "media.megabytes": "{size} MB",
  "identity.account.loading": "Loading account identity",
  "identity.account.refreshFailed": "Could not refresh account identity. Previously loaded value is shown.",
  "identity.account.loadFailed": "Could not load account identity.",
  "identity.account.retrying": "Retrying account identity…",
  "identity.account.retry": "Retry account identity",
  "identity.household.loading": "Loading household identity",
  "identity.household.refreshFailed": "Could not refresh household identity. Previously loaded value is shown.",
  "identity.household.loadFailed": "Could not load household identity.",
  "identity.household.retrying": "Retrying household identity…",
  "identity.household.retry": "Retry household identity",
  "recovery.cameraRequired": "Camera access is required to take a photo. Allow camera access for Stuff Stash in device settings, then try again. You can also choose a photo from your library.",
  "recovery.photoFormat": "Choose JPEG, PNG, or WebP photos. This selection includes an unsupported image format.",
  "recovery.sharingUnavailable": "File sharing is unavailable on this device.",
  "recovery.inventoryDiscovery": "Could not load your inventories. Try again.",
  "recovery.invitationPage": "Stuff Stash returned an invalid invitation page.",
  "recovery.invitationLink": "Stuff Stash did not return the one-time invitation link.",
  "recovery.invitationResponse": "Stuff Stash returned an invalid invitation response.",
  "recovery.createParent": "Create this parent or clear the Put in field.",
  "recovery.chooseParent": "Choose a place or container for Put in.",
  "recovery.reselectParent": "Choose this parent again before saving.",
  "recovery.refreshInventory": "Could not refresh inventory context.",
  "recovery.nameRequired": "Name is required.",
  "recovery.choosePhoto": "Choose at least one photo.",
  "recovery.tagUnavailable": "Tag creation is not available.",
  "recovery.revertUnavailable": "This change can’t be reverted.",
  "recovery.undoUnavailable": "Undo is not available.",
  "recovery.expirationContinuation": "Expiration results could not be continued. Refresh and try again.",
  "recovery.notificationFailed": "The notification operation could not be completed. Try again.",
  "recovery.inventoryChanged": "Inventory changed. Reopen Browse filters.",
  "recovery.inventoryFailed": "Inventory could not be loaded.",
  "recovery.assetFailed": "Asset could not be loaded.",
  "progress.navigation.current": "{step}, current step",
  "progress.navigation.complete": "Go to {step}, completed step",
  "progress.navigation.upcoming": "Go to {step}, not started step",
  "progress.navigation.described": "{label}. {description}",
  "sharing.invitation.message": "You’re invited to {inventory} in Stuff Stash.\n\n{link}",
  "recovery.uploadConfiguration": "Could not start the upload. Check your server settings and try again.",
  "recovery.uploadFailed": "Could not upload the file. Try again.",
  "recovery.uploadContentUnavailable": "This file is no longer available. Choose it again.",
  "sharing.invitation.title": "Share Stuff Stash invitation",
  "sharing.export.title": "Export inventory",
  "notifications.channel.expiration": "Expiration reminders",
  "recovery.pagedRead": "Could not finish loading. Try again.",
  "inventory.loaded": "Loaded from API",
  "inventory.locationAsset": "Location asset",
  "inventory.root": "Inventory root",
  "search.match.tag": "Tag",
  "search.match.title": "Title",
  "search.match.description": "Description",
  "search.match.location": "Location",
  "search.match.customField": "Custom field",
  "search.match.generic": "Match",
  "inventory.updated": "Updated {date}",
  "workspace.creationFailed.household": "Could not create household. Check your access and connection, then try again.",
  "workspace.creationFailed.inventory": "Could not create inventory. Check your access and connection, then try again.",
  "sharing.linkFailed.copy": "Could not copy invitation",
  "sharing.linkFailed.share": "Could not share invitation",
  "customization.loading.active": "Loading active settings…",
  "customization.loading.archived": "Loading archived settings…"
} as const;
