/** Complete workflow messages, including variable-derived notices. */
export const workflowMessages = {
  "voice.openEntityIn": "Open {title} in {context}",
  "voice.openEntity": "Open {title}",
  "voice.entityPosition": "{label} ({position} of {total})",
  "move.cannotContainSelf": "An asset cannot be moved into itself.",
  "move.saved": "Moved {title}.",
  "move.savedAtRoot": "Moved {title} to No parent.",
  "voice.disconnectedReview": "{reason} This review is disconnected. Your draft is kept here. Check the inventory before submitting the change again.",
  "color.degrees": "{value} degrees",
  "color.percent": "{value} percent",
  "onboarding.householdExample": "e.g. Maple Street household",
  "onboarding.inventoryExample": "e.g. Home Inventory",
  "assets.openNamed": "Open asset {title}",
  "customization.onlyIn": "Only in {inventory}",
  "settings.unavailableReason": "Settings unavailable. {reason}",
  "browse.currentInventory": "this inventory",
  "move.promotedPath": "{path} · Will become a container",
  "assets.savedWithPhotoFailures": {
    "one": "Saved {title}, but {count} photo upload failed.",
    "other": "Saved {title}, but {count} photo uploads failed."
  },
  "assets.savedNamed": "Saved {title}.",
  "assets.updatedNamed": "Updated {title}.",
  "customization.inheritedName": "{name} · Inherited",
  "photos.added": {
    "one": "{count} photo added.",
    "other": "{count} photos added."
  },
  "photos.failedReason": "Photos could not be uploaded: {reason}",
  "photos.partiallyAdded": "{added} of {total} photos added.",
  "workspace.inventoryCreated": "Created {title}.",
  "assets.archivedNamed": "Archived {title}.",
  "assets.restoredNamed": "Restored {title}.",
  "assets.deletedNamed": "Deleted {title}.",
  "assets.checkedOutNamed": "Checked out {title}.",
  "assets.returnedNamed": "Returned {title}.",
  "photos.archivedNamed": "Archived {title}.",
  "photos.deletedNamed": "Deleted {title}.",
  "photos.uploadedNamed": "Uploaded {title}.",
  "move.savedInto": "Moved {title} into {parent}.",
  "move.failedWithReason": "Move not saved. {title} stayed where it was. {reason}",
  "move.permissionDenied": "Move not saved. You do not have permission to move assets in this inventory.",
  "move.failed": "Move not saved. {title} stayed where it was.",
  "contents.insideNamed": "Inside {title}",
  "contents.spacesIn": "Spaces in {title}",
  "contents.itemsIn": "Items in {title}",
  "search.noSuggestions": "No suggestions for \"{query}\". Press Search to run a full search.",
  "move.currentDestination": "Current destination: {name}, {metadata}",
  "conversation.caseRevisionSaved": "Test case revision {revision} saved.",
  "conversation.workflowRevisionSaved": "Draft revision {revision} saved. Run test cases before activation.",
  "workspace.appliedRefreshNeeded": "{result} Reload to see the latest inventory.",
  "move.matchCount": {
    "one": "{count} match",
    "other": "{count} matches"
  },
  "move.destinationCount": {
    "one": "{count} possible destination",
    "other": "{count} possible destinations"
  },
  "move.suggestionCount": {
    "one": "Showing {count} suggested destination.",
    "other": "Showing {count} suggested destinations."
  },
  "move.truncatedMatches": "Showing the first {shown} of {total} matches.",
  "expiration.default.day": "Expiration: {date}",
  "expiration.default.month": "Expiration: {date} (end of month)",
  "expiration.disabled.day": "Expiration tracking disabled: {date}",
  "expiration.disabled.month": "Expiration tracking disabled: {date} (end of month)",
  "expiration.today.day": "Expires today: {date}",
  "expiration.today.month": "Expires today: {date} (end of month)",
  "expiration.upcoming.day": "Expiring soon: {date}",
  "expiration.upcoming.month": "Expiring soon: {date} (end of month)",
  "expiration.expired.day": "Expired: {date}",
  "expiration.expired.month": "Expired: {date} (end of month)",
  "contents.childCount": {
    "one": "{count} inside",
    "other": "{count} inside"
  },
  "assets.savedIn": "Saved {title} in {parent}.",
  "assets.savedWithUploads": {
    "one": "Saved {title} with {count} photo upload.",
    "other": "Saved {title} with {count} photo uploads."
  },
  "assets.savedInWithUploads": {
    "one": "Saved {title} in {parent} with {count} photo upload.",
    "other": "Saved {title} in {parent} with {count} photo uploads."
  },
  "photos.saveWarning": {
    "one": "{saved} {count} photo upload failed.",
    "other": "{saved} {count} photo uploads failed."
  },
  "photos.saveWarningWithReason": {
    "one": "{saved} {count} photo upload failed. {reason}",
    "other": "{saved} {count} photo uploads failed. {reason}"
  },
  "import.historyFor": "View current and past data imports for {inventory}.",
  "import.detailsFor": "Import details for {inventory}.",
  "photos.maximumSize": "Attachment must be {size} or smaller.",
  "photos.unsupportedNamed": "{name} is not a supported image type.",
  "photos.oversizedNamed": "{name} is larger than {size}.",
  "import.unknownContentType": "unknown type",
  "import.visibleRange": "{start}-{end} of {total}",
  "import.visibleRangeTruncated": "{start}-{end} of {total}+",
  "conversation.fixtureNamed": "Fixture {title}",
  "conversation.fixtureSettings": "Fixture settings",
  "reminders.before": {
    "one": "{count} day before expiration",
    "other": "{count} days before expiration"
  },
  "reminders.beforeAndExpired": {
    "one": "{count} day before expiration and when expired",
    "other": "{count} days before expiration and when expired"
  },
  "reminders.whenExpired": "When expired",
  "reminders.none": "Default reminders are off",
  "media.bytes": "{size} B",
  "media.kilobytes": "{size} KB",
  "media.megabytes": "{size} MB",
  "identity.account.loading": "Loading account identity",
  "identity.account.refreshFailed": "Could not refresh account identity. Previously loaded value is shown.",
  "identity.account.loadFailed": "Could not load account identity.",
  "identity.account.retrying": "Retrying account identity…",
  "identity.account.retry": "Retry account identity",
  "identity.household.loading": "Loading household identity",
  "identity.household.refreshFailed": "Could not refresh household identity. Previously loaded value is shown.",
  "identity.household.loadFailed": "Could not load household identity.",
  "identity.household.retrying": "Retrying household identity…",
  "identity.household.retry": "Retry household identity",
  "recovery.cameraRequired": "Camera access is required to take a photo. Allow camera access for Stuff Stash in device settings, then try again. You can also choose a photo from your library.",
  "recovery.photoFormat": "Choose JPEG, PNG, or WebP photos. This selection includes an unsupported image format.",
  "recovery.sharingUnavailable": "File sharing is unavailable on this device.",
  "recovery.invitationPage": "Stuff Stash returned an invalid invitation page.",
  "recovery.invitationLink": "Stuff Stash did not return the one-time invitation link.",
  "recovery.invitationResponse": "Stuff Stash returned an invalid invitation response.",
  "recovery.createParent": "Create this parent or clear the Put in field.",
  "recovery.chooseParent": "Choose a place or container for Put in.",
  "recovery.reselectParent": "Choose this parent again before saving.",
  "recovery.refreshInventory": "Could not refresh inventory context.",
  "recovery.nameRequired": "Name is required.",
  "recovery.choosePhoto": "Choose at least one photo.",
  "recovery.tagUnavailable": "Tag creation is not available.",
  "recovery.revertUnavailable": "This change can’t be reverted.",
  "recovery.undoUnavailable": "Undo is not available.",
  "recovery.expirationContinuation": "Expiration results could not be continued. Refresh and try again.",
  "recovery.notificationFailed": "The notification operation could not be completed. Try again.",
  "recovery.inventoryChanged": "Inventory changed. Reopen Browse filters.",
  "recovery.inventoryFailed": "Inventory could not be loaded.",
  "recovery.assetFailed": "Asset could not be loaded."
} as const;
