import { expect, test } from '@playwright/test';
import { installAuthenticatedWorkspace, resetWorkspaceApiState } from './workspace-fixture';
import { installConversationFixture } from './conversation-fixture';
const path = '/settings/tenants/tenant-home/conversations';
test('edits cases, runs pinned revisions and activates only after review', async ({ page }, testInfo) => {
  resetWorkspaceApiState(page); await installAuthenticatedWorkspace(page); const state = await installConversationFixture(page);
  await page.goto(path);
  await page.getByRole('button', { name: /Household voice · Revision 1/ }).click();
  await page.getByLabel('Workflow name').fill('Household voice tuned');
  await page.getByRole('button', { name: 'Save draft', exact: true }).click();
  await expect(page.getByRole('status').filter({ hasText: 'Draft revision 2 saved' })).toBeVisible();
  await page.getByRole('button', { name: /Close editor/ }).click();
  await page.getByRole('button', { name: 'Test cases', exact: true }).click();
  await page.getByRole('button', { name: /Find baby clothes · Revision 1/ }).click();
  await page.getByLabel('Case title', { exact: true }).fill('');
  await page.getByRole('button', { name: 'Save test case', exact: true }).click();
  await expect(page.getByLabel('Case title', { exact: true })).toHaveAttribute('aria-describedby', 'case-title-error');
  await expect(page.locator('#case-title-error')).toBeVisible();
  await page.getByLabel('Case title', { exact: true }).fill('Baby clothes in the attic');
  await page.screenshot({ path: testInfo.outputPath('case-editor.png'), fullPage: true });
  await page.getByRole('button', { name: 'Save test case', exact: true }).click();
  await expect(page.getByRole('status').filter({ hasText: 'Test case revision 2 saved' })).toBeVisible();
  await page.getByRole('button', { name: /Close editor/ }).click();
  await page.getByRole('button', { name: 'Runs', exact: true }).click(); await page.getByRole('button', { name: 'New run', exact: true }).click();
  await page.getByRole('button', { name: /Household voice tuned · Revision 2/ }).click();
  await page.getByRole('button', { name: /Baby clothes in the attic · Revision 2/ }).click();
  await page.getByRole('button', { name: 'Run selected cases', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Completed', exact: true })).toBeVisible();
  expect(state.queued[0]).toEqual({ workflowId: 'workflow', revisionId: 'workflow-revision-2', cases: [{ caseId: 'case', revisionId: 'case-revision-2' }] });
  await page.getByRole('button', { name: 'Compare expected and observed', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Observed', exact: true })).toBeVisible();
  expect(state.activations).toBe(0);
  await page.screenshot({ path: testInfo.outputPath('run-review.png'), fullPage: true });
  await page.getByRole('button', { name: 'Activate tested revision', exact: true }).click();
  await expect(page.getByText('This revision is active.', { exact: true })).toBeVisible(); expect(state.activations).toBe(1);
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
});
test('clears the entire conversation surface when access is revoked', async ({ page }) => {
  resetWorkspaceApiState(page); await installAuthenticatedWorkspace(page); const state = await installConversationFixture(page);
  await page.goto(path); await expect(page.getByRole('button', { name: 'Test cases', exact: true })).toBeVisible();
  state.denied = true; await page.getByRole('button', { name: 'Test cases', exact: true }).click();
  await expect(page.getByText('Your account no longer has access to configure this tenant.', { exact: true })).toBeVisible();
  await expect(page.getByRole('button', { name: 'New workflow', exact: true })).toHaveCount(0);
  await expect(page.getByText('Find baby clothes', { exact: true })).toHaveCount(0);
});
