import {expect,test} from '@playwright/test';
import {installPrintingSettings} from './printing-settings-fixture';
const path='/settings/tenants/tenant-home/inventories/inventory-household/printing';
test('printer settings protect drafts and disclose report details inside the workspace',async({page},testInfo)=>{
 const printer=await installPrintingSettings(page);await page.goto(path);
 await expect(page.getByRole('heading',{name:'Registered printers',exact:true})).toBeVisible();
 await expect(page.getByText('29 × 90 mm (DK-11201)',{exact:true})).toBeVisible();
 await expect(page.getByText('Reported printed',{exact:true})).toBeVisible();
 const actor=page.getByText('Reported by oidc_', {exact:false});await expect(actor).not.toBeVisible();
 await page.getByText('Report details',{exact:true}).focus();await page.keyboard.press('Enter');await expect(actor).toBeVisible();
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 await page.getByText('Report details',{exact:true}).press('Enter');
 await page.getByRole('heading',{name:'Printers and labels',exact:true}).scrollIntoViewIfNeeded();
 await page.screenshot({path:testInfo.outputPath('printing-settings.png'),fullPage:true});
 const edit=page.getByRole('button',{name:'Edit printer',exact:true});await edit.click();
 await page.getByLabel('Printer name',{exact:true}).fill('Workshop Brother');await page.keyboard.press('Escape');
 await expect(page.getByRole('alertdialog',{name:'Discard changes?'})).toBeVisible();
 await page.getByRole('button',{name:'Keep editing',exact:true}).click();
 await expect(page.getByLabel('Printer name',{exact:true})).toBeFocused();
 await expect(page.getByLabel('Printer name',{exact:true})).toHaveValue('Workshop Brother');
 await page.getByRole('button',{name:'Save printer',exact:true}).click();await expect(page.getByRole('dialog')).not.toBeVisible();
 await expect(edit).toBeFocused();expect(printer.name).toBe('Workshop Brother');
 await edit.click();await page.getByLabel('Printer name',{exact:true}).fill('Discard me');
 await page.mouse.click(4,4);await expect(page.getByRole('alertdialog',{name:'Discard changes?'})).toBeVisible();
 await page.getByRole('button',{name:'Keep editing',exact:true}).click();
 await expect(page.getByLabel('Printer name',{exact:true})).toHaveValue('Discard me');
 await page.getByRole('button',{name:'Cancel',exact:true}).click();await page.getByRole('button',{name:'Discard changes',exact:true}).click();
 await expect(edit).toBeFocused();expect(printer.name).toBe('Workshop Brother');
});
