export type WorkspaceEventName =
  | 'workspace.load_started'
  | 'workspace.load_failed'
  | 'workspace.loaded'
  | 'workspace.asset_create_started'
  | 'workspace.asset_created'
  | 'workspace.asset_create_failed'
  | 'workspace.asset_detail_load_started'
  | 'workspace.asset_detail_loaded'
  | 'workspace.asset_detail_load_failed'
  | 'workspace.asset_primary_photo_load_failed'
  | 'workspace.asset_update_started'
  | 'workspace.asset_updated'
  | 'workspace.asset_update_failed'
  | 'workspace.asset_tag_create_started'
  | 'workspace.asset_tag_created'
  | 'workspace.asset_tag_create_failed'
  | 'workspace.asset_archive_started'
  | 'workspace.asset_archived'
  | 'workspace.asset_archive_failed'
  | 'workspace.asset_restore_started'
  | 'workspace.asset_restored'
  | 'workspace.asset_restore_failed'
	  | 'workspace.asset_delete_started'
	  | 'workspace.asset_deleted'
	  | 'workspace.asset_delete_failed'
	  | 'workspace.asset_checkout_started'
	  | 'workspace.asset_checked_out'
	  | 'workspace.asset_checkout_failed'
	  | 'workspace.asset_return_started'
	  | 'workspace.asset_returned'
  | 'workspace.asset_return_failed'
	  | 'workspace.asset_operation_apply_started'
	  | 'workspace.asset_operation_applied'
	  | 'workspace.asset_operation_apply_failed'
	  | 'workspace.asset_checkout_history_load_started'
	  | 'workspace.asset_checkout_history_loaded'
	  | 'workspace.asset_checkout_history_load_failed'
	  | 'workspace.checked_out_assets_load_started'
	  | 'workspace.checked_out_assets_loaded'
	  | 'workspace.checked_out_assets_load_failed'
	  | 'workspace.asset_attachments_load_started'
  | 'workspace.asset_attachments_loaded'
  | 'workspace.asset_attachments_load_failed'
  | 'workspace.asset_attachment_upload_started'
  | 'workspace.asset_attachment_uploaded'
  | 'workspace.asset_attachment_upload_failed'
  | 'workspace.search_started'
  | 'workspace.search_failed'
  | 'workspace.search_completed'
  | 'workspace.browse_started'
  | 'workspace.browse_completed'
  | 'workspace.browse_failed'
  | 'workspace.import_jobs_load_started'
  | 'workspace.import_jobs_loaded'
  | 'workspace.import_jobs_load_failed'
  | 'workspace.import_job_preview_started'
  | 'workspace.import_job_preview_completed'
  | 'workspace.import_job_preview_failed'
  | 'workspace.import_job_start_started'
  | 'workspace.import_job_started'
  | 'workspace.import_job_start_failed'
  | 'workspace.import_job_cancel_started'
  | 'workspace.import_job_cancel_requested'
  | 'workspace.import_job_cancel_failed'
  | 'workspace.import_job_history_remove_started'
  | 'workspace.import_job_history_removed'
  | 'workspace.import_job_history_remove_failed'
  | 'workspace.access_grants_load_started'
  | 'workspace.access_grants_loaded'
  | 'workspace.access_grants_load_failed'
  | 'workspace.access_grant_started'
  | 'workspace.access_granted'
  | 'workspace.access_grant_failed'
  | 'workspace.access_revoke_started'
  | 'workspace.access_revoked'
  | 'workspace.access_revoke_failed'
  | 'workspace.access_invitations_load_started'
  | 'workspace.access_invitations_loaded'
  | 'workspace.access_invitations_load_failed'
  | 'workspace.access_invitation_create_started'
  | 'workspace.access_invitation_created'
  | 'workspace.access_invitation_create_failed'
  | 'workspace.access_invitation_expiration_started'
  | 'workspace.access_invitation_expiration_updated'
  | 'workspace.access_invitation_expiration_failed'
  | 'workspace.access_invitation_cancel_started'
  | 'workspace.access_invitation_cancelled'
  | 'workspace.access_invitation_cancel_failed'
  | 'workspace.access_invitation_delete_started'
  | 'workspace.access_invitation_deleted'
  | 'workspace.access_invitation_delete_failed'
  | 'workspace.audit_load_started'
  | 'workspace.audit_loaded'
  | 'workspace.audit_load_failed';

export interface WorkspaceObserver {
  record(eventName: WorkspaceEventName, attributes?: Record<string, string | number | boolean>): void;
}

export class InMemoryWorkspaceObserver implements WorkspaceObserver {
  readonly events: Array<{ eventName: WorkspaceEventName; attributes: Record<string, string | number | boolean> }> = [];

  record(eventName: WorkspaceEventName, attributes: Record<string, string | number | boolean> = {}): void {
    this.events.push({ eventName, attributes });
  }
}
