package agentmodel

const (
	RealtimeVoiceEventTranscriptFinal             = "transcript.final"
	RealtimeVoiceEventAgentProgress               = "agent.progress"
	RealtimeVoiceEventAgentDiagnostic             = "agent.diagnostic"
	RealtimeVoiceEventToolCallStarted             = "tool.call.started"
	RealtimeVoiceEventToolCallCompleted           = "tool.call.completed"
	RealtimeVoiceEventToolCallFailed              = "tool.call.failed"
	RealtimeVoiceEventActionPlanProposed          = "action.plan.proposed"
	RealtimeVoiceEventActionPlanApproved          = "action.plan.approved"
	RealtimeVoiceEventActionPlanCancelled         = "action.plan.cancelled"
	RealtimeVoiceEventActionPlanExecuted          = "action.plan.executed"
	RealtimeVoiceEventActionPlanFailed            = "action.plan.failed"
	RealtimeVoiceEventAssistantResponseStarted    = "assistant.response.started"
	RealtimeVoiceEventAssistantResponseCompleted  = "assistant.response.completed"
	RealtimeVoiceEventTextToSpeechAudioStarted    = "tts.audio.started"
	RealtimeVoiceEventTextToSpeechAudioChunk      = "tts.audio.chunk"
	RealtimeVoiceEventTextToSpeechAudioCompleted  = "tts.audio.completed"
	RealtimeVoiceEventSessionCompleted            = "session.completed"
	RealtimeVoiceToolSearchAuthorizedAssets       = "search_authorized_assets"
	RealtimeVoiceToolGetInventoryVocabulary       = "get_inventory_vocabulary"
	RealtimeVoiceToolGetAssetDetail               = "get_asset_detail"
	RealtimeVoiceToolListAuthorizedAssets         = "list_authorized_assets"
	RealtimeVoiceToolListAssetAuditHistory        = "list_asset_audit_history"
	RealtimeVoiceToolListCheckedOutAssets         = "list_checked_out_assets"
	RealtimeVoiceToolListAssetCheckoutHistory     = "list_asset_checkout_history"
	RealtimeVoiceSearchAuthorizedAssetsPublicName = "Search inventory"
	RealtimeVoiceGetAssetDetailPublicName         = "Inspect item"
	RealtimeVoiceListAuthorizedAssetsPublicName   = "List inventory"
	RealtimeVoiceListAssetAuditHistoryPublicName  = "Check history"
	RealtimeVoiceListCheckedOutAssetsPublicName   = "List checked out"
	RealtimeVoiceListCheckoutHistoryPublicName    = "Checkout history"
	RealtimeVoiceFailureSpeechToText              = "speech_to_text_failed"
	RealtimeVoiceFailureLanguageInference         = "language_inference_failed"
	RealtimeVoiceFailureTextToSpeech              = "text_to_speech_failed"
	RealtimeVoiceToolTurnBudget                   = 6
	RealtimeVoiceProgressUnderstanding            = "understanding"
	RealtimeVoiceProgressExploring                = "exploring"
	RealtimeVoiceProgressPlanning                 = "planning"
	RealtimeVoiceProgressReviewing                = "reviewing"
	RealtimeVoiceProgressAnswering                = "answering"
	RealtimeVoiceProgressRecovering               = "recovering"
)
