import { useState, type RefObject } from 'react';
import { Modal, Pressable, StyleSheet, Text, View, type TextInput } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Check, ChevronDown } from 'lucide-react-native';
import type { CustomAssetTypeDefinition, CustomFieldApplicability, CustomFieldType } from '../../domain/customization/Customization';
import { suggestedCustomizationKey } from '../../domain/customization/Customization';
import { useAppearancePalette } from '../theme/AppearanceContext';
import { radius, spacing, type MobileColorPalette } from '../theme/tokens';
import { SettingsSeparator } from '../screens/SettingsList';
import { AppTextInput } from './AppTextInput';

export function CustomizationFieldControls(props: { readonly applicability: CustomFieldApplicability; readonly canMutate: boolean; readonly eligibleTypes: readonly CustomAssetTypeDefinition[]; readonly enumOptions: readonly string[]; readonly fieldType: CustomFieldType; readonly mode: 'create' | 'edit'; readonly newOption: string; readonly onApplicability: (value: CustomFieldApplicability) => void; readonly onEnumOptions: (value: readonly string[]) => void; readonly onFieldType: (value: CustomFieldType) => void; readonly onNewOption: (value: string) => void; readonly onTargets: (value: readonly string[]) => void; readonly targetIds: readonly string[] }) {
  const styles = createStyles(useAppearancePalette()); const types: readonly CustomFieldType[] = ['text', 'number', 'boolean', 'date', 'url', 'enum'];
  const selectedTypes = props.eligibleTypes.filter((type) => props.targetIds.includes(type.id));
  const availableTypes = props.eligibleTypes.filter((type) => !props.targetIds.includes(type.id));
  const unavailableTargetCount = props.targetIds.length - selectedTypes.length;
  return <>
    <View style={styles.formRow}><Text style={styles.label}>Type</Text>{props.mode === 'edit' ? <Text style={styles.lockedValue}>{capitalize(props.fieldType)}</Text> : <SingleChoicePicker disabled={!props.canMutate} label="Type" onChange={props.onFieldType} options={types.map((value) => ({ label: capitalize(value), value }))} value={props.fieldType} />}</View>
    {props.fieldType === 'enum' ? <View style={styles.formRow}><Text style={styles.label}>Options</Text>{props.enumOptions.map((option) => <Text key={option} style={styles.lockedValue}>{option}{props.mode === 'edit' ? ' · Existing' : ''}</Text>)}{props.enumOptions.length === 0 ? <Text accessibilityLiveRegion="polite" style={styles.validationText}>Add at least one option.</Text> : null}{props.canMutate ? <View style={styles.inline}><AppTextInput accessibilityLabel="New enum option" onChangeText={props.onNewOption} placeholder="Add option" style={styles.input} value={props.newOption} /><Pressable accessibilityRole="button" onPress={() => { const next = suggestedCustomizationKey(props.newOption); if (next && !props.enumOptions.includes(next)) props.onEnumOptions([...props.enumOptions, next]); props.onNewOption(''); }} style={styles.inlineAction}><Text style={styles.inlineActionText}>Add</Text></Pressable></View> : null}</View> : null}
    <View style={styles.formRow}><Text style={styles.label}>Applies to</Text>{props.mode === 'edit' ? props.applicability === 'all_assets' ? <Text style={styles.lockedValue}>All assets</Text> : <><Text style={styles.lockedValue}>Selected asset types</Text>{props.canMutate ? <Choice disabled={false} label="Expand to all assets" onPress={() => props.onApplicability('all_assets')} selected={false} /> : null}</> : <SingleChoicePicker disabled={!props.canMutate} label="Applies to" onChange={props.onApplicability} options={[{ label: 'All assets', value: 'all_assets' }, { label: 'Selected asset types', value: 'custom_asset_types' }]} value={props.applicability} />}</View>
    {props.applicability === 'custom_asset_types' ? <View style={styles.formRow}><Text style={styles.label}>Asset types</Text>{selectedTypes.map((type) => <Text key={type.id} style={styles.lockedValue}>{`${type.displayName}${type.scope === 'tenant' ? ' · Inherited' : ''}${props.mode === 'edit' ? ' · Existing' : ''}`}</Text>)}{unavailableTargetCount > 0 ? <Text style={styles.lockedValue}>{`${unavailableTargetCount} existing asset ${unavailableTargetCount === 1 ? 'type is' : 'types are'} unavailable`}</Text> : null}{props.canMutate ? availableTypes.map((type) => <Choice disabled={false} key={type.id} label={`${props.mode === 'edit' ? 'Add ' : ''}${type.displayName}${type.scope === 'tenant' ? ' · Inherited' : ''}`} onPress={() => props.onTargets([...props.targetIds, type.id])} selected={false} />) : null}{props.targetIds.length === 0 && props.canMutate ? <Text accessibilityLiveRegion="polite" style={styles.validationText}>Choose at least one asset type.</Text> : null}{props.eligibleTypes.length === 0 && props.targetIds.length === 0 ? <Text style={styles.readOnly}>No active asset types are available.</Text> : null}</View> : null}
  </>;
}

export function CustomizationLabeledInput({ editable, error, inputRef, label, multiline = false, onChangeText, required = false, value }: { readonly editable: boolean; readonly error?: string; readonly inputRef?: RefObject<TextInput | null>; readonly label: string; readonly multiline?: boolean; readonly onChangeText: (value: string) => void; readonly required?: boolean; readonly value: string }) { const styles = createStyles(useAppearancePalette()); return <View style={styles.formRow}><View style={styles.labelRow}><Text style={styles.label}>{label}</Text>{required ? <Text style={styles.required}>Required</Text> : null}</View><AppTextInput accessibilityHint={error ?? (required ? 'Required' : undefined)} accessibilityLabel={label} editable={editable} multiline={multiline} onChangeText={onChangeText} ref={inputRef} style={[styles.input, multiline && styles.multiline, !editable && styles.disabled]} value={value} />{error ? <Text accessibilityLiveRegion="polite" style={styles.validationText}>{error}</Text> : null}</View>; }
export function CustomizationReadOnlyValue({ label, value }: { readonly label: string; readonly value: string }) { const styles = createStyles(useAppearancePalette()); return <View style={styles.formRow}><Text style={styles.label}>{label}</Text><Text selectable style={styles.readOnlyValue}>{value}</Text></View>; }

function SingleChoicePicker<Value extends string>({ disabled, label, onChange, options, value }: { readonly disabled: boolean; readonly label: string; readonly onChange: (value: Value) => void; readonly options: readonly { readonly label: string; readonly value: Value }[]; readonly value: Value }) {
  const [open, setOpen] = useState(false); const colors = useAppearancePalette(); const styles = createStyles(colors);
  const selected = options.find((option) => option.value === value)?.label ?? value;
  return <><Pressable accessibilityLabel={`Choose ${label}. Current value ${selected}`} accessibilityRole="button" accessibilityState={{ disabled }} disabled={disabled} onPress={() => setOpen(true)} style={styles.choiceDisclosure}><Text style={styles.choiceDisclosureText}>{selected}</Text><ChevronDown color={colors.textMuted} size={18} /></Pressable>{open ? <Modal animationType="slide" onRequestClose={() => setOpen(false)} presentationStyle="pageSheet" visible><SafeAreaView edges={['bottom']} style={styles.choiceModal}><View style={styles.choiceModalHeader}><Text accessibilityRole="header" style={styles.choiceModalTitle}>Choose {label.toLocaleLowerCase()}</Text><Pressable accessibilityRole="button" onPress={() => setOpen(false)} style={styles.choiceModalDone}><Text style={styles.actionText}>Done</Text></Pressable></View><View style={styles.choiceModalGroup}>{options.map((option, index) => <View key={option.value}>{index ? <SettingsSeparator /> : null}<Pressable accessibilityRole="radio" accessibilityState={{ checked: option.value === value }} onPress={() => { onChange(option.value); setOpen(false); }} style={styles.choiceModalRow}>{option.value === value ? <Check color={colors.action} size={18} /> : <View style={styles.choiceCheckSpace} />}<Text style={styles.choiceText}>{option.label}</Text></Pressable></View>)}</View></SafeAreaView></Modal> : null}</>;
}

function Choice({ disabled, label, onPress, selected }: { readonly disabled: boolean; readonly label: string; readonly onPress: () => void; readonly selected: boolean }) { const colors = useAppearancePalette(); const styles = createStyles(colors); return <Pressable accessibilityRole="radio" accessibilityState={{ checked: selected, disabled }} disabled={disabled} onPress={onPress} style={[styles.choice, selected && styles.choiceSelected, disabled && styles.disabled]}>{selected ? <Check color={colors.action} size={17} /> : null}<Text style={styles.choiceText}>{label}</Text></Pressable>; }
function capitalize(value: string) { return value.charAt(0).toUpperCase() + value.slice(1).replaceAll('_', ' '); }

function createStyles(colors: MobileColorPalette) { return StyleSheet.create({
  formRow: { gap: spacing.sm, padding: spacing.md }, labelRow: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between' }, label: { color: colors.text, fontSize: 15, fontWeight: '700' }, required: { color: colors.textMuted, fontSize: 13 }, input: { backgroundColor: colors.surface, borderColor: colors.border, borderRadius: radius.md, borderWidth: 1, color: colors.text, flex: 1, fontSize: 16, minHeight: 44, paddingHorizontal: spacing.sm, paddingVertical: spacing.sm }, multiline: { minHeight: 100, textAlignVertical: 'top' }, disabled: { opacity: 0.55 }, validationText: { color: colors.danger, fontSize: 13 }, readOnly: { color: colors.textMuted, fontSize: 14, lineHeight: 20 }, readOnlyValue: { color: colors.text, fontSize: 17, lineHeight: 23 }, choice: { alignItems: 'center', borderColor: colors.border, borderRadius: radius.md, borderWidth: 1, flexDirection: 'row', gap: spacing.sm, minHeight: 44, paddingHorizontal: spacing.sm }, choiceSelected: { borderColor: colors.action, borderWidth: 2 }, choiceText: { color: colors.text, flex: 1, fontSize: 15 }, lockedValue: { color: colors.text, fontSize: 15, minHeight: 30 }, choiceDisclosure: { alignItems: 'center', borderColor: colors.border, borderRadius: radius.md, borderWidth: 1, flexDirection: 'row', justifyContent: 'space-between', minHeight: 44, paddingHorizontal: spacing.sm }, choiceDisclosureText: { color: colors.text, fontSize: 16 }, choiceModal: { backgroundColor: colors.background, flex: 1, padding: spacing.md }, choiceModalHeader: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between', minHeight: 52 }, choiceModalTitle: { color: colors.text, flex: 1, fontSize: 22, fontWeight: '800' }, choiceModalDone: { alignItems: 'center', justifyContent: 'center', minHeight: 44, minWidth: 54 }, choiceModalGroup: { backgroundColor: colors.surface, borderRadius: radius.md, overflow: 'hidden' }, choiceModalRow: { alignItems: 'center', flexDirection: 'row', gap: spacing.sm, minHeight: 52, paddingHorizontal: spacing.md }, choiceCheckSpace: { height: 18, width: 18 }, inline: { alignItems: 'center', flexDirection: 'row', gap: spacing.sm }, inlineAction: { alignItems: 'center', justifyContent: 'center', minHeight: 44, minWidth: 54 }, inlineActionText: { color: colors.action, fontSize: 15, fontWeight: '700' }, actionText: { color: colors.action, fontSize: 15, fontWeight: '700' }
}); }
