import {afterEach,expect,it} from 'vitest';
import {mount,tick,unmount} from 'svelte';
import InventoryPrintingSettings from './InventoryPrintingSettings.svelte';
import {FakePrintingRepository} from '$lib/fakes/printingRepository';
import {SessionPrintIntents} from '$lib/application/printing/manualPrint';
let component:ReturnType<typeof mount>|undefined;
afterEach(async()=>{if(component)await unmount(component);component=undefined;document.body.innerHTML='';});
async function settle(){for(let i=0;i<10;i++){await Promise.resolve();await tick();}}
function button(text:string){return [...document.querySelectorAll<HTMLButtonElement>('button')].find(b=>b.textContent?.trim()===text);}
async function fixture(canPrint=true){const repository=new FakePrintingRepository();repository.queued.set('prior',{id:'prior',assetId:'asset',printerId:'printer',status:'failed',revision:5,copies:1,completedCopies:0,reason:'response_lost',attemptOutcome:'uncertain',resolution:{reportedOutcome:'unknown',resolvedBy:'editor',resolvedAt:'2026-10-03T12:02:00Z'},createdAt:'2026-10-03T12:00:00Z'});const intents=new SessionPrintIntents(repository,()=> 'reprint-key');component=mount(InventoryPrintingSettings,{target:document.body,props:{scope:repository.scope,repository,intents,canConfigure:false,canPrint}});await settle();return repository;}
it('opens an explicit preview before a linked reprint and resumes a lost response after dismissal',async()=>{const repository=await fixture();button('Print another label')!.click();await settle();expect(repository.queued.size).toBe(1);button('Preview label')!.click();await settle();repository.loseNextJobResponse=true;button('Print label')!.click();await settle();expect(repository.queued.size).toBe(2);expect(repository.queued.get('job-2')!.predecessor).toBe('prior');document.querySelector<HTMLButtonElement>('[data-slot="dialog-close"]')!.click();await settle();button('Print another label')!.click();await settle();button('Retry the same print request')!.click();await settle();expect(repository.queued.size).toBe(2);});
it('does not expose reprinting to viewers or for unresolved jobs',async()=>{const repository=await fixture(false);expect(button('Print another label')).toBeUndefined();repository.queued.get('prior')!.status='uncertain';button('Refresh status')!.click();await settle();expect(button('Print another label')).toBeUndefined();});
it('hides reprint from editors while physical output is still unresolved',async()=>{const repository=await fixture();Object.assign(repository.queued.get('prior')!,{status:'uncertain',resolution:undefined});button('Refresh status')!.click();await settle();expect(button('Print another label')).toBeUndefined();expect(repository.queued.size).toBe(1);});
