import {afterEach,expect,it} from 'vitest';
import {flushSync,mount,tick,unmount} from 'svelte';
import InventoryPrintingSettings from './InventoryPrintingSettings.svelte';
import {FakePrintingRepository} from '$lib/fakes/printingRepository';
import type {PrintJob} from '$lib/domain/printing';
let component:ReturnType<typeof mount>|undefined;
afterEach(async()=>{if(component)await unmount(component);component=undefined;document.body.innerHTML='';});
async function settle(){for(let i=0;i<8;i++){await Promise.resolve();await tick();}}
function button(text:string){return [...document.querySelectorAll<HTMLButtonElement>('button')].find(b=>b.textContent?.trim()===text);}
function uncertain():PrintJob{return {id:'job',printerId:'printer',assetId:'asset',status:'uncertain',revision:3,copies:1,completedCopies:0,reason:'response_lost',attemptOutcome:'uncertain',createdAt:'2026-10-03T12:00:00Z'};}
async function start(repository:FakePrintingRepository,canPrint=true){component=mount(InventoryPrintingSettings,{target:document.body,props:{scope:repository.scope,repository,canConfigure:false,canPrint}});await settle();}
async function selectOutcome(){const trigger=document.getElementById('resolution-outcome-job')!;trigger.focus();trigger.dispatchEvent(new KeyboardEvent('keydown',{key:'Enter',bubbles:true,cancelable:true}));flushSync();await settle();const option=[...document.querySelectorAll<HTMLElement>('[role="option"]')].find(n=>n.textContent?.trim()==='I saw the label print')!;option.dispatchEvent(new PointerEvent('pointerup',{pointerType:'mouse',bubbles:true,cancelable:true}));flushSync();await settle();}
it('waits for current-attempt idle evidence and keeps viewers from resolving',async()=>{const repository=new FakePrintingRepository();repository.queued.set('job',uncertain());await start(repository,false);expect(button('Resolve this job')).toBeUndefined();expect(document.body.textContent).toContain('must confirm the printer is idle');repository.queued.get('job')!.idleConfirmedAt='2026-10-03T12:01:00Z';button('Refresh status')!.click();await settle();expect(button('Resolve this job')).toBeUndefined();expect(repository.queued.get('job')!.status).toBe('uncertain');});
it('requires acknowledgement and retries a lost resolution without rewriting physical evidence or printing',async()=>{const repository=new FakePrintingRepository();repository.queued.set('job',{...uncertain(),idleConfirmedAt:'2026-10-03T12:01:00Z'});repository.loseNextResolutionResponse=true;await start(repository);expect(button('Resolve this job')!.disabled).toBe(true);await selectOutcome();expect(button('Resolve this job')!.disabled).toBe(true);(document.getElementById('resolution-ack-job') as HTMLInputElement).click();await settle();button('Resolve this job')!.click();await settle();expect(repository.queued.get('job')!.resolution?.reportedOutcome).toBe('printed');expect(document.querySelector('[role="alert"]')).not.toBeNull();expect((document.getElementById('resolution-outcome-job') as HTMLButtonElement).disabled).toBe(true);button('Retry the same resolution')!.click();await settle();expect(document.body.textContent).toContain('Resolved by user — output unconfirmed');expect(document.body.textContent).toContain('User report: I saw the label print');expect(repository.queued.get('job')!.attemptOutcome).toBe('uncertain');expect(repository.queued.get('job')!.completedCopies).toBe(0);expect(repository.queued.size).toBe(1);});
