package app

import (
	"flag"
	"github.com/stuffstash/stuff-stash/cli/internal/ports"
	"io"
)

func optionFlags(o *Options) *flag.FlagSet {
	flags := flag.NewFlagSet("stuffstash", flag.ContinueOnError)
	flags.SetOutput(io.Discard)
	flags.StringVar(&o.FilePath, "file", "", "binary input path, or - for supported stdin uploads")
	flags.StringVar(&o.Transfer, "transfer", "direct", "attachment transfer: direct or api")
	flags.StringVar(&o.Variant, "variant", "", "thumbnail size: small, medium, or large")
	flags.StringVar(&o.PrinterAdapterID, "adapter", "", "printer adapter ID from the catalog")
	flags.StringVar(&o.PrinterPresetVersion, "preset-version", "", "printer media preset version")
	flags.BoolVar(&o.AllInventories, "all-inventories", false, "search all inventories in the selected household")
	flags.StringVar(&o.InvitationEmail, "email", "", "invitation email address")
	flags.StringVar(&o.InvitationRole, "role", "", "invitation role: viewer or editor")
	customizationFlags(flags, o)
	expirationFlags(flags, o)
	printSubmissionFlags(flags, o)
	flags.StringVar(&o.InvitationStatus, "status", "", "invitation status or unsettled connector-attempt filter")
	flags.Func("view", "asset activity: changes or all", func(v string) error { o.ActivityView = ports.ActivityView(v); return nil })
	flags.Func("details", "checkout or return notes", func(value string) error { o.Details = &value; return nil })
	flags.Func("tag-color", "tag color as #RRGGBB, or an empty value", func(value string) error { o.TagColor = &value; return nil })
	flags.Func("key", "stable key for a new tag or definition", func(value string) error { o.TagKey = &value; return nil })
	flags.StringVar(&o.Lifecycle, "lifecycle", "", "asset lifecycle: active, archived, or all")
	flags.StringVar(&o.Sort, "sort", "", "asset sort: id_asc or updated_desc")
	flags.StringVar(&o.RequestID, "request-id", "", "API request correlation ID")
	flags.StringVar(&o.InputPath, "input", "", "JSON request file, or - for stdin")
	flags.StringVar(&o.Color, "color", "auto", "color output: auto, always, or never")
	flags.StringVar(&o.Selection.Context, "context", o.Selection.Context, "saved context name")
	flags.BoolVar(&o.Yes, "yes", false, "confirm the requested action without a prompt")
	flags.StringVar(&o.Timezone, "timezone", "", "notification timezone, such as America/New_York")
	flags.Int64Var(&o.Revision, "revision", -1, "current resource revision")
	flags.BoolVar(&o.UnreadOnly, "unread-only", false, "show unread notifications only")
	flags.BoolVar(&o.NoInput, "no-input", false, "do not ask for input")
	flags.StringVar(&o.Format, "format", "png", "label file format: png or pdf")
	flags.StringVar(&o.OutputPath, "output", "", "new private label file path")
	flags.StringVar(&o.MediaPreset, "media-preset", "", "authorized media preset ID")
	flags.Float64Var(&o.WidthMM, "width-mm", 0, "catalog physical label width in millimeters")
	flags.Float64Var(&o.HeightMM, "height-mm", 0, "catalog physical label height in millimeters")
	flags.StringVar(&o.LabelSize, "label-size", "", "supported printer media preset ID")
	flags.StringVar(&o.PrinterID, "printer", "", "registered printer destination")
	flags.StringVar(&o.TemplateID, "template", "", "label template ID")
	flags.UintVar(&o.TemplateVersion, "template-version", 0, "label template version")
	flags.IntVar(&o.Copies, "copies", 1, "number of label copies")
	flags.BoolVar(&o.PrintLabel, "print-label", false, "create a label job with the new asset")
	flags.BoolVar(&o.ShowReference, "show-reference", false, "show label reference")
	flags.StringVar(&o.ConnectorID, "connector", o.ConnectorID, "registered connector ID")
	flags.StringVar(&o.ConnectorName, "name", "", "household, inventory, connector, or definition display name")
	flags.StringVar(&o.JournalDirectory, "journal-dir", o.JournalDirectory, "persistent print recovery directory")
	flags.StringVar(&o.Server, "server", o.Server, "Stuff Stash API URL")
	flags.StringVar(&o.Scope.Tenant, "tenant", o.Scope.Tenant, "tenant ID")
	flags.StringVar(&o.Scope.Inventory, "inventory", o.Scope.Inventory, "inventory ID")
	flags.StringVar(&o.Title, "title", "", "asset title")
	flags.StringVar(&o.Kind, "kind", "", "asset kind")
	flags.StringVar(&o.Parent, "parent", "", "parent ID or root")
	flags.StringVar(&o.IdempotencyKey, "idempotency-key", "", "logical mutation key")
	flags.BoolVar(&o.AllPages, "all", false, "read all remaining pages; does not create an atomic snapshot")
	flags.Int64Var(&o.Page.Limit, "limit", 50, "page size")
	flags.StringVar(&o.Page.Cursor, "cursor", "", "page cursor")
	flags.BoolVar(&o.JSON, "json", false, "JSON output")
	flags.BoolVar(&o.DeviceCode, "device-code", false, "sign in from another device")
	flags.BoolVar(&o.Help, "help", false, "show help")
	return flags
}
