#!/usr/bin/env python3
"""Offline runtime registry/renderer export with narrowly owned deterministic docs."""
import argparse
import hashlib
import html
import json
import os
from pathlib import Path
import re
import subprocess
import tempfile

ROOT = Path(__file__).resolve().parents[1]
PAGES = Path('docs/src/content/docs/printing')
ASSETS = Path('docs/src/assets/printing/generated')
MANIFEST = ASSETS / 'manifest.json'
PAGE_NAMES = {'supported-printers.mdx', 'label-sizes.mdx', 'templates.mdx'}
SAFE_ID = re.compile(r'[a-z0-9][a-z0-9-]{0,79}\Z')


def owned(path):
    return path.parent == ASSETS and path.name != 'manifest.json' or path.parent == PAGES and path.name in PAGE_NAMES


def text(value):
    # Descriptor text is content, never raw MDX/JSX syntax.
    return html.escape(str(value), quote=True).replace('{', '&#123;').replace('}', '&#125;').replace('|', '&#124;').replace('\n', ' ')


def header(title):
    return f'---\ntitle: {title}\n---\n\n{{/* Generated by make printing-docs-generate. Do not edit manually. */}}\n\n'


def collect_media(printers):
    seen = set(); media = {}
    for printer in printers:
        if not SAFE_ID.fullmatch(printer['id']) or printer['id'] in seen:
            raise ValueError('Invalid or duplicated executable adapter ID')
        seen.add(printer['id'])
        if not printer['platforms'] or not printer['transport'] or 'image/png' not in printer['formats']:
            raise ValueError('Unsupported declared printer capability')
        for preset in printer['media_presets']:
            key = (preset['preset_id'], preset['version'])
            if not SAFE_ID.fullmatch(key[0]) or not isinstance(key[1], int) or key[1] < 1:
                raise ValueError('Invalid media identity')
            if key in media and media[key] != preset:
                raise ValueError('Conflicting shared media preset: ' + key[0])
            media[key] = preset
    return [media[key] for key in sorted(media)]


def generate(printers, catalog, rendered):
    media = collect_media(printers)
    if catalog['schema_version'] != 1 or catalog['media'] != media:
        raise ValueError('Renderer and executable printer media catalogs differ')
    files = {}
    printers = sorted(printers, key=lambda p: p['id'])
    page = header('Supported printers')
    page += 'These adapters are included in the candidate source build. A catalog entry does not establish physical-device verification or availability in an older CLI release. See [setup and release status](../setup/) and [CLI installation](../../cli/).\n\n'
    page += '| Printer | Host / connection | Label presets | Physical verification |\n| --- | --- | --- | --- |\n'
    for printer in printers:
        sizes = ', '.join(f"{text(m['preset_id'])} v{m['version']}" for m in printer['media_presets'])
        status = 'Verified' if printer['physically_verified'] else 'Not yet verified'
        page += f"| {text(printer['model'])} | {text(', '.join(printer['platforms']))} / {text(printer['transport'])} | {sizes} | {status} |\n"
    page += '\n[Label sizes](../label-sizes/) · [Layouts and examples](../templates/).\n\n'
    for printer in printers:
        page += f"## {text(printer['model'])}\n\n"
        page += ('The adapter can request wake-up.\n\n' if printer['wake'] else 'Automatic wake-up is not available in this adapter. Keep the printer powered on or attend to it when required.\n\n')
        page += f"Completion evidence: `{text(printer['completion_evidence'])}`. A connected computer alone does not establish that its printer is ready.\n\n"
    files[str(PAGES / 'supported-printers.mdx')] = page.encode()
    page = header('Label sizes')
    page += 'Choose the loaded size when registering a printer. Update that setting after changing rolls; the initial setup trusts your selection. Queued labels keep their original size. Templates are selected independently.\n\n'
    page += '| Preset | Physical size | Raster | Resolution |\n| --- | --- | --- | --- |\n'
    for m in media:
        page += f"| {text(m['preset_id'])} v{m['version']} | {m['width_micrometers']/1000:g} × {m['height_micrometers']/1000:g} mm | {m['raster_width']} × {m['raster_height']} dots | {m['resolution_dpi']} dpi |\n"
    page += '\nThe 29 × 90 mm Brother stock uses a manufacturer-defined 89.8 mm feed dimension. Printable margins and feed orientation come from the same profile used by the adapter and renderer. Screen examples are not physical-size rulers.\n\n[See template examples](../templates/).\n'
    files[str(PAGES / 'label-sizes.mdx')] = page.encode()
    page = header('Label templates')
    examples = catalog['examples']
    templates = {(t['id'], t['version']): t for t in catalog['templates']}
    if len(templates) != len(catalog['templates']):
        raise ValueError('Duplicate renderer template identity')
    for index, ex in enumerate(examples):
        if (ex['template']['id'], ex['template']['version']) not in templates or ex['media'] not in media:
            raise ValueError('Fixture refers to an unknown template or media')
        for key in ['png', 'display_png', 'pdf']:
            name = ex[key]
            if Path(name).name != name or not (rendered / name).is_file():
                raise ValueError('Missing or unsafe renderer fixture filename')
            files[str(ASSETS / name)] = (rendered / name).read_bytes()
        page += f"import preview{index} from '../../../assets/printing/generated/{ex['display_png']}';\n"
        page += f"import original{index} from '../../../assets/printing/generated/{ex['png']}?url&no-inline';\n"
    page += '\nThese synthetic examples are produced by the production renderer, using a reserved example URL. They do not link to real inventory. The display PNG only rotates the original raster into reading orientation; it does not redraw or resize it.\n\nLong titles or URLs can exceed a layout’s limits. The renderer reports incompatible content instead of silently clipping it. Choose another layout or shorter content.\n\n'
    for index, ex in enumerate(examples):
        template = templates[(ex['template']['id'], ex['template']['version'])]
        reference = 'shown' if ex['template']['options']['show_reference'] else 'hidden'
        m = ex['media']; size = f"{m['width_micrometers']/1000:g} × {m['height_micrometers']/1000:g} mm"
        page += f"## {text(template['name'])} — reference {reference}\n\n{text(template['purpose'])}\n\nTemplate v{template['version']}; {size}; reference {reference}.\n\n"
        alt = text(f"{template['name']}, {size}, reference {reference}; synthetic Garage tools label")
        page += f'<img src={{preview{index}.src}} width="{ex["display_width_pixels"]}" height="{ex["display_height_pixels"]}" alt="{alt}" style="display:block;max-width:100%;height:auto;background:white;border:1px solid #ccc" />\n\n'
        page += f'<a href={{original{index}}} download>Download original printer PNG</a>\n\n'
    files[str(PAGES / 'templates.mdx')] = page.encode()
    files[str(ASSETS / 'catalog.json')] = (json.dumps(dict(printers=printers, labels=catalog), sort_keys=True, indent=2) + '\n').encode()
    manifest = {'schema_version': 1, 'files': {path: hashlib.sha256(data).hexdigest() for path, data in sorted(files.items())}}
    files[str(MANIFEST)] = (json.dumps(manifest, indent=2) + '\n').encode()
    return files


def export_runtime():
    env = dict(os.environ, GOPROXY='off', GOSUMDB='off', GOTOOLCHAIN='local')
    # Downloads/toolchain provisioning are build setup, never part of generation.
    printers = json.loads(subprocess.check_output(['go','run','-mod=readonly','-buildvcs=false','./apps/cli/cmd/stuffstash','printers','catalog','--json'], cwd=ROOT, env=env))
    with tempfile.TemporaryDirectory(prefix='stuffstash-printing-export-') as temp:
        root = Path(temp)
        media = collect_media(printers)
        (root/'media.json').write_text(json.dumps({'schema_version':1,'media':media}))
        rendered = root/'rendered'
        subprocess.run(['go','run','-mod=readonly','-buildvcs=false','./apps/api/cmd/label-catalog','--media',str(root/'media.json'),'--output',str(rendered)], cwd=ROOT, env=env, check=True)
        return generate(printers, json.loads((rendered/'catalog.json').read_text()), rendered)


def apply(files, destination, check):
    old = {}
    manifest = destination / MANIFEST
    if manifest.exists():
        old = json.loads(manifest.read_text())['files']
        if any(not owned(Path(path)) for path in old):
            raise ValueError('Manifest includes an unowned path; refusing to touch it')
    discovered = set(old) | {str(MANIFEST)}
    if (destination / ASSETS).exists():
        discovered |= {str(path.relative_to(destination)) for path in (destination / ASSETS).rglob('*') if path.is_file()}
    changed = sorted(path for path in set(files) | discovered if path not in files or not (destination / path).is_file() or (destination / path).read_bytes() != files[path])
    if check:
        return changed
    # Only old manifest-owned output may be removed, never unknown files or guides.
    for path in set(old) - set(files):
        (destination / path).unlink(missing_ok=True)
    for path, data in files.items():
        target = destination / path; target.parent.mkdir(parents=True, exist_ok=True); target.write_bytes(data)
    return changed


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--check', action='store_true')
    parser.add_argument('--output', type=Path)
    args = parser.parse_args()
    files = export_runtime()
    if args.output:
        apply(files, args.output, False)
    changed = apply(files, ROOT, args.check)
    if args.check and changed:
        raise SystemExit('Generated printing docs drift. Run make printing-docs-generate and commit the output:\n' + '\n'.join(changed))


if __name__ == '__main__':
    main()
