ignoreScripts: true
allowBuilds:
  esbuild: true
  sharp: true
overrides:
  '@capsizecss/unpack': '4.0.0'
  '@emnapi/runtime': '1.10.0'
  '@types/mdx': '2.0.13'
  '@types/node': '24.13.1'
  acorn: '8.16.0'
  obug: '2.1.2'
  postcss-selector-parser: '6.1.2'
  rollup: '4.61.1'
  semver: '7.8.2'
