<script lang="ts">
  import { onDestroy, tick } from 'svelte';
  import Plus from '@lucide/svelte/icons/plus';
  import Search from '@lucide/svelte/icons/search';
  import { collectSettingsPages, filterSettingsRecords, invalidateSharedSettingsLoads, isSettingsPermissionDenied, mergeCanonicalSettingsRecord, removeCanonicalSettingsRecord, settingsKeyFromName, sharePendingSettingsLoad, sortSettingsRecords } from '$lib/application/settingsManagement';
  import { settingsResourceHref } from '$lib/application/settingsManagementNavigation';
  import { safeWorkspaceErrorMessage } from '$lib/application/workspaceSafeError';
  import { hasAccessPermission, customFieldTypes, type CustomAssetType, type CustomFieldApplicability, type CustomFieldDefinition, type CustomFieldType, type Inventory, type Tenant } from '$lib/domain/inventory';
  import type { InventoryCustomizationRepository } from '$lib/ports/inventoryCustomizationRepository';
  import type { SettingsResourceAction } from '$lib/application/workspaceRoute';
  import * as Button from '$lib/components/ui/button/index.js';
  import { Badge } from '$lib/components/ui/badge/index.js';
  import { Input } from '$lib/components/ui/input/index.js';
  import { Label } from '$lib/components/ui/label/index.js';
  import WorkspaceTaskSheet from '../action-surface/WorkspaceTaskSheet.svelte';
  import WorkspaceConfirmationDialog from '../action-surface/WorkspaceConfirmationDialog.svelte';
  import ChoiceGrid from '../ChoiceGrid.svelte';
  import SettingsCollectionState from './SettingsCollectionState.svelte';
  import { notifySuccess } from '$lib/components/ui/sonner/notifications';
  import type { WorkspaceObserver } from '$lib/observability/workspaceObserver';

  let { level, tenant, inventory = null, repository, observer, canonicalItems, lifecycle = 'active', resourceId = null, action: routeAction = null, onNavigate, onSchemaChange, onPermissionDenied }:
    { level: 'tenant' | 'inventory'; tenant: Tenant; inventory?: Inventory | null; repository: InventoryCustomizationRepository; observer: WorkspaceObserver; canonicalItems: CustomFieldDefinition[]; lifecycle?: 'active' | 'archived'; resourceId?: string | null; action?: SettingsResourceAction; onNavigate: (href: string) => void; onSchemaChange: (fields: CustomFieldDefinition[]) => void; onPermissionDenied: () => Promise<void> } = $props();
  let items = $state<CustomFieldDefinition[]>([]); let assetTypes = $state<CustomAssetType[]>([]); let loading = $state(true); let loadingMore = $state(false); let hasMore = $state(false); let nextCursor = $state<string | null>(null); let error = $state(''); let appendError = $state(''); let saving = $state(false); let query = $state(''); let loadEpoch = 0; let lastRequestKey = '';
  let displayName = $state(''); let key = $state(''); let keyManuallyEdited = $state(false); let type = $state<CustomFieldType>('text'); let applicability = $state<CustomFieldApplicability>('all_assets'); let targetIds = $state<string[]>([]); let enumOptions = $state(''); let formError = $state(''); let formErrorElement = $state<HTMLElement | null>(null); let initializedFor = $state(''); let discardOpen = $state(false);
  let selected = $derived(items.find((item) => item.id === resourceId) ?? null); let ownedSelected = $derived(selected && selected.scope === level ? selected : null);
  let canManage = $derived(level === 'tenant' ? hasAccessPermission(tenant.access, 'configure') : hasAccessPermission(inventory?.access, 'configure'));
  let canManageTenant = $derived(hasAccessPermission(tenant.access, 'configure'));
  let filtered = $derived(filterSettingsRecords(sortSettingsRecords(items), query)); let inherited = $derived(level === 'inventory' ? filtered.filter((item) => item.scope === 'tenant') : []); let local = $derived(level === 'inventory' ? filtered.filter((item) => item.scope === 'inventory') : filtered);
  let formOpen = $derived(routeAction === 'new' || routeAction === 'edit'); let confirmationOpen = $derived(routeAction === 'archive' || routeAction === 'restore' || routeAction === 'delete'); let detailOpen = $derived(Boolean(resourceId) && routeAction === null); let contextName = $derived(level === 'tenant' ? tenant.name : inventory?.name ?? 'Inventory'); let collectionHref = $derived(href());
  let targetOptions = $derived(assetTypes.filter((item) => item.lifecycleState === 'active' && (level === 'inventory' || item.scope === 'tenant')).map((item) => ({ value: item.id, label: item.displayName, description: item.scope === 'tenant' ? tenant.name : inventory?.name })));
  let dirty = $derived(displayName !== (ownedSelected?.displayName ?? '') || key !== (ownedSelected?.key ?? '') || enumOptions.trim().length > 0 || applicability !== (ownedSelected?.applicability ?? 'all_assets') || targetIds.some((id) => !ownedSelected?.customAssetTypeIds.includes(id)));
  let keyError = $derived(routeAction === 'new' && key.trim() && !/^[a-z][a-z0-9-]{0,79}$/.test(key.trim()) ? 'Key must start with a letter and use lowercase letters, numbers, or hyphens.' : '');
  onDestroy(() => { loadEpoch += 1; });
  $effect(() => { const requestKey = `${level}:${tenant.id}:${inventory?.id ?? ''}:${lifecycle}`; if (requestKey === lastRequestKey) return; lastRequestKey = requestKey; const epoch = ++loadEpoch; void load(epoch); });
  $effect(() => { if (routeAction === 'edit' && !ownedSelected) return; const marker = `${routeAction}:${resourceId ?? ''}:${ownedSelected?.displayName ?? ''}`; if (!formOpen || initializedFor === marker) return; initializedFor = marker; displayName = ownedSelected?.displayName ?? ''; key = ownedSelected?.key ?? ''; keyManuallyEdited = routeAction !== 'new'; type = ownedSelected?.type ?? 'text'; applicability = ownedSelected?.applicability ?? 'all_assets'; targetIds = [...(ownedSelected?.customAssetTypeIds ?? [])]; enumOptions = ''; formError = ''; });
  $effect(() => { if (routeAction === 'new' && formOpen && !keyManuallyEdited) key = settingsKeyFromName(displayName); });
  function href(options: { lifecycle?: 'active' | 'archived'; resourceId?: string; action?: SettingsResourceAction } = {}): string { return settingsResourceHref({ level, tenantId: tenant.id, inventoryId: inventory?.id, collection: 'fields', lifecycle: options.lifecycle ?? lifecycle, resourceId: options.resourceId, action: options.action }); }
  async function load(epoch = ++loadEpoch): Promise<void> { loading = true; error = ''; observer.record('workspace.settings_collection_load_started', { resource: 'custom_field', scope: level }); try { const fieldRequestKey = `custom-fields:${level}:${tenant.id}:${inventory?.id ?? ''}:${lifecycle}`; const fieldsPromise = sharePendingSettingsLoad(repository, fieldRequestKey, () => level === 'tenant' ? repository.listTenantCustomFieldDefinitions(tenant.id, undefined, lifecycle) : repository.listInventoryCustomFieldDefinitions(tenant.id, inventory!.id, undefined, lifecycle), true); const [fields, types] = await Promise.all([fieldsPromise, loadSupportingAssetTypes()]); if (epoch !== loadEpoch) return; items = sortSettingsRecords(fields.items); hasMore = fields.pagination.hasMore; nextCursor = fields.pagination.nextCursor; assetTypes = sortSettingsRecords(types); appendError = ''; observer.record('workspace.settings_collection_loaded', { resource: 'custom_field', scope: level, count: items.length }); } catch (caught) { if (epoch === loadEpoch) { error = safeWorkspaceErrorMessage(caught, 'Custom fields could not be loaded. Try again.'); observer.record('workspace.settings_collection_load_failed', { resource: 'custom_field', scope: level }); await handlePermissionDenied(caught, 'load'); } } finally { if (epoch === loadEpoch) loading = false; } }
  function loadSupportingAssetTypes(): Promise<CustomAssetType[]> { const requestKey = `${level}:${tenant.id}:${inventory?.id ?? ''}`; return sharePendingSettingsLoad(repository, `custom-field-supporting-types:${requestKey}`, () => collectSettingsPages((cursor) => level === 'tenant' ? repository.listTenantCustomAssetTypes(tenant.id, cursor, 'active') : repository.listInventoryCustomAssetTypes(tenant.id, inventory!.id, cursor, 'active')), true); }
  async function loadMore(): Promise<void> { if (!hasMore || !nextCursor || loadingMore) return; const epoch = loadEpoch; loadingMore = true; appendError = ''; try { const page = level === 'tenant' ? await repository.listTenantCustomFieldDefinitions(tenant.id, nextCursor, lifecycle) : await repository.listInventoryCustomFieldDefinitions(tenant.id, inventory!.id, nextCursor, lifecycle); if (epoch !== loadEpoch) return; items = sortSettingsRecords([...items, ...page.items]); hasMore = page.pagination.hasMore; nextCursor = page.pagination.nextCursor; } catch (caught) { if (epoch === loadEpoch) appendError = safeWorkspaceErrorMessage(caught, 'More custom fields could not be loaded. Try again.'); } finally { if (epoch === loadEpoch) loadingMore = false; } }
  function splitOptions(value: string): string[] { return Array.from(new Set(value.split(',').map((item) => item.trim()).filter(Boolean))); }
  function toggleTarget(id: string): void { if (ownedSelected?.customAssetTypeIds.includes(id)) return; targetIds = targetIds.includes(id) ? targetIds.filter((item) => item !== id) : [...targetIds, id]; }
  async function save(): Promise<void> {
    if (!canManage || saving) return; const name = displayName.trim(); const stableKey = key.trim(); const additions = splitOptions(enumOptions);
    if (!name || (routeAction === 'new' && !/^[a-z][a-z0-9-]{0,79}$/.test(stableKey)) || (type === 'enum' && routeAction === 'new' && additions.length === 0) || (applicability === 'custom_asset_types' && targetIds.length === 0)) { formError = !name ? 'Enter a display name.' : !stableKey ? 'Enter a stable key.' : keyError ? keyError : type === 'enum' && additions.length === 0 ? 'Add at least one list option.' : 'Select at least one asset type.'; await tick(); formErrorElement?.focus(); return; }
    saving = true; formError = ''; observer.record('workspace.settings_mutation_started', { resource: 'custom_field', action: routeAction === 'new' ? 'create' : 'update', scope: level });
    try { const saved = routeAction === 'new' ? await repository.createCustomFieldDefinition(tenant.id, inventory?.id ?? '', { scope: level, key: stableKey, displayName: name, type, enumOptions: type === 'enum' ? additions : [], applicability, customAssetTypeIds: applicability === 'custom_asset_types' ? targetIds : [] }) : ownedSelected ? await repository.updateCustomFieldDefinition(tenant.id, inventory?.id ?? '', ownedSelected.id, level, { displayName: name, ...(type === 'enum' && additions.length ? { enumOptions: [...ownedSelected.enumOptions, ...additions.filter((item) => !ownedSelected.enumOptions.includes(item))] } : {}), ...(ownedSelected.applicability === 'custom_asset_types' ? { applicability, customAssetTypeIds: applicability === 'all_assets' ? [] : targetIds } : {}) }) : null; if (!saved) throw new Error('Field unavailable.'); invalidateSharedSettingsLoads(repository, `custom-fields:${level}:${tenant.id}:${inventory?.id ?? ''}:`); items = sortSettingsRecords(routeAction === 'new' ? [...items, saved] : items.map((item) => item.id === saved.id ? saved : item)); onSchemaChange(mergeCanonicalSettingsRecord(canonicalItems, saved)); notifySuccess(routeAction === 'new' ? 'Custom field added' : 'Changes saved', { description: `${saved.displayName} is up to date.` }); observer.record('workspace.settings_mutation_succeeded', { resource: 'custom_field', action: routeAction === 'new' ? 'create' : 'update', scope: level }); onNavigate(collectionHref); }
    catch (caught) { formError = safeWorkspaceErrorMessage(caught, `Custom field was not ${routeAction === 'new' ? 'created' : 'saved'}. Try again.`); observer.record('workspace.settings_mutation_failed', { resource: 'custom_field', action: routeAction === 'new' ? 'create' : 'update', scope: level }); await handlePermissionDenied(caught, routeAction === 'new' ? 'create' : 'update'); await tick(); formErrorElement?.focus(); } finally { saving = false; }
  }
  async function lifecycleAction(): Promise<void> { if (!ownedSelected || !canManage || saving || !routeAction) return; const selectedRecord = ownedSelected; const action = routeAction; const destination = collectionHref; saving = true; formError = ''; observer.record('workspace.settings_mutation_started', { resource: 'custom_field', action, scope: level }); try { let changed: CustomFieldDefinition | null = null; if (action === 'archive') changed = await repository.archiveCustomFieldDefinition(tenant.id, inventory?.id ?? '', selectedRecord.id, level); else if (action === 'restore') changed = await repository.restoreCustomFieldDefinition(tenant.id, inventory?.id ?? '', selectedRecord.id, level); else if (action === 'delete') await repository.deleteCustomFieldDefinition(tenant.id, inventory?.id ?? '', selectedRecord.id, level); invalidateSharedSettingsLoads(repository, `custom-fields:${level}:${tenant.id}:${inventory?.id ?? ''}:`); items = items.filter((item) => item.id !== selectedRecord.id); const nextCanonical = action === 'archive' ? removeCanonicalSettingsRecord(canonicalItems, selectedRecord.id) : action === 'restore' && changed ? mergeCanonicalSettingsRecord(canonicalItems, changed) : null; observer.record('workspace.settings_mutation_succeeded', { resource: 'custom_field', action, scope: level }); onNavigate(destination); if (nextCanonical) onSchemaChange(nextCanonical); } catch (caught) { formError = safeWorkspaceErrorMessage(caught, `Custom field was not ${action === 'delete' ? 'deleted' : `${action}d`}. It remains ${lifecycle}.`); observer.record('workspace.settings_mutation_failed', { resource: 'custom_field', action, scope: level }); await handlePermissionDenied(caught, action); } finally { saving = false; } }
  function requestClose(): void { if (dirty) { discardOpen = true; return; } onNavigate(collectionHref); }
  async function handlePermissionDenied(caught: unknown, action: string): Promise<void> { if (!isSettingsPermissionDenied(caught)) return; observer.record('workspace.settings_permission_denied', { resource: 'custom_field', action, scope: level }); await onPermissionDenied(); }
  function openRow(item: CustomFieldDefinition): string { return item.scope === level ? href({ resourceId: item.id, ...(item.lifecycleState === 'active' ? { action: 'edit' as const } : {}) }) : href({ resourceId: item.id }); }
  function manageInheritedHref(item: CustomFieldDefinition): string { return settingsResourceHref({ level: 'tenant', tenantId: tenant.id, collection: 'fields', resourceId: item.id, ...(item.lifecycleState === 'active' ? { action: 'edit' as const } : {}) }); }
  const typeLabels: Record<CustomFieldType, string> = { text: 'Text', number: 'Number', boolean: 'Yes/no', date: 'Date', url: 'URL', enum: 'List' };
</script>

<section class="settings-resource-page" aria-labelledby="field-settings-title"><header class="settings-resource-header"><div><p class="settings-eyebrow">{contextName}</p><h1 id="field-settings-title">Custom fields</h1><p>{level === 'tenant' ? 'Fields shared with every inventory.' : 'Inherited and inventory-only metadata.'}</p></div>{#if canManage && lifecycle === 'active'}<Button.Root href={href({ action: 'new' })} onclick={(event) => { event.preventDefault(); onNavigate(href({ action: 'new' })); }}><Plus /> Add Field</Button.Root>{/if}</header>
<nav class="settings-lifecycle-nav" aria-label="Custom field lifecycle"><a href={href({ lifecycle: 'active' })} aria-current={lifecycle === 'active' ? 'page' : undefined} onclick={(event) => { event.preventDefault(); onNavigate(href({ lifecycle: 'active' })); }}>Active</a><a href={href({ lifecycle: 'archived' })} aria-current={lifecycle === 'archived' ? 'page' : undefined} onclick={(event) => { event.preventDefault(); onNavigate(href({ lifecycle: 'archived' })); }}>Archived</a></nav>
{#if loading && items.length === 0}<SettingsCollectionState kind="loading" title={`Loading ${lifecycle} custom fields`} message="Getting the current schema." />{:else}
{#if loading}<SettingsCollectionState kind="loading" title="Updating custom fields" message="Showing the last loaded rows while this view refreshes." />{/if}
{#if error}<SettingsCollectionState kind="error" title="Custom fields unavailable" message={error} onRetry={() => { void load(); }} />{/if}
{#if items.length > 12 || hasMore}<div class="settings-search"><Search aria-hidden="true" /><Label class="visually-hidden" for="field-settings-search">Search loaded custom fields</Label><Input id="field-settings-search" type="search" bind:value={query} placeholder="Search loaded fields" /></div>{/if}
{#if filtered.length === 0}<SettingsCollectionState kind="empty" title={query ? 'No matching loaded fields' : `No ${lifecycle} custom fields`} message={query ? hasMore ? 'No loaded rows match. Load remaining fields to complete this search.' : 'Try a different name or key.' : lifecycle === 'active' && canManage ? 'Add a field for structured asset information.' : `There are no ${lifecycle} fields here.`} />{:else}{#each level === 'inventory' ? [{ title: `From ${tenant.name}`, rows: inherited }, { title: `Only in ${inventory?.name}`, rows: local }] : [{ title: '', rows: local }] as group}{#if group.rows.length}<section class="settings-resource-group" aria-label={group.title || `${contextName} custom fields`}>{#if group.title}<h2>{group.title}</h2>{/if}<div class="settings-resource-list">{#each group.rows as item}<a class="settings-resource-row" href={openRow(item)} onclick={(event) => { event.preventDefault(); onNavigate(openRow(item)); }}><span><strong>{item.displayName}</strong><small>{typeLabels[item.type]} · {item.applicability === 'all_assets' ? 'All assets' : `${item.customAssetTypeIds.length} asset types`}</small><small>{item.key}</small></span><span class="settings-resource-meta">{#if item.scope === 'tenant' && level === 'inventory'}<Badge variant="outline">Inherited</Badge>{/if}{#if lifecycle === 'archived'}<Badge variant="secondary">Archived</Badge>{/if}</span></a>{/each}</div></section>{/if}{/each}{/if}
{#if appendError}<SettingsCollectionState kind="error" title="Could not load more" message={appendError} onRetry={() => { void loadMore(); }} />{:else if hasMore}<div class="settings-pagination"><Button.Root variant="outline" disabled={loadingMore} onclick={() => { void loadMore(); }}>{loadingMore ? 'Loading…' : 'Load more'}</Button.Root><small>More custom fields are available.</small></div>{/if}
{/if}</section>

<WorkspaceTaskSheet open={formOpen} title={routeAction === 'new' ? 'Add Field' : ownedSelected ? `Edit ${ownedSelected.displayName}` : 'Field unavailable'} description={`Managed in ${contextName}.`} busy={saving} closeHref={collectionHref} onCloseLink={(event) => { event.preventDefault(); requestClose(); }} onOpenChange={(open) => { if (!open && !saving) requestClose(); }}>
{#if !canManage}<SettingsCollectionState kind="denied" title="Read only" message="Your draft is preserved, but this account can no longer change custom fields here." />{/if}{#if routeAction === 'edit' && !ownedSelected}<SettingsCollectionState kind="error" title="Field unavailable" message="This field may be inherited, archived, or no longer available." />{:else}{#if formError}<p class="settings-form-error" role="alert" tabindex="-1" bind:this={formErrorElement}>{formError}</p>{/if}<div class="field-stack"><Label for="field-name">Display name</Label><Input id="field-name" bind:value={displayName} maxlength={120} disabled={!canManage} /></div><div class="field-stack"><Label for="field-key">Stable key</Label><Input id="field-key" value={key} disabled={!canManage} readonly={routeAction !== 'new'} oninput={(event) => { key = event.currentTarget.value; keyManuallyEdited = true; }} /><small>The key cannot change after creation.</small></div>{#if routeAction === 'new'}<fieldset class="settings-choice-field" disabled={!canManage}><legend>Field type</legend><ChoiceGrid label="Field type" options={customFieldTypes.map((value) => ({ value, label: typeLabels[value] }))} selectedValues={[type]} onSelect={(value) => { if (canManage) type = value as CustomFieldType; }} /></fieldset>{:else if ownedSelected}<dl class="settings-readonly-details"><div><dt>Type</dt><dd>{typeLabels[ownedSelected.type]}</dd></div></dl>{/if}{#if type === 'enum'}{#if ownedSelected?.enumOptions.length}<div><Label>Existing options</Label><p>{ownedSelected.enumOptions.join(', ')}</p></div>{/if}<div class="field-stack"><Label for="field-options">{ownedSelected ? 'Add options' : 'Options'}</Label><Input id="field-options" bind:value={enumOptions} disabled={!canManage} placeholder="new, open, closed" /></div>{/if}{#if !ownedSelected || ownedSelected.applicability === 'custom_asset_types'}<fieldset class="settings-choice-field" disabled={!canManage}><legend>Applies to</legend><ChoiceGrid label="Field applicability" options={[{ value: 'all_assets', label: 'All assets' }, { value: 'custom_asset_types', label: 'Selected asset types', disabled: ownedSelected?.applicability === 'all_assets' }]} selectedValues={[applicability]} onSelect={(value) => { if (canManage) applicability = value as CustomFieldApplicability; }} /></fieldset>{/if}{#if applicability === 'custom_asset_types'}<fieldset class="settings-choice-field" disabled={!canManage}><legend>Asset types</legend><ChoiceGrid label="Field asset type targets" options={targetOptions} selectedValues={targetIds} emptyMessage="No eligible active asset types." onSelect={toggleTarget} /></fieldset>{/if}{/if}
{#if keyError}<p class="settings-field-error" role="alert">{keyError}</p>{/if}
{#snippet footer()}<Button.Root variant="outline" disabled={saving} onclick={requestClose}>Cancel</Button.Root>{#if routeAction === 'edit' && ownedSelected}<Button.Root variant="destructive" href={href({ resourceId: ownedSelected.id, action: 'archive' })} onclick={(event) => { event.preventDefault(); onNavigate(href({ resourceId: ownedSelected.id, action: 'archive' })); }}>Archive</Button.Root>{/if}<Button.Root disabled={saving || !canManage || !dirty || !displayName.trim() || (routeAction === 'new' && (!key.trim() || Boolean(keyError)))} onclick={() => { void save(); }}>Save</Button.Root>{/snippet}</WorkspaceTaskSheet>

<WorkspaceConfirmationDialog open={discardOpen} title="Discard changes?" description="Your unsaved custom field changes will be lost." onOpenChange={(open) => { discardOpen = open; }}>
{#snippet cancel()}<Button.Root variant="outline" onclick={() => { discardOpen = false; }}>Keep editing</Button.Root>{/snippet}
{#snippet action()}<Button.Root variant="destructive" onclick={() => { discardOpen = false; onNavigate(collectionHref); }}>Discard changes</Button.Root>{/snippet}
</WorkspaceConfirmationDialog>

<WorkspaceTaskSheet open={detailOpen} title={selected?.displayName ?? 'Custom field'} description={selected?.scope === 'tenant' && level === 'inventory' ? `Inherited from ${tenant.name}.` : `${selected?.lifecycleState === 'archived' ? 'Archived' : 'Managed'} in ${contextName}.`} closeHref={collectionHref} onCloseLink={(event) => { event.preventDefault(); onNavigate(collectionHref); }} onOpenChange={(open) => { if (!open) onNavigate(collectionHref); }}>
{#if !selected}<SettingsCollectionState kind="error" title="Field unavailable" message="This record may no longer exist or may not be visible to this account." />{:else}<dl class="settings-readonly-details"><div><dt>Stable key</dt><dd>{selected.key}</dd></div><div><dt>Type</dt><dd>{typeLabels[selected.type]}</dd></div><div><dt>Ownership</dt><dd>{selected.scope === 'tenant' ? `Inherited from ${tenant.name}` : `Only in ${contextName}`}</dd></div><div><dt>Applies to</dt><dd>{selected.applicability === 'all_assets' ? 'All assets' : `${selected.customAssetTypeIds.length} asset types`}</dd></div></dl>{/if}
{#snippet footer()}<Button.Root variant="outline" onclick={() => onNavigate(collectionHref)}>Done</Button.Root>{#if selected?.scope === 'tenant' && level === 'inventory' && canManageTenant}<Button.Root href={manageInheritedHref(selected)} onclick={(event) => { event.preventDefault(); onNavigate(manageInheritedHref(selected)); }}>Manage in {tenant.name}</Button.Root>{:else if ownedSelected && ownedSelected.lifecycleState === 'archived' && canManage}<Button.Root href={href({ resourceId: ownedSelected.id, action: 'delete' })} variant="destructive" onclick={(event) => { event.preventDefault(); onNavigate(href({ resourceId: ownedSelected.id, action: 'delete' })); }}>Delete permanently</Button.Root><Button.Root href={href({ resourceId: ownedSelected.id, action: 'restore' })} onclick={(event) => { event.preventDefault(); onNavigate(href({ resourceId: ownedSelected.id, action: 'restore' })); }}>Restore</Button.Root>{/if}{/snippet}
</WorkspaceTaskSheet>

<WorkspaceConfirmationDialog open={confirmationOpen} title={routeAction === 'delete' ? 'Delete custom field permanently' : routeAction === 'restore' ? 'Restore custom field' : 'Archive custom field'} description={routeAction === 'delete' ? 'This cannot be undone. Deletion can be blocked while active assets store a value.' : routeAction === 'restore' ? 'The field will be validated against its current targets before becoming available.' : 'Existing stored values remain, but the field is hidden from normal editing and validation.'} busy={saving} onOpenChange={(open) => { if (!open && !saving) onNavigate(collectionHref); }}>{#if formError}<p class="settings-form-error" role="alert">{formError}</p>{/if}{#if ownedSelected}<p><strong>{ownedSelected.displayName}</strong></p>{/if}{#snippet cancel()}<Button.Root variant="outline" disabled={saving} onclick={() => onNavigate(collectionHref)}>Cancel</Button.Root>{/snippet}{#snippet action()}<Button.Root variant={routeAction === 'delete' || routeAction === 'archive' ? 'destructive' : 'default'} disabled={saving || !ownedSelected || !canManage} onclick={() => { void lifecycleAction(); }}>{routeAction === 'delete' ? 'Delete permanently' : routeAction === 'restore' ? 'Restore' : 'Archive'}</Button.Root>{/snippet}</WorkspaceConfirmationDialog>
