import { t } from '$lib/presentation/localization';

const actionMessages = {
  "label.provisioned": "audit.action.label.provisioned",
  "label.viewed": "audit.action.label.viewed",
  "label.resolved": "audit.action.label.resolved",
  "label.rendered": "audit.action.label.rendered",
  "label.content_downloaded": "audit.action.label.content_downloaded",
  "label.templates_listed": "audit.action.label.templates_listed",

  "archive_job.viewed": "audit.action.archive_job.viewed",
  "archive_job.created": "audit.action.archive_job.created",
  "archive_job.updated": "audit.action.archive_job.updated",
  "notification_device.updated": "audit.action.notification_device.updated",
  "notification_device.revoked": "audit.action.notification_device.revoked",
  "notification_device.viewed": "audit.action.notification_device.viewed",
  "notification.created": "audit.action.notification.created",
  "notification.read": "audit.action.notification.read",
  "notification.unread": "audit.action.notification.unread",
  "notification.listed": "audit.action.notification.listed",
  "notification_preferences.viewed": "audit.action.notification_preferences.viewed",
  "notification_preferences.updated": "audit.action.notification_preferences.updated",
  "tenant.created": "audit.action.tenant.created",
  "tenant.viewed": "audit.action.tenant.viewed",
  "tenant.listed": "audit.action.tenant.listed",
  "tenant.updated": "audit.action.tenant.updated",
  "tenant.archived": "audit.action.tenant.archived",
  "tenant.restored": "audit.action.tenant.restored",
  "tenant.deleted": "audit.action.tenant.deleted",
  "inventory.created": "audit.action.inventory.created",
  "inventory.exported": "audit.action.inventory.exported",
  "inventory.viewed": "audit.action.inventory.viewed",
  "inventory.listed": "audit.action.inventory.listed",
  "inventory.updated": "audit.action.inventory.updated",
  "inventory.archived": "audit.action.inventory.archived",
  "inventory.restored": "audit.action.inventory.restored",
  "inventory.deleted": "audit.action.inventory.deleted",
  "inventory_access.granted": "audit.action.inventory_access.granted",
  "inventory_access_grant.viewed": "audit.action.inventory_access_grant.viewed",
  "inventory_access_grant.listed": "audit.action.inventory_access_grant.listed",
  "inventory_access.revoked": "audit.action.inventory_access.revoked",
  "inventory_invitation.created": "audit.action.inventory_invitation.created",
  "inventory_invitation.viewed": "audit.action.inventory_invitation.viewed",
  "inventory_invitation.listed": "audit.action.inventory_invitation.listed",
  "inventory_invitation.accepted": "audit.action.inventory_invitation.accepted",
  "inventory_invitation.expiration_updated": "audit.action.inventory_invitation.expiration_updated",
  "inventory_invitation.revoked": "audit.action.inventory_invitation.revoked",
  "inventory_invitation.cancelled": "audit.action.inventory_invitation.cancelled",
  "inventory_invitation.deleted": "audit.action.inventory_invitation.deleted",
  "custom_asset_type.created": "audit.action.custom_asset_type.created",
  "custom_asset_type.viewed": "audit.action.custom_asset_type.viewed",
  "custom_asset_type.listed": "audit.action.custom_asset_type.listed",
  "custom_asset_type.updated": "audit.action.custom_asset_type.updated",
  "custom_asset_type.archived": "audit.action.custom_asset_type.archived",
  "custom_asset_type.restored": "audit.action.custom_asset_type.restored",
  "custom_asset_type.deleted": "audit.action.custom_asset_type.deleted",
  "custom_field_definition.created": "audit.action.custom_field_definition.created",
  "custom_field_definition.viewed": "audit.action.custom_field_definition.viewed",
  "custom_field_definition.listed": "audit.action.custom_field_definition.listed",
  "custom_field_definition.updated": "audit.action.custom_field_definition.updated",
  "custom_field_definition.archived": "audit.action.custom_field_definition.archived",
  "custom_field_definition.restored": "audit.action.custom_field_definition.restored",
  "custom_field_definition.deleted": "audit.action.custom_field_definition.deleted",
  "asset.created": "audit.action.asset.created",
  "asset.viewed": "audit.action.asset.viewed",
  "asset.listed": "audit.action.asset.listed",
  "asset.searched": "audit.action.asset.searched",
  "asset.updated": "audit.action.asset.updated",
  "asset.moved": "audit.action.asset.moved",
  "asset.archived": "audit.action.asset.archived",
  "asset.restored": "audit.action.asset.restored",
  "asset.deleted": "audit.action.asset.deleted",
  "asset.checked_out": "audit.action.asset.checked_out",
  "asset.returned": "audit.action.asset.returned",
  "asset.return_details_updated": "audit.action.asset.return_details_updated",
  "asset_tag.created": "audit.action.asset_tag.created",
  "asset_tag.listed": "audit.action.asset_tag.listed",
  "asset_tag.updated": "audit.action.asset_tag.updated",
  "asset_tag.archived": "audit.action.asset_tag.archived",
  "attachment.created": "audit.action.attachment.created",
  "attachment.viewed": "audit.action.attachment.viewed",
  "attachment.listed": "audit.action.attachment.listed",
  "attachment.content_downloaded": "audit.action.attachment.content_downloaded",
  "attachment.archived": "audit.action.attachment.archived",
  "attachment.restored": "audit.action.attachment.restored",
  "attachment.deleted": "audit.action.attachment.deleted",
  "audit_record.listed": "audit.action.audit_record.listed",
  "undoable_operation.undone": "audit.action.undoable_operation.undone",
  "undoable_operation.redone": "audit.action.undoable_operation.redone",
  "provider_profile.created": "audit.action.provider_profile.created",
  "provider_profile.viewed": "audit.action.provider_profile.viewed",
  "provider_profile.listed": "audit.action.provider_profile.listed",
  "provider_profile.updated": "audit.action.provider_profile.updated",
  "provider_profile.enabled": "audit.action.provider_profile.enabled",
  "provider_profile.disabled": "audit.action.provider_profile.disabled",
  "provider_profile.archived": "audit.action.provider_profile.archived",
  "provider_profile.credential_replaced": "audit.action.provider_profile.credential_replaced",
  "provider_profile.tested": "audit.action.provider_profile.tested",
  "conversation_workflow.revision_created": "audit.action.conversation_workflow.revision_created",
  "conversation_workflow.viewed": "audit.action.conversation_workflow.viewed",
  "conversation_workflow.listed": "audit.action.conversation_workflow.listed",
  "conversation_workflow.activated": "audit.action.conversation_workflow.activated",
  "conversation_evaluation_case.revision_created": "audit.action.conversation_evaluation_case.revision_created",
  "conversation_evaluation_case.viewed": "audit.action.conversation_evaluation_case.viewed",
  "conversation_evaluation_case.listed": "audit.action.conversation_evaluation_case.listed",
  "conversation_evaluation_run.created": "audit.action.conversation_evaluation_run.created",
  "conversation_evaluation_run.progressed": "audit.action.conversation_evaluation_run.progressed",
  "conversation_evaluation_run.cancelled": "audit.action.conversation_evaluation_run.cancelled",
  "conversation_evaluation_run.viewed": "audit.action.conversation_evaluation_run.viewed",
  "conversation_evaluation_run.listed": "audit.action.conversation_evaluation_run.listed",
  "voice_provider_configuration.updated": "audit.action.voice_provider_configuration.updated",
  "import_job.previewed": "audit.action.import_job.previewed",
  "import_job.started": "audit.action.import_job.started",
  "import_job.completed": "audit.action.import_job.completed",
  "import_job.failed": "audit.action.import_job.failed",
  "import_job.cancellation_requested": "audit.action.import_job.cancellation_requested",
  "import_job.cancelled": "audit.action.import_job.cancelled",
  "import_job.history_removed": "audit.action.import_job.history_removed",
  "import_job.credential_cleaned": "audit.action.import_job.credential_cleaned",
} as const;

const targetMessages = {
  "archive_job": "audit.target.archive_job",
  "notification_device": "audit.target.notification_device",
  "notification": "audit.target.notification",
  "notification_preferences": "audit.target.notification_preferences",
  "tenant": "audit.target.tenant",
  "inventory": "audit.target.inventory",
  "inventory_access_grant": "audit.target.inventory_access_grant",
  "inventory_invitation": "audit.target.inventory_invitation",
  "custom_asset_type": "audit.target.custom_asset_type",
  "custom_field_definition": "audit.target.custom_field_definition",
  "asset": "audit.target.asset",
  "asset_tag": "audit.target.asset_tag",
  "attachment": "audit.target.attachment",
  "audit_record": "audit.target.audit_record",
  "undoable_operation": "audit.target.undoable_operation",
  "provider_profile": "audit.target.provider_profile",
  "import_job": "audit.target.import_job",
  "conversation_workflow": "audit.target.conversation_workflow",
  "conversation_evaluation_case": "audit.target.conversation_evaluation_case",
  "conversation_evaluation_run": "audit.target.conversation_evaluation_run",
} as const;

const sourceMessages = {
  "api": "audit.source.api",
  "conversation": "audit.source.conversation",
  "mcp": "audit.source.mcp",
  "import": "audit.source.import",
  "background_job": "audit.source.background_job",
  "system": "audit.source.system",
} as const;

export function auditVocabularyLabel(group: 'action' | 'target' | 'source', code: string): string | undefined {
  const messages = { action: actionMessages, target: targetMessages, source: sourceMessages }[group];
  if (!Object.hasOwn(messages, code)) return undefined;
  return t(messages[code as keyof typeof messages]);
}
